### ISSUE TITLE
Ability to select circuit visit

### ISSUE THREAD

**Issue by AnsNie** [AntonyCorbett/OnlyT#1]
Hi!

I would like to have ability to select circuit visit when using automatic -mode, like in the SoundBox timer currently. This would do the necessary changes (change midweek meeting timer order a bit and replace bible study with service talk, and split weekend WT into WT and public talk).
This is of course possible also by using manual or file-modes, but that means some extra-work for sound desk operators during circuit visits.

Best regards,
Anssi

**Comment by AntonyCorbett** [comment]
Done
