### ISSUE TITLE
Localisation: need to split up 'Enabled' strings

### ISSUE THREAD

**Issue by josslamberti** [AntonyCorbett/OnlyT#109]
Issue
Given I am translating OnlyT
When I am prompted to choose a translation for "Enabled"
Then the string is used in 2 places that may not be compatible
It can be an issue as the item in question may be plural or singular and feminine or masculine

E.g. "horloge" (clock) is feminine in French and many translations for "Remote apps" are going to be plural.
So in French, the web clock may be "Activée" and the remote apps "Activées".

**Comment by AntonyCorbett** [comment]
@josslamberti well spotted!

**Comment by josslamberti** [comment]
Yeah but sorry for not spotting the other 2 occurrences!

**Comment by josslamberti** [comment]
@AntonyCorbett  have you missed a step with the labels? See screenshot with build 25:

![image](https://user-images.githubusercontent.com/30600877/47049959-a34f8f80-d196-11e8-9699-e576e8723a4c.png)

**Comment by AntonyCorbett** [comment]
@josslamberti It's ok, it's just that your changes weren't available at teh time of my build. All looks good on my system and you should see the "enabled" updates in teh next pre-release
