### ISSUE TITLE
Meeting countdown: changes require an app restart

### ISSUE THREAD

**Issue by josslamberti** [AntonyCorbett/OnlyT#122]
Given I have changed the list of meeting starting times but not restarted the app
When the current time reaches within 5 minutes of the next meeting
Then the meeting countdown is not shown

Should we add a 4th note (or a separate note to match the language change note format) indicating that an app restart is required for the changes to be taken into account?
Unless changing these values should not require an app restart, obviously.

**Comment by AntonyCorbett** [comment]
@josslamberti That probably means that the countdown had already been displayed once in the session. OnlyT has a "safety feature" that guarantees that it only displays the countdown timer once per session. This prevents it accidentally being shown during a meeting.

**Comment by AntonyCorbett** [comment]
@josslamberti I can't reproduce this. Are you able to provide some steps please?

**Comment by josslamberti** [comment]
After some investigation, I was indeed missing an important step. Try this:
Select no monitor and restart the app.
Then on the next run, select a monitor, then set a time that will trigger the meeting countdown. It won't appear. See first video: https://app.box.com/s/cc0wl96e73ia7gw5r4jhxj484ogzv7fi

I think there's a conflict between the normal timer display and the meeting countdown. To a point that if you select a different monitor while the countdown is running, then the countdown ignores the change of monitor and stays where it is. See the 2nd video: https://app.box.com/s/9b5sezvwl2f6fq446b1urjdg235aqk77

Actually I didn't manage to record a 3rd observation as I was writing this reply but if you let the countdown run down after having selected no monitor, then the meeting countdown gives way to the normal clock even though the app is now set not to use any monitor.

**Comment by josslamberti** [comment]
I think what happens is that the code that runs the meeting countdown does not check if the monitor selected in the settings has changed. The data's loaded once but never updated.
And when it hands back to the main clock, it's the old data that is used again.

**Comment by AntonyCorbett** [comment]
@josslamberti fixed in 1.1.0.29
Thanks for your help with this one!

**Comment by josslamberti** [comment]
@AntonyCorbett May I argue that it may not be fixed in build 29?
See this video where I can reproduce the issues described above: https://app.box.com/s/byu6rmnwqg74jxac6h23o88mrzy5ixq8

**Comment by AntonyCorbett** [comment]
@josslamberti thanks - build 29 clearly doesn't contain the fix!

**Comment by AntonyCorbett** [comment]
@josslamberti build 30 should be ok

**Comment by josslamberti** [comment]
At last I got a chance to verify it. Fix confirmed in build 32, thanks!
