### ISSUE TITLE
OnlyT Remote and Windows 10 (Home)

### ISSUE THREAD

**Issue by AlexandrePRUVOT** [AntonyCorbett/OnlyT#154]
Hello Antony,
OnlyM is awesome. OnlyV is awesome. OnlyT is awesome. So thank you very much. And thanks for the French translation of OnlyT.
I could not run OnlyT Remote on a Samsung Tablet (Android). I tried on two computers running Windows 10 Home with an administrator account. I searched for several days. I started by allowing data sharing and discovery of the network on the private network (I think it is necessary). And finally, I managed by running OnlyT as an administrator (while my account already has an administrator profile ...). At that moment, I was able to see OnlyT PC's timers on my tablet. It works with my two computers (Kingdom Hall and House). This looks like problem # 51.
Best regard.
Alexandre

**Comment by AntonyCorbett** [comment]
Hi Alexandre. Thanks for your kind words. My comment on #51 should apply here.
https://github.com/AntonyCorbett/OnlyT/issues/51#issuecomment-357587306
In a standard Windows installation, Elevation is only required to open the port.

**Comment by AlexandrePRUVOT** [comment]
Hello Antony,
The port was opened easily without executing OnlyT as an administrator (but the profile was already as administrator).
When I remove "run as administrator", the tablet does not see the timer of the PC.
When I put "run as administrator", the tablet sees the timer of the PC.

Note: In "Run as Administrator" mode, I receive the following message: "Do you want to allow the following program from an unknown publisher to make changes to this computer? "
(But I know how to make it disappear: I go to Control Panel / Accounts and User Protection / User Accounts / Change User Account Control Settings / Never Notify Me!)

Finally, this is not a bug because OnlyT works but, by dint of tearing my hair for a week, I became bald ;-)

Does this mean that the installation with Windows 10 Home is not a standard installation of Windows?

In any case, thank you. The brothers of our three congregations are starting to appreciate your very nice tools.
Cordially.
Alexandre
![onlyt_modif](https://user-images.githubusercontent.com/44783825/48025560-19b33200-e144-11e8-9590-2ce05a272b94.jpg)
.

**Comment by TizianoNoto** [comment]
> The port was opened easily without executing OnlyT as an administrator (but the profile was already as administrator).

Hi @AlexandrePRUVOT , did Windows pop out the same message you receive when choosing "run as administrator" after pressing the "Open port" button? (I strongly discourage to disable User Account Control!)

**Comment by AlexandrePRUVOT** [comment]
Hello,
This morning, I did some tests before leaving. I enabled windows notifications.
Note: I am already administrator by default. With my account, I can install or uninstall programs. My children with their user accounts can not. And in the present case, I do not use the real administrator account (the super administrator, the one hidden by default).
So when I run Only T as administrator, I have a first "Unknown Publisher" notification. Then when I start opening port 8096, no notification. My tablet sees the timer of the PC.
So when I'm not running Only T as administrator, I do not have notification when I open OnlyT. But when I start opening port 8096, I have an "Unknown Publisher" notification. There, my tablet does not see the timer of the PC.
Opening port 8096 in the firewall has never been a problem. The administrator's permission for this makes sense.
Best regard.
Alexandre
![firewall](https://user-images.githubusercontent.com/44783825/48049579-6841ea00-e19f-11e8-873a-6c32f7dc1bbc.JPG)

**Comment by TizianoNoto** [comment]
Please try opening OnlyT without choosing "as administrator". Go to Settings. Click Open port. You should see a notification from Windows about "OnlyTFirewallPorts.exe". Enter administrator password (if required) then Yes. Now both firewall rule and HTTP reservation (this can also be done with `NETSH` in command prompt) should be set for the TCP port.

It looks like you have some duplicate firewall rule for OnlyT, I recommend some cleanup.

**Comment by AlexandrePRUVOT** [comment]
Hello Tiziano,
1) I cleaned the firewall (I just left a single instance for opening the port 8096 by OnlyT).
![firewall1](https://user-images.githubusercontent.com/44783825/48150886-32e0ed80-e2c0-11e8-93e0-987b2ad51f8e.JPG)

2) I launched Only without choosing "as administrator" and I clicked on Open port. There was indeed a notification for the administrator. Then, a second occurrence appeared in the firewall.
![firewall2](https://user-images.githubusercontent.com/44783825/48150914-3ffddc80-e2c0-11e8-9dbe-45ee50435593.JPG)

3) I cleaned the firewall again. (Idem: the tablet only sees the timer of the PC if I run Only as administrator).
![screenshot_tablette](https://user-images.githubusercontent.com/44783825/48150934-4db36200-e2c0-11e8-974e-a934b89d65dd.png)

On the other hand, I do not know how to check the HTTP reservation (it goes far beyond my skills).
![netshconfigip](https://user-images.githubusercontent.com/44783825/48150948-573cca00-e2c0-11e8-8ec5-26143f5b2b84.JPG)

Best regard.
Alexander

**Comment by AlexandrePRUVOT** [comment]
Good evening,
Sorry, the previous tests were done with version 1.1.0.42 !
The problem of the multiplication of the opening of the ports in the firewall is solved since version 1.1.044 (from this morning). I just did the tests with this version.
However, I always have to run OnlyT as administrator.
Best regard.
Alexandre

**Comment by AntonyCorbett** [comment]
@AlexandrePRUVOT It could be that the url reservation was made for the admin account. Can I suggest you try another port? Load OnlyT (not elevated). Change port to another one of the values, e.g. 8097 and Open.  You'll need to change the port in the remote client too.

**Comment by TizianoNoto** [comment]
> On the other hand, I do not know how to check the HTTP reservation (it goes far beyond my skills).

In an elevated command prompt (in other words, run it as administrator) type
`netsh http show urlacl`

You should see this somewhere, probably one of the last entries:
```
URL prenotati           : http://*:8096/
    Utente: \Everyone
        In ascolto: Yes
        Delega: No
        SDDL: D:(A;;GX;;;WD)

```
Make sure _User_ is _Everyone_ and _Listening_ set to _Yes_

**Comment by AlexandrePRUVOT** [comment]
Hello Antony and Tizano (is that your name?),
I tried Antony's suggestion. And, it's the same thing. My tablet only sees the PC if I run OnlyT as administrator.
As Tizano asked, I typed netsh http show urlacl in "command prompt". And, I did not find a URL with port 8096 or 8097 open.
![netsh2](https://user-images.githubusercontent.com/44783825/48279190-1ffd2300-e450-11e8-877d-eec21c69fa58.JPG)
Wow! This is a good track for investigation.
Best regard.
Alexandre

**Comment by AntonyCorbett** [comment]
@AlexandrePRUVOT Thanks - this is useful. As @TizianoNoto mentions OnlyT creates both a firewall rule and HTTP reservation. It looks like the reservation is failing. Please would you try to create it manually at an elevated command line? The command looks like this for port 8096 and a French OS:

netsh http add urlacl url=http://*:8096/ user="Tout le monde"

Kind regards
Antony

**Comment by AlexandrePRUVOT** [comment]
Thank you @AntonyCorbett. I did as you asked me.
The URL reservation is done.
![netsh3](https://user-images.githubusercontent.com/44783825/48284506-e46a5500-e45f-11e8-84d6-476ad9392ffb.JPG)

And ... wonderful, it works well ! Thank you so much. Good night.
Alexandre

**Comment by TizianoNoto** [comment]
How curious. In the italian edition of Windows "_Everyone_" must be used and I assumed this would apply for all languages.

**Comment by AntonyCorbett** [comment]
@AlexandrePRUVOT I can see the bug in OnlyT code - it omits the quotation marks that are required when the localised "Everyone" string contains spaces!
