### ISSUE TITLE
language change

### ISSUE THREAD

**Issue by tevadalbnegru** [AntonyCorbett/OnlyT#155]
In the Kingdom Hall where we intend to use OnlyT we are more congregations (of different languages!). Whenever you have to enter the settings to change the language is a bit "difficult".
Could one or two small buttons be created in the main panel to change the language of the application directly? (languages that could be pre-selected in the settings pane).
Now I do not know how it could be done, that the language would be changed instant or that the application would have to be reopened again.
Could this be possible? Would it be useful for others?

**Comment by richfrantz** [comment]
You're making this harder than it has to be. Each congregation should have their own account. With their own language and other settings. Let Windows handle it.
________________________________

**Comment by TizianoNoto** [comment]
I agree that having different Windows accounts makes some things easier (e.g. global displayed language).

However, @tevadalbnegru can create different shortcuts for each congregation using the `/id=` option.

**Comment by TizianoNoto** [comment]
I agree that having different Windows accounts makes some things easier (e.g. global displayed language).

However, you can also create different shortcuts for each congregation using the `/id=` option.

**Comment by TizianoNoto** [comment]
I agree that having different Windows accounts makes some things easier (e.g. global displayed language).

However, you can also create different desktop shortcuts for each congregation with their own settings using the `/id=` option.

**Comment by AntonyCorbett** [comment]
@tevadalbnegru Hope the previous comments are of help.
