### ISSUE TITLE
Not a Bug - Just requesting assistance - .bat script

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyT#166]
Hi, I am wondering if anyone can help me please.

I am wanting to make our K-Hall PC as user friendly as possible and looking to make some of the programs start automatically at designated times.  I can use Task Scheduler but I am having difficulty getting the programs to work so thought I would use a .bat file.

Here is the script I have so far:

@echo off
TASKKILL /F /IM onlyt.exe
rem onlyt
cd C:\ProgramData\Microsoft\Windows\Start Menu\Programs\OnlyT
start onlyt.exe
exit

...but my PC cannot find 'OnlyT'.  
Is there a superior script that anyone can please suggest? - or can tell me what I am doing wrong?  
I tried this one as well but it also fails to find OnlyT:

@ECHO 
ECHO.
ECHO 
taskkill /IM OnlyT.exe /F
start C:\ProgramData\Microsoft\Windows\Start Menu\Programs\OnlyT
ECHO.
CLS
EXIT

Sorry to be a pain!
Kind regards
Simon

**Comment by AntonyCorbett** [comment]
@Chipperchap if you want to start OnlyT from the start menu folder you need to specify "OnlyT.lnk" rather than "OnlyT.exe"

**Comment by Chipperchap** [comment]
Ahh, that did it.  I got one of the scripts working, 
Thank you Antony 😄

**Comment by richfrantz** [comment]
The exe is in Program Files (x86), your path is wrong.
________________________________
