### ISSUE TITLE
Change timing report folder

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#175]
Not a very important option, but it's nice to have

**Comment by AntonyCorbett** [comment]
@LvDaniel thanks, but I’ve decided against this. It complicates the interface and symbolic links provide a solution if really necessary.

**Comment by AntonyCorbett** [comment]
@LvDaniel I believe symbolic links are supported. However, Google also has an application that allows you to sync any folder.

**Comment by LvDaniel** [comment]
@AntonyCorbett I respect your opinion but considering that OnlyM and OnlyR have already the option to change the folder, will be nice to be consistent and align OnlyT from this point of view as well. I don't think will have a big impact on the interface.
But this is just the way I see things, you might have strong reasons for not doing this.
Just wanted to share my toughs as I know you're open to feedback.

**Comment by LvDaniel** [comment]
@AntonyCorbett does the thumbs up means you'll reconsider this in the future? Thanks.
