### ISSUE TITLE
view timing report

### ISSUE THREAD

**Issue by richfrantz** [AntonyCorbett/OnlyT#176]
A button to open the timing report after it is created. Just to save the step of  having to navigate to the folder manually.

**Comment by AntonyCorbett** [comment]
@richfrantz There's a button in teh Settings page, but I may add one to the notification bar too

**Comment by richfrantz** [comment]
The button in settings only opens the folder, as far as I can tell. That may be because I don't have any reports yet. If there was a report IN the folder, would it have opened it?
________________________________

**Comment by AntonyCorbett** [comment]
@richfrantz the button in settings opens the folder.

**Comment by AntonyCorbett** [comment]
Requirement is for a button on the notification bar to open the newly-generated report.

**Comment by richfrantz** [comment]
thank you
________________________________

**Comment by AntonyCorbett** [comment]
Done in latest pre-release
