### ISSUE TITLE
Possibility to resize OnlyT window

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#177]
Just a nice to have

**Comment by AntonyCorbett** [comment]
@LvDaniel thanks. Please would explain why it's needed? Is it just that the text or buttons are too small / large, etc?

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks. 

See also #73

**Comment by LvDaniel** [comment]
Yep, it's related.
We'll be perfect to have both of them.

**Comment by LvDaniel** [comment]
Something like this...
![jwl-onlyt-onlym](https://user-images.githubusercontent.com/45002147/49395405-0db89100-f73f-11e8-8021-e69875d67724.jpg)

**Comment by AntonyCorbett** [comment]
Thanks for your suggestion. I am closing the issue for now as I am trying to limit the feature-set to essentials.
