### ISSUE TITLE
Music while meeting countdown is it possible?

### ISSUE THREAD

**Issue by Emvin** [AntonyCorbett/OnlyT#179]
Just like soundbox, when the meeting countdown start 5 mins. before the actual time, a background music (_Kingdom song or original song from JW Library_) playing and gradually fade the music and stop when the meeting countdown also stop. Hope you'll consider. thanks brothers.

**Comment by AntonyCorbett** [comment]
@Emvin thanks for the suggestion, but JW Library has a feature for playing background music on shuffle, and I won't be duplicating any features.

**Comment by dazzathestag** [comment]
I’m sorry to message on a closed post - hope that acceptable ? I have Seen a couple of comments about JW Library being able to do a shuffle feature on the music - I can never find this and always have to start from song 1 by clicking the main play button which means we hear the same songs at the start of every meeting, if i click on say song 100 it stops after the song has finished. Can anyone please say where the shuffle function is please ?

**Comment by LvDaniel** [comment]
@dazzathestag after you click "Play all" button from the top, open the media player (click on the bottom bar). Shuffle button is on the bottom right.
![image](https://user-images.githubusercontent.com/45002147/51377294-363ff300-1b13-11e9-8041-bc97e6ee051c.png)

**Comment by dazzathestag** [comment]
Wow, never knew that, thankyou LvDaniel, that will make a huge difference, at least we can move to some new songs now 😂
