### ISSUE TITLE
Can the meeting countdown timer be overlaid on top of the JW Library Year text?

### ISSUE THREAD

**Issue by DanJermy** [AntonyCorbett/OnlyT#183]
Just updated and noticed that a separate monitor can be called out for the meeting countdown timer which is great.

Noting your comment @AntonyCorbett that a letter implied the year text should be displayed on the other screens, then it seemed logical that the ability to scale the timer was to allow this to overlay in the corner perhaps; however I cannot seem to find a way to allow both the countdown timer and the year text to display on the TVs at the same time.

Many thanks as always / Dan

**Comment by AntonyCorbett** [comment]
@DanJermy the letter says that the year text should be displayed on the media monitors before and after the meeting. For this reason, and for a long time, I resisted the requests to display the countdown on the media monitors. However, I acqiesced - it's up to the users to decide on this question rather than me. But you can't overlay the countdown on the year text - it's a technical limitation.

**Comment by bergerchemical** [comment]
So maybe the solution would be to be able to display the year text not from the JW Library application and from OnlyT, eg when displaying the time to start and after the meeting just display the year text.

**Comment by richfrantz** [comment]
The position I am going to propose to our BOE is that there is a difference between "before" the meeting and "immediately" before the meeting. If the year text is on the screen for 20 minutes before the meeting, but the timer is on the screen for 5 minutes immediately before the chairman calls to order, then the requirement of the letter has been met. We'll see.

**Comment by bergerchemical** [comment]
ok but things get complicated when switching: you need to enable / disable the display on the second screen in JWL settings ... I think..

**Comment by AntonyCorbett** [comment]
@bergerchemical no. When the countdown ends it automatically switches to JWL year text.

**Comment by AntonyCorbett** [comment]
> So maybe the solution would be to be able to display the year text not from the JW Library application...

@bergerchemical Yes, that is possible but the instruction is clear - JWL is to be used to display year text.

**Comment by bergerchemical** [comment]
ok :)

**Comment by AntonyCorbett** [comment]
@DanJermy "Transparent background" is now available in the latest pre-release
