### ISSUE TITLE
Adjustable countdown timer duration

### ISSUE THREAD

**Issue by richfrantz** [AntonyCorbett/OnlyT#184]
Not hardcoded to 5 minutes. User configurable. I'd like 2 minutes personally.

**Comment by AntonyCorbett** [comment]
@richfrantz Thanks for the suggestion. I'll leave it open to see if others feel strongly about this. My feeling is that it complicates the design and the requirement for configurable time is not compelling.

**Comment by AntonyCorbett** [comment]
@richfrantz I'll close this for the time being, but if anyone else raises the subject I'll link here. Sorry - it's difficult balancing time available with the weight of good suggestions!

**Comment by AntonyCorbett** [comment]
@richfrantz done
