### ISSUE TITLE
Countdown not displayed when OnlyT running in background

### ISSUE THREAD

**Issue by Jeremy909** [AntonyCorbett/OnlyT#187]
Only-T started the countdown but was not shown on Platform TVs because I think JW Library was the program in focus and Only-T was running in the background. As soon as I clicked on the Only-T window the countdown replaced the Yeartext.

Only-T needs to be able to able to take control of a selected screen even if it is running in the background or even minimised.

**Comment by AntonyCorbett** [comment]
@Jeremy909 Correct. It's not possible for an inactive top-level window to 'steal the focus' away from another application. This makes sense if you think about it from a user's perspective - we're using JWL and suddenly one of its windows disappears! It's one of a number of compromises and caveats we have to live with.

**Comment by richfrantz** [comment]
I wonder if our terminology is sending us down the wrong path.

Instead of people asking if the countdown timer can "overlay" the year text shown by JWL. Is "picture in picture" the route to take?

That IS what we're shooting for right? Two video sources, one screen, simultaneously.

If so, I suspect that isn't a coding issue, but a TV configuration issue.
________________________________

**Comment by AntonyCorbett** [comment]
@Jeremy909 See also this note: https://github.com/AntonyCorbett/OnlyM/wiki/JW-Library-Compatibility

**Comment by AntonyCorbett** [comment]
@richfrantz Yes, pip can be accomplished with 3rd-party software (eg.g OBS), but it may add to the complexity for most users.

**Comment by AntonyCorbett** [comment]
@richfrantz The ideal solution is a single application to cover all the requirements. But we may never get that and instead have to either simplify or accept some additional complexity.

**Comment by Jeremy909** [comment]
Does Selecting "Always on Top" help?

**Comment by AntonyCorbett** [comment]
@Jeremy909 No

**Comment by Jeremy909** [comment]
I haven't had chance to test this yet, but does this mean that once the 5 minute countdown has begun, if anyone interacts with JW Library making it the focused window, the countdown would be replaced by the JW Library yeartext?

**Comment by AntonyCorbett** [comment]
If JWL was already open then no, a user can work with JWL without imterrupting the Countdown. However, if the user explicity brings the JWL year text window to the fore then it will take precedence.
