### ISSUE TITLE
Pre-meeting timer monitor (TV) did not return to JWL

### ISSUE THREAD

**Issue by 65Lsmith** [AntonyCorbett/OnlyT#192]
I had tested the system before meeting and appeared to work fine. After testing, I closed both OnlyT and JWL. Restarted JWL then OnlyT and started music. Count down timer started on TVs. When timer ended TVs went black. TVs would not show JWL or year text. Time came for 1st song, song lyrics would not show on TVs. At end of song, closed both apps, and started SoundBox. What did I do wrong?
Thanks for all of you all's work on this. I have JW compatibility mode checked.

**Comment by AntonyCorbett** [comment]
@65Lsmith thanks for feedback. Please see:
https://github.com/AntonyCorbett/OnlyT/wiki/JW-Library-Compatibility
I suspect that OnlyT was not the active application when the timer finished so it could not restore the JWL year text window.

**Comment by AntonyCorbett** [comment]
@65Lsmith I just updated the wiki to provide further information.

**Comment by 65Lsmith** [comment]
Thanks Tony. Thank you and all that helped for all the hard work you have done to help us bring great meetings to honor Jehovah.
