### ISSUE TITLE
Installer localisation

### ISSUE THREAD

**Issue by TizianoNoto** [AntonyCorbett/OnlyT#198]
Installer should be localized as well, in my opinion.

If this saves time for you I'll add the languages in the script and then try to open a pull request. If I find out that some languages don't have an [official or unofficial translation](http://www.jrsoftware.org/files/istrans/) we could ask the translators if they wish to translate the _Default.isl_ file as well.

**Comment by AntonyCorbett** [comment]
@TizianoNoto thanks for your offer. I found that with SoundBox 3.1 (where the installer _was_ localised, it created a lot of confusion. Users assumed that this was the place where UI language was chosen for the whole application.

**Comment by TizianoNoto** [comment]
You're welcome.
And you're right, if one doesn't read the dialog box carefully he may believe what you say.

What about **not** choosing a language? Setup wizard automatically selects the system language, if included, otherwise the default one, English. OnlyM does the same at the first start.

**Comment by AntonyCorbett** [comment]
@TizianoNoto yes that would work. Perhaps we can keep this in reserve as we have a fair amount of localisation (OnlyR and OnlyV) still to do.

**Comment by AntonyCorbett** [comment]
@TizianoNoto I don't think I will be translating the installer, so am closing the issue. Thanks for all your helpful feedback.

**Comment by TizianoNoto** [comment]
@AntonyCorbett I understand. It may seem like just an eye-candy but I came up with this idea after realizing that some brothers in charge of audio-visual departments don't understand English very well and get easily worried if the computer pops up messages in foreign languages. 😄

---

I'm posting my proposed solution in case you're going to reconsider it in the future.

Inno Setup is set to **automatically use the system language** if it matches one of the included _official_ or _unofficial_ translation files; if no match is found it defaults to English.

*Official* translations are already included in the program whereas *unofficial* ones can either be downloaded from Inno's [Translations](http://www.jrsoftware.org/files/istrans/) page or created on the spot then added to the [Installer](https://github.com/AntonyCorbett/OnlyT/tree/master/Installer/)/Languages folder.

The following lines are added in [Installer/OnlyTSetup.iss](https://github.com/AntonyCorbett/OnlyT/blob/master/Installer/OnlyTSetup.iss):
```
[Setup]
ShowLanguageDialog=no

[Languages]
Name: "<official translation>"; MessagesFile: "compiler:Languages\<OfficialTranslation>.isl"
Name: "<unofficial translation>"; MessagesFile: "..\Installer\Languages\<UnofficialTranslation>.isl"
...
```

I already have a list of languages drafted after looking at the Crowdin project's page.
