### ISSUE TITLE
Wiki translation

### ISSUE THREAD

**Issue by TizianoNoto** [AntonyCorbett/OnlyT#199]
"With great software comes great documentation".

Marvel references apart, I think it would be nice if the wiki can be translated as well. Maybe a subfolder for each language code containing the guide files? Unless there's a better way to do this in GitHub.

**Comment by AntonyCorbett** [comment]
@TizianoNoto thanks for the suggestion. I've researched the idea and it seems the best way to approach this would be for a translator to create a new github repository for the new localised wiki (you can easily clone the original as a starting point). I could then add a link from the English wiki (and from the readme file) to any localised wikis.

This would mean the translator would be responsible for the translation, and for keeping it up to date and accepting any pull requests (updates) from other users.

So, if you are in agreement, and would like to take on a localised version of the wiki, please go ahead and let me know the repository address so I can add a link.

Thanks
Antony

**Comment by TizianoNoto** [comment]
@AntonyCorbett You're welcome. Me and Manuel actually started working on it but progress has been slow because of other commitments. We'll let you know as soon as it's finished.

**Comment by bergerchemical** [comment]
I started translating the wiki into Polish. I am sorry to write in a closed thread but I do not want to start a new one in this matter
https://github.com/bergerchemical/OnlyT/wiki/Instrukcja
