### ISSUE TITLE
Option: Turn off analog clock

### ISSUE THREAD

**Issue by hakerskipl** [AntonyCorbett/OnlyT#20]
Hey,

Thanks a lot for developing OnlyT, but we can't use it, because it's still missing an option to turn off an analog clock. Actually, digital clock it's too small on our time display. To my best knowledge, other facilities in the area will have the same problem.

Best regards, Matthew
Torun, Poland

**Comment by AntonyCorbett** [comment]
Understood. We need the ability to configure the elements on the timer display

**Comment by donavan1** [comment]
An other option if possible a fade in /out between analog clock and the digital clock.

**Comment by AntonyCorbett** [comment]
@donavan1 
>An other option if possible a fade in /out between analog clock and the digital clock.<
Please elaborate. I suspect it should be a different issue.

**Comment by donavan1** [comment]
Hi Antony

i meant to say Analog timer (if possible) can display before the talk starts, and then switch to digital ( full screen) at the start of the talk. just like in soundbox but with the analog clock.

or 

can this analog clock and digital as is be landscape in the current setup.

**Comment by AntonyCorbett** [comment]
All done

**Comment by donavan1** [comment]
Hi

Tested app, Great stuff.

**Comment by donavan1** [comment]
Hi Antony 
Here one more, hopefully !!!!........ 

Meeting start time remaining feature.



pre-set the time the meeting will start.

![meet start](https://user-images.githubusercontent.com/8216036/31011996-88d46760-a510-11e7-96f9-7e00c2a34e9b.PNG)

 result display, as in 3min, 5min etc..... before meeting starts.

![meeting start time remaining](https://user-images.githubusercontent.com/8216036/31012015-9b0971f0-a510-11e7-8da3-e3c2a90feed7.PNG)
