### ISSUE TITLE
JWL and OnlyT countdown timer

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#201]
This is not an issue nor a feature request. Just wanted to make sure that I understand correctly how JWL and OnlyT countdown meeting are working together after reading the Wiki, JWL Compatibility section and few threads which touched this topic. 
Maybe will be helpful for others as well.

**Comment by LvDaniel** [comment]
First thing you need to enable JWL Compatibility option on OnlyT side if you want to display the countdown timer on the main monitor.

After, the operator should do the flowing:
- when preparing for the meeting, start JWL first and after OnlyT 
- 5 minutes before the meting, make sure OnlyT is the active application. If JWL or any other app is active, OnlyT won't be able to display the countdown timer on the media monitor. Still, if at some point during those 5 minutes you'll make OnlyT active, countdown timer will be displayed.
- right before the countdown will end, you need to make OnlyT the active application again. If not, OnlyT won't be able to return the monitor to JWL (to display the year text and other media). In this case the only solution to return the media monitor to JWL will be to click the JWL icon on the Windows taskbar and select the secondary window.
- this applies if you want to use JWL and OnlyM in parallel. But obviously OnlyM is active when you want to display an image and when you hide (stop) it. Still, you need to be careful when you run a video, as you need to have OnlyM active when the video automatically finishes.

There's nothing that can be done to change this as this is a restriction imposed by Windows.
  @AntonyCorbett have I understood correctly how it works?

**Comment by AntonyCorbett** [comment]
@LvDaniel Yes, that's about it. Of course this applies only if you are using the meeting countdown timer and want to display it on the main media monitor(s).

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for confirming. All it's clear now.

**Comment by TizianoNoto** [comment]
I also found out on my test pc that JWL media window is not restored if all JWL windows are minimized. At least the main window must be shown on screen so that everything works as expected.

**Comment by AntonyCorbett** [comment]
@TizianoNoto  I thought I had fixed this in a recent release.

**Comment by AntonyCorbett** [comment]
@LvDaniel @TizianoNoto I've done some work on this and JW Compatibility mode should be improved in a release next weekend.

**Comment by AntonyCorbett** [comment]
@LvDaniel @TizianoNoto The current release has improved JWL compatibility support
