### ISSUE TITLE
Timings reports options not exist.

### ISSUE THREAD

**Issue by rafik73github** [AntonyCorbett/OnlyT#204]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by rafik73github** [comment]
Timings reports options not exist. Windows 10. OnlyT 1.1.0.46.
![onlyt](https://user-images.githubusercontent.com/20180132/48984602-c5292400-f0fd-11e8-9870-9e7df262da1b.jpg)

**Comment by AntonyCorbett** [comment]
It wasn't added until 1.1.0.47
