### ISSUE TITLE
OnlyT Report Question

### ISSUE THREAD

**Issue by JakeLHX** [AntonyCorbett/OnlyT#205]
Hi Anthony, two questions, However I think I am just missing a trick...

We use OnlyT **not** on any external monitor as yet, just as an app on the PC to time and record the duration of talks... However when you stop the timing on the current talk it moves on to the next talk, but the previous talk when selected is reset as if to start timing again... This does not change (from my testing) with the persist setting. 

As such we are unable to catch the duration of the previous talk and are unable to go back and see it

This would be fine if we could use the End-of-meeting report feature in .54, however when testing this I have gotten a "Report NOT generated" after the data has been analysed. 

I wonder if you could expand for me on what the requirements are for the report to be generated? 

Thankyou very much for your time and effort!

**Comment by AntonyCorbett** [comment]
@JakeLHX Please see the wiki page:

https://github.com/AntonyCorbett/OnlyT/wiki/Timing-Reports

OnlyT will only generate a report if the recorded timing data is assessed to be from a real meeting, e.g, reasonable duration, etc.

**Comment by JakeLHX** [comment]
Of course, look forward to testing at the next meeting :)

Aside from this and using an external display however, we will be unable to (For instance:)

- Finish timing current talk
- Start timing next talk
- During timing (Or even after timing has finished), select previous talk to see and record (On paper for the sake of argument) the duration

Am I understanding correctly?

**Comment by LvDaniel** [comment]
@JakeLHX if you use OnlyT app on Android or iOS you can see the time for each talk.
But I agree that would be useful to see it on OnlyT the main app, like we used to see it on SoundBox.

**Comment by LvDaniel** [comment]
@AntonyCorbett would be possible to see the whole list without needing to scroll for the last item?
![image](https://user-images.githubusercontent.com/45002147/49022283-29e78b80-f19d-11e8-8a8e-cb1aade9353a.png)

Also to have the talks that have passed grayed out? Or having the timing at the end, something like this?
![image](https://user-images.githubusercontent.com/45002147/49022619-f3f6d700-f19d-11e8-8988-95d74e5a9b36.png)
Just a proposal...

**Comment by AntonyCorbett** [comment]
@JakeLHX 

> Am I understanding correctly?

Yes

**Comment by AntonyCorbett** [comment]
@LvDaniel 

> Do you think those are eligible to be feature requests? If so, I can open separate requests.

Yes to both questions.

Thank you!
Antony

**Comment by AntonyCorbett** [comment]
Implemented in 1.1.0.55
