### ISSUE TITLE
View the full list of items

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#206]
View the full list of items (talks) without needing to scroll for the last item.
And if you consider appropriate, keep the items in chronological order without moving the current item at the top of the list (and missing from the normal order).

Example: Item 2 it's at the top of the list, missing between Item 1 and Item 3.
![image](https://user-images.githubusercontent.com/45002147/49087041-a9895f00-f25e-11e8-8fdf-d2178cf419f2.png)

**Comment by AntonyCorbett** [comment]
Implemented in 1.1.0.55

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks a lot.
