### ISSUE TITLE
See the duration for the previous talks

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#207]
Would be nice to have the option to see the duration of previous talks.
Or maybe have the talks that have passed grayed out.

Example:
![image](https://user-images.githubusercontent.com/45002147/49087347-654a8e80-f25f-11e8-8fbe-e7737e6db924.png)

**Comment by Blann** [comment]
Occasionally the operator has accidentally started the next timer too soon and needs to reset it – under these circumstances the ability to re-select a previous part is needed.

**Comment by Blann** [comment]
Yes, that’s what we currently do – I may have misunderstood but I thought it was being suggested that the ability to do that be removed (grayed out?)

**Comment by richfrantz** [comment]
Us too. I hope it isn't removed.
________________________________

**Comment by LvDaniel** [comment]
It was sugested to be greyed out just as a visual efect for the items completed already, but still to be able to re-select and reset them if needed

**Comment by AntonyCorbett** [comment]
Implemented in 1.1.0.55

**Comment by LvDaniel** [comment]
@AntonyCorbett nice done. Thank you!
