### ISSUE TITLE
Timing report

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#208]
@AntonyCorbett this is not a feature request nor a bug. 
Just wanted to give you more feedback on the timing report feature which is in the pre-relase phase.

**Comment by LvDaniel** [comment]
Last day when we had the meeting I've run SoundBox Timer and OnlyT in parallel (there might be few seconds differences between them). Reports look pretty similar. 
I've noticed is that OnlyT added +10 seconds on the "counsel and commendation" for Item 1 and Item 2 - but this is just an observation as 10 seconds added won't make any difference to the report.
But on "counsel and commendation" for Item 3, OnlyT reported -00:45 while SoundBox reported +00:35 which is more realistic.

I assume that for "Introductory Segment" the normal time is 5 minutes and starts from the closest quarter till opening comments are starting.
While "Concluding Segment" are added automatically with 5 minutes length starting the end off concluding comments.
How about "Interim Segment"? Does it take in consideration middle song duration, or has a default time value? And starts in short time after Ministry Item 3 is finished? 

I've attached both reports (sorry that the SoundBox one is generated in a different language).
And a big thanks Antony for all your great work.

[OnlyT 2018-11-28.pdf](https://github.com/AntonyCorbett/OnlyT/files/2628616/OnlyT.2018-11-28.pdf)
[SoundBox 2018-11-28.pdf](https://github.com/AntonyCorbett/OnlyT/files/2628617/SoundBox.2018-11-28.pdf)

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks. If the final item in the ministry section is a student talk the only way we can estimate the counsel duration is to deduct an amount of time for the interim song from the start of the next timer. I also use a fixed duration of 3m 20s for the interim segment, which seems to accord best with the layout of the midweek agenda. The report is currently mis-calculating the counsel duration on the final item.

**Comment by AntonyCorbett** [comment]
Fixed in 1.1.0.55

**Comment by LvDaniel** [comment]
@AntonyCorbett thank you.

**Comment by LvDaniel** [comment]
@AntonyCorbett seems like the counsel duration for the final ministry item it's still skipped.
Please see below the report from the last meeting, while using 1.1.0.56 version.
[2018-12-05.pdf](https://github.com/AntonyCorbett/OnlyT/files/2652605/2018-12-05.pdf)
