### ISSUE TITLE
Language updates

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#211]
@AntonyCorbett apologize for opening a new request, but I don't know another way to contact you directly. Please close it right away after you see it.
In my language (Romanian) I can see some translations that can be improved. Also some items are not yet translated. Do you know how we can update those? Should I contact the language translator and let him know or there's another way?
If it's needed, I can contribute to the translation as well.
Thanks for you're help and understanding.

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks. Would you be willing to help with Romanian translation? If so, please go to Crowdin.com, sign up for an account then let me know your Crowdin user name. Then I can send you an invitation.

**Comment by LvDaniel** [comment]
@AntonyCorbett my Crowdin username is the same as GitHub one, LvDaniel. Thanks Antony.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks for invitation. I've translated the missing items and updated some others. Should I do anything else? I saw that there's an aproove option on each item, is this needed? Or it's enough the
