### ISSUE TITLE
Manual Bell option?

### ISSUE THREAD

**Issue by JakeLHX** [AntonyCorbett/OnlyT#212]
**Is your feature request related to a problem? Please describe.**
The auto-bell is not always something we want to use. For new students etc etc.

**Describe the solution you'd like**
We would like an option on the student talks for a manual bell alert. 

**Describe alternatives you've considered**
Buying a physical bell 😆

**Comment by AntonyCorbett** [comment]
@JakeLHX One option is to disable the automatic bell for the current talk (just click the bell icon to toggle). However, if you disable it then there's no manual bell option, so I understand the request.

**Comment by AntonyCorbett** [comment]
@JakeLHX Available in latest release
