### ISSUE TITLE
meetings for field service

### ISSUE THREAD

**Issue by rafik73github** [AntonyCorbett/OnlyT#215]
Can you add meetings for field service timer?

**Comment by LvDaniel** [comment]
@rafik73github you can create a new shortcut with a different "/id=" and change the settings to File-based mode. Use "talk_schedule.xml" file and change it according to your needs. More details in [Wiki](https://github.com/AntonyCorbett/OnlyT/wiki) "Main > Mode" section.

**Comment by JonMcFly** [comment]
Use a watch.
Getting the timing right for a field service meeting is not vital or important.
Need to stop requesting unnecessary features to these apps and keep them simple.

**Comment by AntonyCorbett** [comment]
@rafik73github thanks for the suggestion. @LvDaniel points to a solution.
