### ISSUE TITLE
Timer counts up for Public Talk only

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#216]
@AntonyCorbett I don't know if this is an eligible feature request, but this is up to you and the others if they find it useful.
For the Midweek meeting and Watchtower Study our congregation uses the timer counting down as it's the best way to see the time allocated for each talk as we're using adaptive timing. But for the Public Talk most of the speakers ask to have the timer counting up.
I know that there's a option which allows us to toggle between counting up and down, but this means that operator must specify each time the timer to count up for the Public Talk. And accidentally he might change it for some other talks clicking on the arrow.
We can train the operators to be careful on this, but I was wondering, is it possible to have an option (checkbox) in the settings menu to have the timer counting up automatically for Public Talk only? For the rest of the talks, it should count down. Eventually when this option is enabled, "Timer counts up" option might be grayed out.

**Comment by AntonyCorbett** [comment]
@LvDaniel thanks for the suggestion. My own feeling is that this would be an extra complication. We have the ability to specify a default direction and we are also able to make an ad-hoc change. Specifying different defaults on a per-talk basis may be confusing. I'll leave the issue open for a while for any other comments. Thanks for the feedback!

**Comment by LvDaniel** [comment]
@AntonyCorbett I think you're right. Ad-hoc change of the direction should be the way to do it if it's really needed. It's better to keep things simple and avoid any confusion. Thanks
