### ISSUE TITLE
Question: How does automatic mode one-way work with songs and prayer?

### ISSUE THREAD

**Issue by mcoleson** [AntonyCorbett/OnlyT#223]
We are just starting with OnlyT.
Would like to use the feature with automatic one-way adaptive. If my understanding is correct, if a speaker goes overtime, only will adapt subsequent talks so the alloted time is shortened.
1. First, is that the correct understanding?
2. Second, how does this work with the song mid-meeting song?  Does OnlyT take the song into account?
3. I assume you start onlyT after the first song and prayer, correct?
Thank you!

**Comment by LvDaniel** [comment]
@mcoleson
1. If there is an overtime till that moment, OnlyT will reduce the length just for Living Part 1 (and Part 2 if it's the case), for the Bible Study (midweek meeting) and for the Watchtower Study (weekend meeting). Other talks won't be adapted.
2. Yes, takes a default (fixed) 3:20 time for the mid song.
3. Yes, you start the timer on the Opening Comments section.

**Comment by AntonyCorbett** [comment]
@mcoleson Further to @LvDaniel, the adaptive timing is only applied in the 2nd half of the meetings (both midweek and weekend). Note that the official directions don't specify the start time for each item; just the duration. But OnlyT infers the item start times (allowing 5 mins for concluding segment and a small amount for changeover). So at the start of an item, OnlyT's adaptive timing can calculate any rolling deficit and apportion it between remaining items.
