### ISSUE TITLE
The size of the clock seconds

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#224]
@AntonyCorbett this isn't something important, and it might be just my opinion so feel free to close it.
I was thinking that it would be better to have the seconds smaller (~ half the size of hours/minutes) which allows the hours/minutes to have a bigger size and be more visible.
Something like below (current/proposed).

![seconds size](https://user-images.githubusercontent.com/45002147/49686215-03f5ab80-fafa-11e8-81b9-a0c3a35727f7.png)

**Comment by AntonyCorbett** [comment]
@LvDaniel Made a small adjustment to size and position
