### ISSUE TITLE
OnlyT window stuck as very compressed title bar

### ISSUE THREAD

**Issue by PacoSupreme** [AntonyCorbett/OnlyT#23]
**Computer:** W10 64-bit with a touchscreen monitor
**Version of OnlyT:** At the time we saw the issue we were using 1.0.15. We have since upgraded to 1.0.16. 
**Background:** We have been using onlyT with great success until the other night during the annual meeting test. The computer is configured to start onlyT, onlyR, Chrome, JW Library, DisplayFusion (makes it easy to switch the video playing one one monitor to another) and a script that sends an IR command to two Keene KIRAM modules to turn on our TVs on startup. We rebooted the computer and the brother operating the computer shutdown the programs. He was successful on all but the OnlyT. 

**Problem:** Somehow the OnlyT got into a state where all you can see is the a fraction of the Title bar which consists of the onlyT logo, minimize maximize and X. It looks like it was manually resized to be a really small unusable size. I cannot figure out how to get it out of that state. I have tried uninstalling and reinstalling. 

Is there a file that saves the last windows size and position that I can reset to get only onlyT to open in a usable state?

**Comment by donavan1** [comment]
![capture](https://user-images.githubusercontent.com/8216036/30856933-3e813984-a2ba-11e7-86f4-711ef3b37b61.PNG)

**Comment by PacoSupreme** [comment]
The above screen grab is exactly what we see. I can't figure out how to recover it.

**Comment by donavan1** [comment]
commented

**Comment by donavan1** [comment]
This is what happens when I run the OnlyT1.0.0.16 version,, try installing
1.0.0.15 I now also get the same display.

**Comment by AntonyCorbett** [comment]
Settings are stored in options,json the users roaming profile, e.g. C:\Users\Antony\AppData\Roaming\OnlyT\1\options.json

Suggest you remove the "AppWindowPlacement" entry

**Comment by PacoSupreme** [comment]
@AnthonyCorbett Sure. I can get it for you tonight. I will also try resetting the AppWindowPlacement entry.
