### ISSUE TITLE
OnlyT, OnlyM and OnlyV icons

### ISSUE THREAD

**Issue by elspag** [AntonyCorbett/OnlyT#232]
I don't know if this can be useful to anyone else, but in our KH the desktop icons were zoomed, because of the screen resolution making them tiny.
But OnlyT, OnlyM and OnlyV icons don't zoom correctly. OnlyR works fine, as it can be seen here:
![2018-12-18 09_34_42-nvidia geforce overlay](https://user-images.githubusercontent.com/11458239/50144994-6abc5700-02a8-11e9-845d-0fe0af38b82b.png)
Is it possible to add multiple sizes icon to OnlyT, OnlyM and OnlyV?
Thanks

**Comment by AntonyCorbett** [comment]
@elspag Thanks. I'll update them soon, but please find isons you can use here (just replace the icons in the shortcuts):

[Desktop.zip](https://github.com/AntonyCorbett/OnlyT/files/2690123/Desktop.zip)

**Comment by elspag** [comment]
> @elspag Thanks. I'll update them soon, but please find isons you can use here (just replace the icons in the shortcuts):
> 
> [Desktop.zip](https://github.com/AntonyCorbett/OnlyT/files/2690123/Desktop.zip)

Perfec! Thanks, Antony
