### ISSUE TITLE
Timing summary special characters

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#235]
I don't know if this is happening for other languages which have special characters, but for my language (Romanian) on the second page of the generated report (Timing summary), the special character "ș" is displayed "?" and "ă" is displayed "a". Some other special characters like "î" and "â" are displayed correctly.
This happens only to the 2nd page (Timing summary), on the first one (Timing report) all the characters are displayed correctly. I noticed this behavior on SoundBox report as well.
[2018-12-19.pdf](https://github.com/AntonyCorbett/OnlyT/files/2696754/2018-12-19.pdf)

**Comment by AntonyCorbett** [comment]
Fixed in latest pre-release. @LvDaniel Thanks for reporting this.

**Comment by LvDaniel** [comment]
@AntonyCorbett Thanks for fixing it.
