### ISSUE TITLE
Time format on Web Clock does not match program settings

### ISSUE THREAD

**Issue by timjobutler** [AntonyCorbett/OnlyT#237]
**Describe the bug**
The time format setting used in our hall is _24-hours (leading zero)_. However, the Web Clock shows the time as _12-hour (leading zero)_ without the AM/PM indicator.

**To Reproduce**
1. Go to 'Settings > Main > Digital clock format'
2. Change setting to '24-hour (leading zero)'
3. Open web browser to the remote app IP address and view the time when the timer is not in use

**Expected behavior**
The time format on the Web Clock should mirror the format configure in the program settings.

**Screenshots**
I didn't have an opportunity to capture a screenshot.

**Desktop (please complete the following information):**
 - Windows 10 (latest release)
 - OnlyT 1.1.0.58
 - OnlyT app (latest version)

**Comment by AntonyCorbett** [comment]
@timjobutler thanks for picking this up. Fix will be in next release (or pre-release)

**Comment by timjobutler** [comment]
@AntonyCorbett Thanks for providing the fix
