### ISSUE TITLE
how to show timer on web cl

### ISSUE THREAD

**Issue by carosado3** [AntonyCorbett/OnlyT#239]
Hello, 

I am new to OnlyT. Thank you all for your hard work. I just have a question on how to get the actual timer to show up on my tablet. 

I would like to control the timer from our main pc but to show the countdown/countup on the tablet. 

If there is a thread about this please show me. 

Thanks

CR

**Comment by carosado3** [comment]
I figured it out. I just had to hit play and it shows on the monitor. 

Thank you.

**Comment by AntonyCorbett** [comment]
Hi

@carosado3 glad you're sorted. Please review the project wiki under "web clock" and "remote apps" for more info.
