### ISSUE TITLE
It is possible to add the option to choose between analog clock or digital clock 

### ISSUE THREAD

**Issue by TiagoPaisAlmeida** [AntonyCorbett/OnlyT#24]
Have the possibility to choose between have the actual clock design, but also choose to have all the clocks in digital as in soudbox clock.
Thank you again

**Comment by TechMan88** [comment]
yes i would also love to have Both options. thanks Anthony Grt Job wkll install at our Hall nxt week, Brothers Approved it today. after 2 mths without soundbox they are excited again.

thank you

**Comment by AntonyCorbett** [comment]
done
