### ISSUE TITLE
Zusammenkunfts-Countdown wird nicht automatisch auf Bildschirm gestartet und gibt nach Beendigung den Bildschirm nicht automatisch wieder frei

### ISSUE THREAD

**Issue by MisterTob** [AntonyCorbett/OnlyT#240]
wenn der Countdown zu Beginn der Zusammenkunft startet, wird er nicht automatisch auf dem Bildschirm angezeigt. Man muss erst nochmal darauf klicken.
Und wenn der Countdown abgelaufen ist, bleibt der Bildschirm schwarz. Es wird nicht automatisch JwLibrary wieder angezeigt, sondern erst nach dem man wieder auf die App geklickt hat.

Unsere Einstellungen sehr ihr im Anhang
![screenshot 8](https://user-images.githubusercontent.com/46131813/50422382-aa57e580-084a-11e9-87ae-7787838dd4cf.png)

**Comment by AntonyCorbett** [comment]
Please review the wiki. In particular Automatic mode => JW Library compatibility mode.

**Comment by AntonyCorbett** [comment]
@MisterTob Hi. Yes you have the correct settings. However, the wiki explains important features and limitations of the JWL compatibility mode particularly with respect to the countdown timer. Please re-read this section: https://github.com/AntonyCorbett/OnlyT/wiki/JW-Library-Compatibility

Note the recommendation "It is recommended that you do not display the countdown timer on the main media monitors, but if you really want to please read on:"

Then the section describes how to ensure that the countdown cooperates with JWL. In particular, OnlyT must be the active (foreground) application when the countdown starts. Furthermore, if it can't redisplay the JWL year text whne the countdown closes you will have to do it manually by activating the JWL media monitro via the relevant task bar button.
