### ISSUE TITLE
Meeting Countdown

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#241]
We are using JW Library and OnlyT. I have OnlyT configured to display the meeting countdown on our Media displays. 5 minutes before our meeting begins, I see the "Close Countdown" button appears in OnlyT, but the countdown does not appear on the TV's. The only way I can get the countdown to display is by closing OnlyT and opening it again.

**Comment by AntonyCorbett** [comment]
Hi. Please review the wiki, including the page on JWL compatibility. Thanks, Antony

**Comment by AntonyCorbett** [comment]
@scottys94 JwlMediaWin fixes this.

https://github.com/AntonyCorbett/JwlMediaWin
