### ISSUE TITLE
Not reverting to JW Library after countdown

### ISSUE THREAD

**Issue by searlosus** [AntonyCorbett/OnlyT#249]
We are having a problem where if OnlyT is not the active window when the countdown timer ends the second screen reverts to the PC background rather than the JW Library second screen. It reverts to JW Library second screen if it is the active window. Has anyone else had this issue?

**Comment by Blann** [comment]
This is a limitation of Windows 10 – see the Wiki under 'JW Library Compatibility'.

**Comment by searlosus** [comment]
Thank you, sorry, should have noticed that.

**Comment by AntonyCorbett** [comment]
@searlosus JwlMediaWin fixes this.

https://github.com/AntonyCorbett/JwlMediaWin

**Comment by searlosus** [comment]
Thank you so much, it now works perfectly.
