### ISSUE TITLE
Unable to display in secondary monitor

### ISSUE THREAD

**Issue by EfreAvilaJr** [AntonyCorbett/OnlyT#25]
I'm using a Surface Pro 4 as main , HDMI cable out to second monitor (Sharp TV) from Surface, it is setup as extended monitor (it works with Soundbox). When I toggle the target display from PC to TV it doesn't switch, it stays on PC. Help wanted 😎

**Comment by AntonyCorbett** [comment]
Please would you change the scaling to 100% on your surface monitor and see if that fixes it

**Comment by EfreAvilaJr** [comment]
Hi Antony, tried 100% scaling and no change I'm still unable to switch the target display.

**Comment by AntonyCorbett** [comment]
Can you try another monitor please? Also check that your video driver is up to date.

**Comment by AntonyCorbett** [comment]
No response - closing
