### ISSUE TITLE
OnlyT timer window constraint issue

### ISSUE THREAD

**Issue by Barracudasteak** [AntonyCorbett/OnlyT#254]
**Describe the bug**
When the timer is showing on the monitor, the time overlaps the edge of the screen and misses off the last number. I have tried changing the resolution size of the monitor but it doesnt make a difference. Any ideas?

**Desktop (please complete the following information):**
 - Windows 10

**Comment by AntonyCorbett** [comment]
@Barracudasteak Is the monitor in "portrait" mode? ie. what is the pixel resolution (width x height)? A screenshot would be useful please.

**Comment by Barracudasteak** [comment]
Hi. This is what we currently see. I can't confirm the actual resolution it's set at, but I have tried changing the res to other settings and the end is still cut off regardless of which one is used.

Any ideas?

Thanks

**Comment by AntonyCorbett** [comment]
@Barracudasteak Is the monitor in "portrait" or "landscape" mode please? I didn't receive your screenshot - please would you re-send?

**Comment by Barracudasteak** [comment]
![img_1614](https://user-images.githubusercontent.com/46380850/51620103-95de3a00-1f29-11e9-9c75-04ed160d074b.jpg)

Hi Antony - the monitor is in landscape mode - hopefully the image will attach this time! :) thanks

**Comment by AntonyCorbett** [comment]
@Barracudasteak Thanks for the image. Have you checked to ensure that the monitor is displaying other content correctly? e.g. drag a notepad window over to the monitor and maximize it. Can you see the full extent of the notepad window including the 3 command buttons top right of the caption bar?

**Comment by AntonyCorbett** [comment]
Closing now - no response, please reopen if needed.
