### ISSUE TITLE
Show current time and countdown time in digital mode

### ISSUE THREAD

**Issue by TiagoPaisAlmeida** [AntonyCorbett/OnlyT#26]
Thank you four your last change, that leave us to choose between digital ad analog clock current time.
But it is better if possible to show during the meeting the current time in digital mode and also at the same time during the several parts the countdown clock in digital (same as in soundbox). For our kingdom hall the better way is to speaker sees is part time and also the current time, both in digital mode and in the same screen.
Thank you again for your beautiful work.

**Comment by hakerskipl** [comment]
But please make it as an option, because in our KH it's not necessary. So, it will great to could disable it.

**Comment by AntonyCorbett** [comment]
done
