### ISSUE TITLE
Why does the clock disappear when not in use

### ISSUE THREAD

**Issue by dazzathestag** [AntonyCorbett/OnlyT#265]
In the past when the clock / timer has not been timing an item it always used to stay live as a simple clock which was useful for the person on the platform ie to see when the meeting was due to start for example.
For a number of months now the screen simply goes black when no timer is running and only “lights up” when the timer is switched on.
I cant see any settings that would alter this - is it how it should be or could we have the option to keep the clock displayed ?
Thanks
Darren

**Comment by AntonyCorbett** [comment]
@dazzathestag Hi Darren. You're right - there are no settings to modify the behaviour. I can't think what might be the cause. Perhaps you could start investigating by changing the Main => Monitor to your PC's primary monitor.

**Comment by AntonyCorbett** [comment]
Closing now as no response to suggestion. Please reopen if needed.
