### ISSUE TITLE
Add meeting day and time to file name of report

### ISSUE THREAD

**Issue by ucphinni** [AntonyCorbett/OnlyT#266]
**Is your feature request related to a problem? Please describe.**
When congregations meet on the same day, the report may be overwritten multiple times until the last congregation gets its report.

**Describe the solution you'd like**
It would be nice if the program would automatically look at the start time of the first timer started to see if it slide within the range of a meeting time. For example, if my meeting time is set for Tuesday 7:30 p.m. and my first time or was started at 7:36 p.m., it is safe to assume that the Tuesday meeting was being followed and the report could be named the normal way with the Tue-1930 added to the end of the file name. This would allow for multiple congregations to review the reports and the reports not being clobbered. If a meeting start time could not be found, it is acceptable to drop the suffix. This could be due to a visiting congregation that is only temporarily meeting at the Kingdom Hall.

**Describe alternatives you've considered**
The ID configuration in a shortcut can be used. However, some Kingdom Halls like ours prefer to use one shortcut and only use IDs for out-of-band of band usage such as when we had the attendant meeting.

**Additional context***
The report itself might even be changed in order to reflect this feature. Under the global section where it shows all of the lateness and ahead of time meetings oh, it might be able to utilize this technique to show it by meeting time so that each congregation could get a record of their specific meeting timeliness without using the ID feature.

**Comment by LvDaniel** [comment]
Each congregation can use its own settings and in this case ther reports are generated separately. More details on wiki.

**Comment by AntonyCorbett** [comment]
Thanks for your feedback. The situation is a little more complex than presentation. OnlyT uses a database to store historian timing data and as it stands the same database is used for both congregations.  There are 2 solutions - separate Windows accounts or separate shortcuts with the command-line "id".

**Comment by ucphinni** [comment]
Ok. The database complexities make sense. Here is a different way to think about the feature. Would it makes sense to have a Auto ID generated using the start times?

Workflow would be as follows:

In the null Id configured onlyt, in the settings, under meeting start times, enter using following format
   <day> <time> [<id>]
On Startup, if onlyt, detects that it is started without a ID, it will look up the current day and time and figure out thenext meeting ID or the current meeting which ends 1 hour and 45 minutes from the start time.

This allow for the congregations to use a single shortcut while differentiating between multiple congregations. It will also handle the reports correctly.

Having each congregation restart onlyt for this feature does not seem like a big issue as most congregations do this already.

**Comment by ucphinni** [comment]
Just thought a little bit more about it. Only T does not have enforce the null ID requirement. There are some good use cases where if that is allowed in, it can be useful for special meetings as long as there are no loops in configuration.
________________________________

**Comment by AntonyCorbett** [comment]
@ucphinni Thanks. There are some difficulties associated with your proposal including the fact that OnlyT is used for applications other than standard cong meetings. I also think it adds unnecessary complexity. The solutions offered are comprehenisve and straightforward and - if I understand correctly - the only objection to using the command-line "id" option appears to be the extra shortcut. If this is the case, what is the rationale for it please? Appreciate your input!

**Comment by ucphinni** [comment]
Never tried multiple accounts under impression of more difficulties it rollout, maintenance  and cleanup.

Multiple shortcuts work but they are fragile as they get deleted and moved. I left instructions to recreate. (Copy shortcut from backup folder)

Concept: Single shortcut with no modification leads to less calls.

Sorry to make this difficult. You are doing an excellent job with this app.

Maybe there is a way to lock the desktop so nothing can be moved or deleted. I have to research.
________________________________
