### ISSUE TITLE
Required functions

### ISSUE THREAD

**Issue by nicerose78** [AntonyCorbett/OnlyT#267]
Sorry for my English.
Your program is very nice and functional but I would have some requests to make it even better.
1) Enter the times also for the president's advice to the students.
2) Ability to send messages (eg, Announcements, Comment from home)
3) Out of time flashing
4) After the end of the countdown display melodie's number

**Comment by AntonyCorbett** [comment]
@nicerose78 Thanks for your suggestions. In answer:

1. See #48 
2. See #10 
3. Please add as a new issue
4. See #60 and #7 

Please feel free to add comments / support to the existing items even if they are closed.
