### ISSUE TITLE
Flashing Overtime Indication

### ISSUE THREAD

**Issue by nicerose78** [AntonyCorbett/OnlyT#269]
new function required. 
- Out of time flashing
thanks a lot

**Comment by AntonyCorbett** [comment]
@nicerose78 Thanks. Suggested design: 

1. The visual overtime indication would be on the timer monitor only and _not_ on the OnlyT main window or web clock. 
2. The timer digits would flash slowly for a short fixed duration of 3 seconds starting at the talk duration expiry. 
3. The indication would be shown once only per talk. 
4. The indication would be optional and specified in the OnlyT settings. 
5. The setting would apply to all talks.

**Comment by nicerose78** [comment]
Perfect but I think it would be better if it flashed until the end of the speech

**Comment by LvDaniel** [comment]
@nicerose78 or perhaps once 30 seconds or once per minute

**Comment by LvDaniel** [comment]
@AntonyCorbett how about flashing on the OnlyT main window like this was in SoundBox? Are you considering this or is not an option? My opinion is that this will help the operator if he forgets to start the timer on time.

**Comment by AntonyCorbett** [comment]
> My opinion is that this will help the operator if he forgets to start the timer on time.

See #73

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks.

**Comment by Blann** [comment]
I wonder how necessary this is. If the timer monitor is in line of sight from the platform, surely the digits turning yellow, then red, is sufficient to indicate time is up (besides the actual timer itself)?

**Comment by LvDaniel** [comment]
In our case the timer monitor is on the right side of the hall (close to audio-video desk). Flashing would help in my opinion.

**Comment by AntonyCorbett** [comment]
Am closing for now. I have considered the FR but believe that a flashing "time up" signal is undignified and may even be distracting to others in the audience. If the feature is thought necessary, the issue of poor timing should perhaps be dealt with in another way. Just my opinion of course, but I have to balance the FRs with dev time available. Thanks for feedback!
