### ISSUE TITLE
Direction of countdown time

### ISSUE THREAD

**Issue by hakerskipl** [AntonyCorbett/OnlyT#27]
Hi,

Again I want to thank you for your great job, so fast responses and many hard and good work which you put in this project. Only T already help us to prepare our Kingdom Hall to transition to use JWL.

But it would be very helpful to have option for reverse the direction of count time. Because some of speakers want to see, how much time their already used in speech so they want to count-up timer, local speakers in other wise like to countdown timer which is already implemented. Often also on circuit assemblies, circuit overseers and Bethel travelers want to have count-up timer because their have prepared sketch of the speech for count-up timers.

Best regards,
Matthew

**Comment by donavan1** [comment]
Hi
The best timer app so far.

As you can see I love using pictures to describe my ideas, The "Direction of countdown time" is this similar to your idea.
![capture](https://user-images.githubusercontent.com/8216036/31118285-31a0ddbe-a82d-11e7-8717-fe4f1af179b0.PNG)

**Comment by AntonyCorbett** [comment]
@hakerskipl  done
