### ISSUE TITLE
Multiple timers running

### ISSUE THREAD

**Issue by Oldtimer99** [AntonyCorbett/OnlyT#270]
[removed template text]

**Comment by Oldtimer99** [comment]
Our KH has 3 congregations with separate accounts under Windows 10. Often, one of them leaves their account logged on (when shutting down) with a copy of OnlyT running.
When the next congregation logs on and runs OnlyT, then all apparently works fine, but OnlyT Remote connects to the previously started timer and not the copy now displayed and in use.
Is there a way to force OnlyT Remote to ignore copies of OnlyT that are running under a dormant account?

**Comment by richfrantz** [comment]
I didn't know this. We just restart the PC after every meeting. It only takes 30 seconds, so why not.
________________________________

**Comment by AntonyCorbett** [comment]
@richfrantz agreed. It's probably the best practice to close down.
