### ISSUE TITLE
Missing Student Talks

### ISSUE THREAD

**Issue by chadwick723** [AntonyCorbett/OnlyT#273]
Hi I am not seeing Student Talks in Automatic Mode. Is this correct?

**Comment by chadwick723** [comment]
![file-33](https://user-images.githubusercontent.com/46899772/51487108-7e0f8600-1d70-11e9-8bb4-3e9f9f095bc9.jpeg)

**Comment by AntonyCorbett** [comment]
@chadwick723 Are you using a recent version?

**Comment by chadwick723** [comment]
Yes upgraded to 1.2.0.1 latest today. Also tried reinstalling.

**Comment by AntonyCorbett** [comment]
Connected to the internet with no whitelist filter, etc?

**Comment by chadwick723** [comment]
We do have a filter. Opened it to allow this and that corrected it. Sorry did not realize that was setup as a feed. Thanks!

**Comment by AntonyCorbett** [comment]
@chadwick723 good point - I'll add a note about it in the wiki.
