### ISSUE TITLE
Modify html template

### ISSUE THREAD

**Issue by EfrainCabral** [AntonyCorbett/OnlyT#274]
In most kindom hall we only have 1 preview monitor. In sign language congregations, the speaker needs to see on the preview monitor(usually used to show the timer) the signal resulting from the video mixer at all times. For this reason it is not possible to display the timer on that preview monitor.

The majority of sign language congregations have video mixers that allow streaming. A possible solution to this problem would be to modify html template, with the aim of embedding an html tag pointing to the streaming url.  In this way the timer and the resulting video could be displayed simultaneously.

I tried to modify OnlyT.resources.dll without any results.

The first option I propose tries to avoid having to modify the application. It would simply mean making a custom modification in html template.  However, another option would be the following: video mixers allow to send the video signal through usb to PC, as if it were a webcam. It would be possible to develop the option of being able to embed the capture in the timer display monitor ?

Thank you very much for your good work.

**Comment by AntonyCorbett** [comment]
@EfrainCabral The html template you mention is used to serve the web clock _not_ the timer monitor. 

See #234 for more suggestions.

Thanks for your feedback!
