### ISSUE TITLE
Adjustable countdown timer duration

### ISSUE THREAD

**Issue by KieranP** [AntonyCorbett/OnlyT#279]
Firstly, thank you for creating OnlyM and OnlyT. We've been using them since the beginning of the year, and for the most part, they are working well.

**Is your feature request related to a problem? Please describe.**
Our congregation always used a 1 minute countdown with SoundBox. OnlyT seems to be hard coded to 5 minutes, which is too long IMO.

**Describe the solution you'd like**
The ability to adjust the duration of the countdown, specifically to set to a 1 minute countdown.

**Comment by AntonyCorbett** [comment]
See also #184

**Comment by Blann** [comment]
The 5-minute countdown is in line with regional convention standards. Works fine for us, although I appreciate not every congregation is the same.

**Comment by AntonyCorbett** [comment]
@KieranP done
