### ISSUE TITLE
Oversized Timer window

### ISSUE THREAD

**Issue by Jeremy909** [AntonyCorbett/OnlyT#28]
The timer digits are oversized and cut-off as a result. I've attached an image of what I see.

![onlyt](https://user-images.githubusercontent.com/32488090/31130307-ed772e32-a84e-11e7-99b8-20744ecdba03.jpg)

**Comment by donavan1** [comment]
Have you tried re-installing the app?

**Comment by AntonyCorbett** [comment]
An update will fix it. Otherwise, close the app, delete the options file (see below) and restart:

C:\Users\[your name]\AppData\Roaming\OnlyT\1\options.json

**Comment by Jeremy909** [comment]
Yes that fixes it but only the 1st time I run the program. When I close it
it and run again it does it again.

**Comment by AntonyCorbett** [comment]
You don't say whether you updated or deleted the options file. Please download and install the latest version (1.0.0.22) and let me know what happens.

**Comment by Jeremy909** [comment]
Uninstalling and reinstalling makes no difference. Deleting the options
file fixes it but only for the 1st time I run the program. When I close it
it and run again it does it again.

**Comment by AntonyCorbett** [comment]
@Jeremy909 I have found the issue - your monitor scaling is greater than 100%. I will fix in the next release. Thanks for your help.
