### ISSUE TITLE
Any chance to contribute to translation work?

### ISSUE THREAD

**Issue by shinjonghwan** [AntonyCorbett/OnlyT#282]
**Is your feature request related to a problem? Please describe.**

No problem at all. Thank you so much for building this beautiful timer in advance. We've been using this timer since the beginning of last year. Every update was provided so adequately. Time report feature was especially useful in our cong. We thank you so much for your hard work. Some congregations here, in Korea, are also using this timer in meetings, but they are not comprehensive in english. So I **wonder if there is any chance to contribute to translation work.**

And also wonder if there is any ways that user can UI(like changing font, background color, clock shape or color scheme)?

Thanks once again for your generous spirit.

**Comment by AntonyCorbett** [comment]
@shinjonghwan Thanks for your feedback.

> I wonder if there is any chance to contribute to translation work.

Yes. Please create an account in Crowdin.com and let me know your crowdin user name and language you want to work on. There are currently 2 translated projects - OnlyM and OnlyT so please let me know if you want to help on one or both. Many thanks for your kind offer!

>And also wonder if there is any ways that user can UI(like changing font, background color, clock shape or color scheme)?

No (other than by changing the source code).

**Comment by shinjonghwan** [comment]
Thanks for quick reply.
My secular work is front-end web developing here, in Korea.
Here is my Crowdin account : Roy_Shin (https://crowdin.com/profile/Roy_Shin)
And I’d like to work on onlyT translation first, and language is Korean.
If it is done well, hopefully I want to work on onlyM as well!
Thank you so much! If there is anything I can do for you, feel free to let me know!
Best Regards.


나의 iPad에서 보냄

2019. 2. 11. 오후 6:03, Antony Corbett <notifications@github.com> 작성:

**Comment by AntonyCorbett** [comment]
@shinjonghwan Thanks. I have sent the invitation.

**Comment by AntonyCorbett** [comment]
@shinjonghwan Thanks for starting on the Korean translation. When bros are working on translations, every week or so I add a new pre-release build with the latest translations in them. See here for today's:

https://github.com/AntonyCorbett/OnlyT/releases/tag/1.2.0.2

**Comment by shinjonghwan** [comment]
Thanks a lot, brother Antony!
One of our brother in our cong sent a application to you via Crowdin.com.
His account is thdwlgns1914@gmail.com.
He wants to help me to translate it.
It would be appreciated if you accept him to join this work.
Thanks a lot, once again.

나의 iPad에서 보냄

2019. 2. 14. 오후 6:24, Antony Corbett <notifications@github.com> 작성:

**Comment by AntonyCorbett** [comment]
@shinjonghwan Hi. I accepted a request from a Korean translator on Friday.
