### ISSUE TITLE
Remote Timer App to keep screen awake

### ISSUE THREAD

**Issue by timjobutler** [AntonyCorbett/OnlyT#287]
**CURRENT SITUATION**
Currently the remote timer app does not keep the screen awake requiring the user to unlock the device repeatedly depending on their device's screen lock setting.

**PROPOSED CHANGE**
Provide a new option in the Settings to allow the user to choose whether the app will keep the device's screen awake or not.

**Comment by AntonyCorbett** [comment]
@timjobutler iOS or Android please? I'll advise the developer.

**Comment by timjobutler** [comment]
@AntonyCorbett Yes, important detail! My devices are running Android 8.0.

Thanks Antony

**Comment by MattDelmarter** [comment]
This option is already present on iOS. Open the settings and make sure "Keep Awake" is enabled.

I will double check the Android settings screen, but I thought the option was there for Android as well...

**Comment by LvDaniel** [comment]
@MattDelmarter seems like this is no present in Android version. Thanks for adding it if possible.

**Comment by heltfeil** [comment]
Google Play is riddled with apps that override native screen wake timer.

**Comment by de1mat** [comment]
I have just pushed out a new Beta for OnlyT Remote to the Android Play Store. It includes a new option in settings to keep the device awake.

The update also offers support for Android 10, and an optional Fullscreen Timer when the device is rotated into Landscape Orientation (similar to the iOS feature).

**Comment by AntonyCorbett** [comment]
@de1mat Thanks!

**Comment by LvDaniel** [comment]
@de1mat great news, thanks.
Do you think will be possible to adjust the timing from the Android app? If so, I can raise a request for this. Thanks for your efforts.

**Comment by de1mat** [comment]
> Do you think will be possible to adjust the timing from the Android app? 

Stage 1 of making this possible is that the OnlyT API must support changing timings. There is already a ticket open about this here: https://github.com/AntonyCorbett/OnlyT/issues/138

Once the API support is in place, then yes you can request support for this feature in the Remote app. FYI the proper place to do this would in the Issue Tracker for the Remote app, which is here: https://gitlab.com/imatt/onlyt/public/issues

**Comment by de1mat** [comment]
The new update is now live on the Play Store. I believe this issue can be solved @AntonyCorbett.

https://www.facebook.com/RemoteForOnlyT/posts/440306313260976
https://twitter.com/RemoteForOnlyT/status/1183530275248070656

**Comment by LvDaniel** [comment]
@de1mat thanks for reminding this. I completely forgot there's already a feature request opened for this.
