### ISSUE TITLE
Countdown Timer Wont Start on Wednesdays

### ISSUE THREAD

**Issue by huah007** [AntonyCorbett/OnlyT#289]
Thank you so much for the features of the timer. We love the countdown feature but it is having a problem starting up. We can get it to work on Sundays if we open the OnlT app within the 5 minute countdown window but it wont work on wednesdays for some reason. we have our meeting times entered as follows: Tue 19:00
Wed 07:30
Thu 07:30
Sat 11:00
Sun 10:00
Sun 01:00

we also have to not touch any other app after we open the onlyT app. I am not sure what the issues are but they seem to be tied to JW Library compatibility. any help you can offer woulb be much appreciated.

thanks!

**Comment by AntonyCorbett** [comment]
@huah007 Thanks for your feedback. Try specifying all times in 24-hour clock mode.

Regarding JWL compatibility, please use JwlMediaWin to fix the issue:

https://github.com/AntonyCorbett/JwlMediaWin

Kind regards
Antony
