### ISSUE TITLE
Counseling Timers Display

### ISSUE THREAD

**Issue by jeffclaravall** [AntonyCorbett/OnlyT#290]
there was a feature in the soundbox program where during counsil, there's a bar thats 1 minute long, that goes down for the chairman, although i see it here that we can adjust how long the time is displayed for the chairman to see, i was wondering if there is an option to display the counseling time?

it can be the same like the one in soundbox, where there's a bar running down, or it can be a separate countdown timer for the chairman

**Comment by AntonyCorbett** [comment]
@jeffclaravall I suggest that you train the chairman to recognise that the student time is shown for a minute after which the display reverts to the clock and it's time for him to finish. I don't think I will add the SoundBox-style bar or a separate timer for the 1-minute slot.

Thanks for the feedback - it's much appreciated!

**Comment by AntonyCorbett** [comment]
@jeffclaravall  Please see the latest release, which now includes a "Show persist countdown bar" option that can be used with the "persist student time" option to display a countdown bar for the chairman during counsel.
