### ISSUE TITLE
Full Screen Mode on OnlyT Remote App

### ISSUE THREAD

**Issue by davenhery04** [AntonyCorbett/OnlyT#295]
Hi, I just want to ask if the timer in the remote app can turn to full screen mode? In our Kingdom Hall we used tablet for timer and we can't use the OnlyT app because there is full screen mode function.

Thank you.

**Comment by AntonyCorbett** [comment]
The iOS app has that feature but not the Android one. The web clock can also be used to provide a full screen display.
