### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by peabee21** [AntonyCorbett/OnlyT#297]
Would it be possible to add a reset button to the UI for multiple congregations using same log-in and desktop?  On a Sunday, when second congregation arrives, app has to be closed down and re-opened to reset the timings.  A reset button would be much simpler.
Thanks

**Comment by AntonyCorbett** [comment]
@peabee21 Thanks for your suggestion, The work-around is very straightforward so I'll leave the issue open in case others think it useful. I don't think it would be wise to place any Reset button on the main page and it may be less than straightforward if placed in Settings. We would also need to decide whether to allow reset after meeting timing has started, and if so, how to handle it. Further complications involve the meeting countdown timer which is currently only displayed once per application session, and the timer report which is similar. My feeling is that a reset function would complicate the design and introduce additional execution paths making testing more onerous.

**Comment by AntonyCorbett** [comment]
Closing in the absence of additional comments from other users. Thanks @peabee21 - appreciate your feedback.
