### ISSUE TITLE
Selective installation

### ISSUE THREAD

**Issue by bergerchemical** [AntonyCorbett/OnlyT#299]
What do you think? In the case of multiple accounts on one computer, would it be possible to allow separate installation and configuration for each account as well as the option of installing for the selected account? What do you think? Was this topic already touched?

**Comment by AntonyCorbett** [comment]
@bergerchemical thanks for your suggestion. Program options are per-user so can be different for each Windows user account. Is anything else required?

**Comment by bergerchemical** [comment]
No, that's enough for me. I had only small doubts but I did not really check whether different clock settings were implemented on different accounts. I'll check it soon because I'm curious how it works.
