### ISSUE TITLE
Web clock

### ISSUE THREAD

**Issue by AntonyCorbett** [AntonyCorbett/OnlyT#3]
As in SoundBox - support http server so that mobile devices on the same network can display the timer in a web browser

**Comment by hakerskipl** [comment]
This is very important functionality for our congregation and will be very useful on closest circuit assembly in the next two weeks. If you could give it priority, we will be very happy and thankful to you.

**Comment by Stevo984** [comment]
Please, what is the connection address?

**Comment by AntonyCorbett** [comment]
@Stevo984 There is no web clock functionality. This is as enhancement to be considered for later implementation.

**Comment by AntonyCorbett** [comment]
done
