### ISSUE TITLE
Timer Alert Message

### ISSUE THREAD

**Issue by donavan1** [AntonyCorbett/OnlyT#30]
Hi Antony 

I dont know if this is possible, I might as well try.

After the timer traffic light goes into the red state  can it also display a message "TIMES UP" ( a feature)and then continue counting down.
or
Just display TIME UP when it is the red state.

Thanks 
Donavan

**Comment by AntonyCorbett** [comment]
@donavan1 Hi Donavan. There are no traffic lights in OnlyT and none planned. Are you referring to a proposed feature in SoundBox?

**Comment by donavan1** [comment]
Hi Antony
My suggestion or idea !!!

The countdown time is as normal,
![image](https://user-images.githubusercontent.com/8216036/31596220-5a8e7d08-b241-11e7-9a04-614ad23f1966.png)

![image](https://user-images.githubusercontent.com/8216036/31596237-7090ab6c-b241-11e7-9d36-1b94a60bf2ad.png)

![image](https://user-images.githubusercontent.com/8216036/31596242-7d5e732e-b241-11e7-90c8-807a5b87e9a7.png)

But when it expire the time it should display this message or flash on the timer  screen.

![image](https://user-images.githubusercontent.com/8216036/31596261-9e65fb6e-b241-11e7-82ef-5309b76c8138.png)

and then revert back to 

![image](https://user-images.githubusercontent.com/8216036/31596274-adc9547a-b241-11e7-8aa3-5d96241b397e.png)

this can only be a preset option if one chose to enable this, else the normal countdown timer function is the same.

**Comment by AntonyCorbett** [comment]
Hi Donavan

I think it's unnecceasry. It assumes that the speaker will see the message for the few seconds that it appears. And if he _does_ see it, this means he's alert to the time anyway.

Thanks for your suggestion - all feedback is appreciated.

Kind regards
Antony

**Comment by TechMan88** [comment]
Hi Anthony, what about after the time expired it turn into.. Time up stays red and blinks every 5 secs until its deactivated? 

thxs for ur awesome work

Los Angeles

**Comment by AntonyCorbett** [comment]
@TechMan88 - thanks for suggestion. We have this discussion some time back and decided against anything that might be considered a little undignified :)
