### ISSUE TITLE
Add pause on OnlyR

### ISSUE THREAD

**Issue by marinosalvatore** [AntonyCorbett/OnlyT#303]
Would it be possible to add pause in the recordings, so as to be able to detach the recording of a part and then restart the recording without creating another audio file but creating a unique audio file?

**Comment by AntonyCorbett** [comment]
@marinosalvatore thanks for your request. Please would you describe a typical use-case? Thanks, Antony

**Comment by marinosalvatore** [comment]
Last night for example during the commemoration while I was recording, I had to avoid recording the prayers for the passage of the emblems.  Instead I had to record everything and then cut away the prayers with a wave editor.

**Comment by AntonyCorbett** [comment]
@marinosalvatore if it was necessary to remove prayers from meeting recordings then I would add a pause, but I don't want to complicate the application unless aboslutely necessary.

**Comment by scottys94** [comment]
I like the idea of adding a pause button. Perhaps there could be an option in OnlyR settings to enable or disable the pause button.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AntonyCorbett** [comment]
@scottys94 thanks. We need a compelling case for including new features (given OnlyR's intended application).

**Comment by marinosalvatore** [comment]
@antonycorbett Unfortunately the elders told me that it is a provision to avoid prayer records.  But as @scotty94 says it's not bad either to add it as an option in the settings.

**Comment by richfrantz** [comment]
There are too many prayers in the Bible for a reasonable person to say "you can't record prayers". And there is a KM on the subject.
________________________________

**Comment by LvDaniel** [comment]
@richfrantz I understand your point. Still, on stream.jw.org I don't see prayers to be recorded for regular meetings nor for assemblies/conventions.

**Comment by richfrantz** [comment]
Did you read the KM?

If you don't want to record prayers, start your recording after the opening prayer, and end your recording before the closing prayer.

It is a training issue, no different than a pause button would be a training issue. Mid-meeting prayers are rare, and not worth development effort.

Too many people mistake "volunteer" with "free". They are not the same. Anthony pays for this free software, with his "time". Is there a more precious resource?
________________________________

**Comment by LvDaniel** [comment]
@richfrantz that was just an observation. I'm not pro nor con for a pause option; ultimately this should be Antony's decision.

**Comment by richfrantz** [comment]
True, sorry if I started sounding like a rant. I see a lot of requests flow through here that leave me scratching my head is all that was.
________________________________

**Comment by marinosalvatore** [comment]
You are all right but as some of you said I start recording after prayer and end after the final song.  I needed to record the commemoration where there was prayer for the passage of the emblems, of course it is something that happens once a year but which is useful, then of course it is something that Antony will decide.

**Comment by LvDaniel** [comment]
No worries, I get your point. Indeed Antony's time is precious and I agree that requests raised should be for important things only.

**Comment by AntonyCorbett** [comment]
Closing after sufficient discussion. I don't intend to add a Pause function at this stage.
