### ISSUE TITLE
Timing Reports While Minimized

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#304]
My congregation controls the OnlyT timer with an iPhone. Therefore, we generally keep OnlyT minimized on the Sound System computer throughout the meeting. I have noticed that OnlyT does not generate a timing report until the application is restored. Is there any way for OnlyT to generate timing reports while minimized? There are times when the Sound operator will shut down the computer without restoring OnlyT. On those days, there are no timing reports generated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlainDema** [comment]
Purtroppo anche nella versione Windows non si creano i report dell'adunanza in nessun caso

**Comment by bergerchemical** [comment]
I do not know if this problem was already addressed so once again: is it possible to generate this report in any OnlyT settings? I mean automatic, manual and file mode. I apologize if I repeat the question but I could not find an answer

**Comment by AntonyCorbett** [comment]
@bergerchemical only for automatic mode (see the wiki entry for more details),
