### ISSUE TITLE
talk_schedule.xml

### ISSUE THREAD

**Issue by moisestjsilva** [AntonyCorbett/OnlyT#305]
Good morning my brother, my name is Moses and I'm from Brazil, I do not know if this is the right place to ask about it, but I have two questions.
The first is if by chance the brother would have an example file of the file "talk_schedule.xml" using the "section" command because I could not use this command.
The second is [REDACTED]

Note: @AntonyCorbett edited this to remove additional unrelated question

**Comment by AntonyCorbett** [comment]
@moisestjsilva There is a sample talk_schedule.xml file supplied with the product in the root of the installation folder. Please take a look and let us know if you need further help.

**Comment by moisestjsilva** [comment]
Ok, I saw this file, but I'm not able to increment the "secion" function -

Em sex, 10 de mai de 2019 às 08:50, Antony Corbett <notifications@github.com>
escreveu:

**Comment by AntonyCorbett** [comment]
The comments in the supplied file state:

"section" is an optional identifier referring to the section of the meeting in which the talk is scheduled. It's not used directly by OnlyT but remote control apps may use it

What are you trying to achieve?

**Comment by K0rTy** [comment]
Boa tarde, Moisés.
O que você está tentando fazer talvez eu possa ajudar?

**Comment by moisestjsilva** [comment]
Bom dia, tem duas coisas...uma delas é colocar neste arquivos as seções,
estou usando o programa para cronometrar o programa do congresso e
assembléia, quero separar os discursos da parte da manhã e parte da tarde
no arquivo e não estou conseguindo....

Se puder me passar o seu telefone para que eu possa te explicar melhor.


Em sex, 10 de mai de 2019 4:55 PM, Charllys Fernandes <
notifications@github.com> escreveu:

**Comment by K0rTy** [comment]
Fizemos isso no nosso congresso. Mas criamos um arquivo só com todos os tempos para o dia. 

Mas vou ver o que pode ser feito.

We did this in our congress.  But we created a file with all the time for the day.

 But I'll see what can be done.

**Comment by K0rTy** [comment]
Lembrando que o a aba Section é opcional não é usado no OnlyT apenas no aplicativo remoto.
Ou seja não vai mudar nada distribuir em seção, se você for operar pelo computador.

Eu acho mais pratico se fizer 4 arquivos todos com os tempos de cadas seção separadamente.
Depois configure a contagem regressiva para cada seção esse você pode adicionar no aplicativo mesmo sem problemas.

Ai basta fechar o aplicativo, mover talk_schedule.xml para a basta apropriada. Abrir o aplicativo e esperar o inicio da contagem regressiva.

Se não creio que se colocar a contagem regressiva para cada inicio de seção e adicionar o tempo do dia inteiro não vai dar problemas, desde que certifique-se de adicionar a hora certa.

Veja a descrição:

<! - "seção" é um identificador opcional referente à seção da reunião na qual a palestra é
   agendada. Não é usado diretamente pelo OnlyT, mas aplicativos de controle remoto podem usá-lo ->

**Comment by moisestjsilva** [comment]
Boa noite, foi exatamente isso que eu fiz, o  superintendente fica olhando
no aplicativo e com todas as partes fica um pouco complicado para
visualizar e por isso eu queria colocar separado por seção e talvez com
cores diferentes como acontece na reunião do meio de semana.
Agradeço muito a atenção dos irmãos.

Em sáb, 11 de mai de 2019 10:08 PM, Charllys Fernandes <
notifications@github.com> escreveu:

**Comment by K0rTy** [comment]
Entendi então você quer deixar mais fácil para visualização do Supt. certo?

**Comment by moisestjsilva** [comment]
Isso mesmo! :)

Em dom, 12 de mai de 2019 12:28 AM, Charllys Fernandes <
notifications@github.com> escreveu:

**Comment by K0rTy** [comment]
@AntonyCorbett 

how to use the identifier "Section" in a file talk_schedule.xml?
To have a result similar to a mid-week meeting in the remote application.

![image](https://user-images.githubusercontent.com/11689248/57585810-334e8100-74bb-11e9-8a39-1c9e89275bc2.png)

**Comment by moisestjsilva** [comment]
Send me the one of the image, with the XML file I can do the editing.

Em dom, 12 de mai de 2019 2:38 PM, Charllys Fernandes <
notifications@github.com> escreveu:

**Comment by AntonyCorbett** [comment]
@K0rTy 

> how to use the identifier "Section" in a file talk_schedule.xml? To have a result similar to a mid-week meeting in the remote application.

As explained in the wiki: 

> "section" is an optional identifier referring to the section of the meeting in which the talk is scheduled. It's not used directly by OnlyT but remote control apps may use it.

So the designer of the remote app may use the "section" value to differentiate between sections in some way (e.g. by providing a suitable header as is done with the regular meetings). However, AFAIK, the current remote apps ignore it. You could contact the developers of the remote apps to raise a feature request.

**Comment by K0rTy** [comment]
O da imagem é padrão não tem como editar. Creio que não é salvo em XML.

Como o @AntonyCorbett falou essa função que você quer vai ser feita pelo aplicativo remoto. É aplicativo remoto que lê section e separa. 

Vamos ver com o @iMatt acho que é ele o desenvolvedor do aplicativo remoto.

**Comment by K0rTy** [comment]
@moisestjsilva por esse site acho que voce consegue suporte do aplicativo remoto

https://gitlab.com/imatt/onlyt

**Comment by moisestjsilva** [comment]
Muito obrigado irei verificar.

Em qua, 15 de mai de 2019 10:46 AM, Charllys Fernandes <
notifications@github.com> escreveu:
