### ISSUE TITLE
Webclock has corrupted source code.

### ISSUE THREAD

**Issue by tomtailor1983** [AntonyCorbett/OnlyT#306]
**Describe the bug**
The webclock has corrupted source code.

**To Reproduce**
1. Go to webclock in any browser
2. See source-code
3. or press CRTL+A

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43112427/57581061-3a24c600-74b2-11e9-80cb-25d73934fba0.png)

![grafik](https://user-images.githubusercontent.com/43112427/57581063-46a91e80-74b2-11e9-8c8d-33c4166813cc.png)

**Comment by AntonyCorbett** [comment]
@tomtailor1983 thanks for finding this. I don't think it affects behaviour but I will clean it up it asap.

**Comment by tomtailor1983** [comment]
Thank you, Antony!

I find this because the weblock has with the "});" a left margin, so the webclock was not absolute centered and i am searching the reason therefore... i hope this was the reason... :) Thank you so much!
