### ISSUE TITLE
Webclock: Scaling by height

### ISSUE THREAD

**Issue by tomtailor1983** [AntonyCorbett/OnlyT#307]
I want to be able to adjust whether the webclock scales in width or height.

**Comment by AntonyCorbett** [comment]
The easiest way would be to create your own web page and use the OnlyT web API to get the timer / clock data as required.

**Comment by AntonyCorbett** [comment]
Or perhaps create your own web page and insert the OnlyT web clock in an iframe

**Comment by tomtailor1983** [comment]
Ok, first i will proof a workaround like a wrapper. Thank you.

**Comment by tomtailor1983** [comment]
Thank you.
