### ISSUE TITLE
Adjustment to time when color of clock changes from green to yellow

### ISSUE THREAD

**Issue by palvarado623** [AntonyCorbett/OnlyT#308]
Hello,
Is there a way to adjust when the color of the clock changes from green to yellow?  Currently it is at 30 seconds, but let's say some wanted it to be at one minute or 5 minutes for longer parts; would that be possible?

Thank you!

**Comment by AntonyCorbett** [comment]
@palvarado623 Thanks for your question. No, the 30-second period is fixed regardless of timer duration. There was some discussion about this but to make it customisable would require additional complexity in the user interface and provide little benefit (I felt). In fact, it may even introduce some confusion with speakers wondering why it appears to change colour arbitrarily.
