### ISSUE TITLE
Little problems with setting time in "Count up"

### ISSUE THREAD

**Issue by hakerskipl** [AntonyCorbett/OnlyT#31]
Today, we test OnlyT on circuit assembly. It works great, specially because you made yesterday "Count Up" function - and many brothers prefered this mode.

But we found a something to improve. First at all, change to "Count Up" mode only can be done by opening a Settings window. I think it would easier if this checkbox will be in main window.

Second improvment is a about enable to modify timer setting in enabled Count Up mode. Already, after activate "Count Up" mode, timer setting show 0:00 and can't be changed, but if before changing mode we set timer, then change to Count Up, then after start counting and reaching earlier set time, color change to red. So to change timer setting, we need to disable Count Up mode, set speech time, enable Count Up mode and start.

**Comment by AntonyCorbett** [comment]
@hakerskipl thanks for feedback. I understand both points

**Comment by AntonyCorbett** [comment]
@hakerskipl - I can't reproduce the problem you describe under "Second improvement". When "Count up" is enabled, I can easily change the target time and this is shown bottom left in the black timer panel. Please would you help me understand the issue?

**Comment by AntonyCorbett** [comment]
@hakerskipl - have added functionality to allow toggle of count up/down. Also see revised syntax in the talks_schedule.xml which now includes a "countup" attribute for each item.
