### ISSUE TITLE
timer lavagna come sala assemblea e messaggi oratore.

### ISSUE THREAD

**Issue by AlainDema** [AntonyCorbett/OnlyT#310]
Salve, sarebbe possibile avere solo per avvisare l'inizio dell'adunanza sulla "lavagna" del podio l'orologio analogico con i 5 minuti antecedenti come usato alla sala assemblee su sfondo nero?
Sarebbe anche utile poter inviare sul monitor del "timer" i messaggi per chi si trova sul podio.

**Comment by AntonyCorbett** [comment]
@AlainDema Regarding a speaker message function please see #39

**Comment by AntonyCorbett** [comment]
@AlainDema I'm sorry I don't understand the first of your 2 requests. Please would you try to explain again?

**Comment by TizianoNoto** [comment]
Ciao @AlainDema , la tua intenzione è di mostrarlo all'uditorio, giusto? Hai già provato la funzione "Timer inizio adunanza" presente nelle impostazioni selezionando l'uscita appropriata alla voce "Monitor"?

@AntonyCorbett The first request is to add an analogic timer for the meeting countdown, similar to the one shown before the start of a convention session (or at least this is what we do in Italy).

**Comment by TizianoNoto** [comment]
Aaand the countdown for this year's regional convention was digital. I thought about this conversation as soon as I saw it on the screens two weeks ago.

**Comment by AntonyCorbett** [comment]
Done
