### ISSUE TITLE
May 1903 release of windows 10

### ISSUE THREAD

**Issue by Silverfox171** [AntonyCorbett/OnlyT#311]
With the new May release of windows 10 1903 stops the only T and only M programs from working. When now opening the app it leaves the app as a blank window. Have tried to uninstall and re download but still the same results. Both only T and only M are now broke

**Comment by Silverfox171** [comment]
Also the new release has broken Only R And Only V

**Comment by AntonyCorbett** [comment]
@Silverfox171 Thanks for the feedback. The update may have changed your video driver. The symptom you describe is a common result of Windows reverting to a generic driver. Please investigate and let me know if you still have issues.

**Comment by Silverfox171** [comment]
Hi Antony 
Can say that reinstalled the windows update and has resolved the issue. As you said think it messed with my video drivers. But now all sorted. Thank you.
