### ISSUE TITLE
Automatically refresh the list of points after detecting the internet connection.

### ISSUE THREAD

**Issue by rafik73github** [AntonyCorbett/OnlyT#313]
Welcome. We use mobile internet. The OnlyT application starts with the system start. Unfortunately, before the internet connection is established, OnlyT is already running. Several times it happened that for this reason the list of points was out of date. It would be useful to automatically refresh the list of points after detecting an internet connection or an icon informing about an out of date list. Greetings.

**Comment by AntonyCorbett** [comment]
@rafik73github Thanks for your suggestion.

**Comment by ucphinni** [comment]
Can this refresh be done Saturday and Monday 12 midnight?

**Comment by rafik73github** [comment]
Maybe like that:

using System.Net.NetworkInformation;
 
bool isAvailable = NetworkInterface.GetIsNetworkAvailable();
 
MessageBox.Show(isAvailable.ToString());

**Comment by AntonyCorbett** [comment]
@rafik73github Added this to the new release. The timers list is updated when an internet connection is available

**Comment by rafik73github** [comment]
Welcome.
Thank you, brother, for adding this functionality. Wonderfull work. I'm
just working on a simple C # program that runs the JW Library and OnlyT
only when it detects an internet connection. It's called NeTTest and it's
posted on my GitHub account. These are my first steps, but this programming
language is really cool.
Best regards.

czw., 14 lis 2019 o 17:31 Antony Corbett <notifications@github.com>
napisał(a):
