### ISSUE TITLE
Meeting Countdown Issue

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#314]
Our Sound System computer has separate Windows accounts for each congregation. My congregation uses the meeting countdown included with OnlyT. I have noticed that if 2 or more Windows accounts are logged in at the same time, and if they both have OnlyT open, the meeting countdown doesn't work consistently. For example, at our last weekend meeting, the congregation before us forgot to log off. The countdown never appeared for our meeting. I attached the OnlyT log file for my congregation's account.
[log-20190615.txt](https://github.com/AntonyCorbett/OnlyT/files/3316413/log-20190615.txt)

**Comment by KenFrantz** [comment]
We used to have the same problem. It's just a matter of training. Force a reboot and reconnect. I created a shortcut and put it on all the account desktops. It does a restart and returns to the lock screen. While that is happening, my instructions say to simply turn off the monitor. The PC stays up for updates.

--Ken

Ken
C: (518) 947-4709

________________________________

**Comment by AntonyCorbett** [comment]
@scottys94 Thanks for the report. I can't reproduce the problem you describe and I have explicitly tested the scenario using 2 active Windows accounts. I'm a little confused by your congregation log which shows OnlyT launched at 12:47, 18:58, 19:01, 19:04 and 20:03. Is the same log used for all accounts (the default settings ensure that each account would have a separate log file)? If not, can you explain what was happening please?

**Comment by scottys94** [comment]
@AntonyCorbett Our meeting begins at 13:15, so we opened it at 12:47. The later times are when I was performing further testing (18:58 - 20:03). Each account has a separate log file for OnlyT. The countdown was supposed to start at 13:10, but it did not start at all for the meeting. I was able to re-produce the issue during my testing between 18:58 and 20:03 by having OnlyT open on 2 separate Windows accounts.

**Comment by AntonyCorbett** [comment]
@scottys94 Thanks. The log records the launching of the countdown window. Is it possible that another window (e.g. JWL media window) obscures it?

**Comment by scottys94** [comment]
@AntonyCorbett It’s possible. We are using JwlMediaWin, so I’m not sure if that’s a contributing factor. We did not have any issues with the countdown at our weekend meeting yesterday (06/22/2019), but this time I ensured that our congregation’s account was the only one logged in.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AntonyCorbett** [comment]
@scottys94 do you remember if the “Close Countdown” button was displayed?

**Comment by AntonyCorbett** [comment]
Closed pending a response
