### ISSUE TITLE
Visualize application more clearly than actively

### ISSUE THREAD

**Issue by tomtailor1983** [AntonyCorbett/OnlyT#318]
As a user of OnlyT, I want to see clearly that the application is active, because only then can start the countdown.

Possible solution: 
If the application is active, we will display the icon of OnlyT in the header green, otherwise red.

**Comment by AntonyCorbett** [comment]
@tomtailor1983 Hi. Can I suggest you use JwlMediaWin to fix this? You won't need to worry about OnlyT having focus.

**Comment by tomtailor1983** [comment]
Thank you, i will try it!
