### ISSUE TITLE
Timer Reports

### ISSUE THREAD

**Issue by jmccormic** [AntonyCorbett/OnlyT#320]
Is there a way to change the folder where the “Automatically Generate Reports” is saved to. I would like to have it saved to a file sharing service (Dropbox) so that they are accessible at any time.

**Comment by scottys94** [comment]
>Is there a way to change the folder where the “Automatically Generate Reports” is saved to. I would like to have it saved to a file sharing service (Dropbox) so that they are accessible at any time. 

@jmccormic This would be helpful for me as well.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timjobutler** [comment]
@jmccormic @scottys94 Using symbolic links, you point the OnlyT folder to Dropbox.

> Create a symbolic link to an individual file or folder, and that link will appear to be the same as the file or folder to Windows—even though it’s just a link pointing at the file or folder.

Try these links below for information on symbolic links and how to create them.
[https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/)
[https://www.techrepublic.com/article/how-to-take-advantage-of-symbolic-links-in-window-10/](https://www.techrepublic.com/article/how-to-take-advantage-of-symbolic-links-in-window-10/)
[https://www.maketecheasier.com/create-symbolic-links-windows10/](https://www.maketecheasier.com/create-symbolic-links-windows10/)

Hope these links are helpful.

Tim

**Comment by jmccormic** [comment]
Works great!! Thanks for the advice.

**Comment by scottys94** [comment]
Dropbox has recently blocked the use of Symbolic Links that Windows allows you to create. If you create a Symbolic Link and point it to a Dropbox folder, it will not sync to your Dropbox account. An alternative solution is to use a program like Allway Sync (free of charge). Once you install it, you can choose a Source and Destination folder. The Source would be the TimingReports folder in Documents > OnlyT, and the Destination can be a folder on Dropbox or wherever you'd like. You can go into the program's settings and schedule it to sync immediately when a file is added/changed. You can also configure the program to start in the system tray automatically when you log into Windows.

https://allwaysync.com/

**Comment by AntonyCorbett** [comment]
@scottys94 Thanks for the update. I may add a command-line option to change the reports folder.
