### ISSUE TITLE
Show message after countdown finishes

### ISSUE THREAD

**Issue by BenShelton** [AntonyCorbett/OnlyT#323]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a new option to show a message for around 15 seconds after the countdown finishes, so we can show a reminder such as “Please remember to put your mobiles/tablets on silent”. Text could be customisable to allow for other languages or other messages

**Describe alternatives you've considered**
Something along the lines of #252 

**Additional context**
The chairman shouldn’t have to say these reminders at the start of every meeting and it would be a gentle reminder (because we all forget now and then) as well as an indication for interested ones visiting for the first time

**Comment by AntonyCorbett** [comment]
@BenShelton Thanks for your suggestion. I'm spending some time on OnlyT maintenance and reviewing FRs. This one seems useful but I wonder about the effectiveness of a message that is displayed unchanged for weeks; perhaps the tendency is for it to be ignored. There's also a strong possibility that TV content will eventually be prescribed by the branch. For these reasons I'm reluctant to spend dev time on the FR and will close it for the time being. Thanks for your feedback. Kind regards, Antony
