### ISSUE TITLE
Problem with the countdown

### ISSUE THREAD

**Issue by marinosalvatore** [AntonyCorbett/OnlyT#327]
There is a problem with the countdown, as soon as it closes and closes the window the screen remains black and does not let me see the jw library screen, because it remains in the background, the same problem occurs when the countdown starts if  jw library is selected the count is not seen if I select onlyT you see. 
I also tried to select jw library at the end of the countdown but it crashes jw and I have to restart it.

**Comment by AntonyCorbett** [comment]
@marinosalvatore Use JwMediaWin to fix the JWL window.

https://github.com/AntonyCorbett/JwlMediaWin
