### ISSUE TITLE
Lock output monitor

### ISSUE THREAD

**Issue by chevybowtie** [AntonyCorbett/OnlyT#329]
Our setup: dedicated small PC to one monitor only

From our sound booth, you cannot see the countdown/timer monitor on our back wall. As a result, it's impossible to change settings or anything on that PC since you cannot see it (that's a good thing!) So when it's time to ensure it's up to date (Windows or this app), we remote into it (RDP or Teamviewer).  When you do so, you usually bork the monitor settings: settings page > "Monitor" lists won't contain our monitor when using it remotely.

Any chance we could "lock" the output to a specific monitor so that on reboot, it always chooses that one, especially since that's all this PC does and this app starts automatically. Maybe through the use of a config "preferred monitor" file that it would try first. If that file or the monitor referenced within it is not present, the the current logic of just showing the dialog would be the launch action.

Thanks for your consideration.

**Comment by AntonyCorbett** [comment]
@chevybowtie The best solution is probably to add a command-line option to specify a monitor to override that stored in settings. Theer should be 2 options - one for timer monitor; another for the mtg countdown monitor.

**Comment by chevybowtie** [comment]
That would work just fine for us. Thank you.

One question: After a reboot and/or app restart, will it automatically update the schedule mode: midweek vs weekend based on the date?

**Comment by AntonyCorbett** [comment]
@chevybowtie yes, the automatic mode selects the correct midweek or weekend schedule depending on the date of launch.

**Comment by AntonyCorbett** [comment]
@chevybowtie Command-line options are now implemented in latest pre-release (see Wiki for more information)

**Comment by chevybowtie** [comment]
Thank you, sir!

...and in case anyone else is doing the same, we just schedule a reboot on the PC every morning @ 5AM so that the app, on startup, selects the proper schedule.
