### ISSUE TITLE
Port not opening up on firewall

### ISSUE THREAD

**Issue by omaha4** [AntonyCorbett/OnlyT#33]
On both the desktop at our Hall and on my personal Surface Book, the firewall helper in the app was not opening a port. I had to manually create a new rule to open the port. After the port was set to listen, in order to access the web clock, I have to use this format: "http://192.168.XXX.XXX:XXXX/index"

**Comment by AntonyCorbett** [comment]
@omaha4 - Hi. Thanks. The fireall helper simply reserves the port. It doesn't attempt to open in the firewall. Thanks for feedback.
