### ISSUE TITLE
Speaker video monitors 

### ISSUE THREAD

**Issue by SteveLevitt7** [AntonyCorbett/OnlyT#330]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SteveLevitt7** [comment]
We have a screen facing the speaker that displays the countdown clock, but wondered if it was Possible that when a video is showing it can be played on the countdown monitor, and when the video finishes it goes back to countdown. 
Also is it possible to display the words for the songs. 
At the moment the speaker is having to turn his back to the audience to look at the main screen.

**Comment by AntonyCorbett** [comment]
@SteveLevitt7 please see #234
