### ISSUE TITLE
Count Up toggle doesn't work on Manual mode

### ISSUE THREAD

**Issue by hakerskipl** [AntonyCorbett/OnlyT#34]
Today I tested OnlyT v.1.0.0.32. And toggle CountUp works fine on Automatic mode, but on Manual it doesn't. And on manual mode, with active Count Up mode I can't to change target time.

Please look: https://youtu.be/lx1iJldPeas

**Comment by AntonyCorbett** [comment]
@hakerskipl Thanks!

**Comment by AntonyCorbett** [comment]
@hakerskipl Fixed. Thanks for your help.
