### ISSUE TITLE
Unblock resizing in OnlyT

### ISSUE THREAD

**Issue by hoczykm** [AntonyCorbett/OnlyT#344]
Hello. There are some tools like e.g. [Dell Display Manager ](https://www.dell.com/support/article/pl/pl/pldhs1/qna44541/what-is-dell-display-manager?lang=en) which can help to arrange nicely multiple applications on monitors. However you can't resize OnlyT so it can't be adjusted by programs like these. Would you mind to allow resizing?
![Picture](https://user-images.githubusercontent.com/41285621/66808364-5e864200-ef2b-11e9-8704-204f935556e7.jpg)

PS: The same thing is about OnlyR.

**Comment by AntonyCorbett** [comment]
@hoczykm Presumably you'd like to see the elements of the window resize accordingly (rather than the extra space being simply empty)?

**Comment by LvDaniel** [comment]
@AntonyCorbett @hoczykm this is a feature I would appreciate it also. Having all the elements resized will make OnlyT more visible on the screen and potentially help the operator to start/stop the timer on time.

**Comment by hoczykm** [comment]
> @hoczykm Presumably you'd like to see the elements of the window resize accordingly (rather than the extra space being simply empty)?

Exactly. Dell Display Manager takes care to adjust all my windows to my predefined matrix (see that yellow frames) but it doesn't work for applications where resizing is blocked.

**Comment by AntonyCorbett** [comment]
@hoczykm @LvDaniel Please see latest pre-release. Aspect ratio of controls is maintained as windows size adjusted.

**Comment by LvDaniel** [comment]
@AntonyCorbett thank you very much. It's a very nice and useful feature.
