### ISSUE TITLE
Multiple Custom Timers 

### ISSUE THREAD

**Issue by MDS201** [AntonyCorbett/OnlyT#346]
Is it possible to have adjustable custom timers that can be used for other theocratic meetings that may be held outside the midweek and weekend meetings? 

This could be used for occasions such as memorial talks, special meetings or circuit assembly programs.

A similar thing was used on Soundbox 3.1 (Shown in the image below).

![Custom Timers](https://user-images.githubusercontent.com/46344352/67383746-b6eebc80-f587-11e9-9eb9-1701b64f1c1e.jpg)

**Comment by AntonyCorbett** [comment]
@MDS201 Thanks for the question. Please use the "File-Based" mode to configure special timer lists. See the wiki for more information. 

Kind regards
Antony
