### ISSUE TITLE
Timing in the Part Apply yourself in ministry

### ISSUE THREAD

**Issue by JohnnyBoy11** [AntonyCorbett/OnlyT#347]
Please add a timing in ministry part and please to update timing minutes

**Comment by AntonyCorbett** [comment]
@JohnnyBoy11 Please would you explain in more detail? Thanks, Antony

**Comment by JohnnyBoy11** [comment]
I would like to know if the Only T has the same function with Soundbox
timer. Because the soundbox has a timer for the student and the Only T
doesn't have one. I only have one request to do it also in the Only T.
Thank you

**Comment by AntonyCorbett** [comment]
@JohnnyBoy11 yes, OnlyT has the same functionality as the SoundBox 3.1 timer. Please see the wiki for more information.

**Comment by JohnnyBoy11** [comment]
I would like to ask a question. If you will going to update the Only T in
January 6?

**Comment by yjenb** [comment]
Hey @JohnnyBoy11 

please see the Update 1.2.0.16 from yesterday: https://github.com/AntonyCorbett/OnlyT/releases/tag/1.2.0.16

Many regards,
Benjy

**Comment by JohnnyBoy11** [comment]
I would like to create file based talk for our upcoming assembly, can you
help me with that?

**Comment by AntonyCorbett** [comment]
@JohnnyBoy11 Sorry for the late response. Please see the Wiki for instructions on using the "File-based" mode. If you need further help, then please create a separate issue.
