### ISSUE TITLE
Reducing clock's seconds size

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#348]
If it's not much trouble, is it possible to add an option to reduce the size of the seconds from the digital clock? We're having a 15" display for the timer and the distance from the stage to the AV desk (where the timer is located) is almost 14 meters. So reducing the seconds size will allow the hour and minutes to be a bit larger and more visible.
Something similar with this:
![15728730815786899452742325809490](https://user-images.githubusercontent.com/45002147/68131548-eb6a5d00-ff25-11e9-8f74-37f4dec056c9.jpg)
Thanks.

**Comment by AntonyCorbett** [comment]
@LvDaniel Have you tried turning off the seconds?

**Comment by LvDaniel** [comment]
@AntonyCorbett yes, we considered this, but we kinda want to keep the seconds also. If it's too complicated, please disregard this request. Thank you

**Comment by AntonyCorbett** [comment]
@LvDaniel Just wanted to check you'd tried it :)

**Comment by AntonyCorbett** [comment]
@LvDaniel please see latest release

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks, looks very nice
