### ISSUE TITLE
Weekdays/Weekend meeting setting Feature Request

### ISSUE THREAD

**Issue by Kulotski66** [AntonyCorbett/OnlyT#353]
Good Day,

First of all really appreciate all your hard work on making all this excellent applications.

On our region the weekend are Friday and Saturday and Weekdays are from Sunday to Thursday, can we have a setting that the weekend are in this days and weekdays are this. usually when we start the OnlyT app we missed to check the "Meeting Mode" and suddenly we will notice that we are in the wrong day setting and using a different day of the week

Additional feature request is a total running time of the meeting that enables the chairman to know if we are exceeding or need to extend the meeting.

Thanks and Best regards

**Comment by AntonyCorbett** [comment]
@Kulotski66 Thanks for your feedback. There is another factor. The branch publishes meeting agendas based on a week that starts Monday and ends Sunday, and it's assumed that both meetings assigned for that week are actually scheduled during that week. Is that still the case in your region? As an example, consider the 2 meetings for the week "Nov 18-24" - on what dates were those meeting agendas typically delivered in your region?

**Comment by Kulotski66** [comment]
> @Kulotski66 Thanks for your feedback. There is another factor. The branch publishes meeting agendas based on a week that starts Monday and ends Sunday, and it's assumed that both meetings assigned for that week are actually scheduled during that week. Is that still the case in your region? As an example, consider the 2 meetings for the week "Nov 18-24" - on what dates were those meeting agendas typically delivered in your region?

Thanks for the fast response, here on our region the week starts on a Sunday and ends on a Saturday "Nov 17-23" so our Weekend meeting (PT & Watchtower) is on Friday and Midweek meeting is on Wednesday. 

Thanks & Regards

**Comment by AntonyCorbett** [comment]
@Kulotski66 thanks. Just to confirm, do the 2 meetings in that week use the agendas for the week "Nov 18-24"?

Please create separate issues for each feature request / bug report.

**Comment by Kulotski66** [comment]
> @Kulotski66 thanks. Just to confirm, do the 2 meetings in that week use the agendas for the week "Nov 18-24"?
> 
> Please create separate issues for each feature request / bug report.

 @AntonyCorbett Thank you. Yes the 2 metting will be on weeks Nov 18-24, Our weekend in our region is Friday & Saturday and Weekdays is Sunday to Thursday.
Weekend Meeting (PT & Watchtower) is Friday
Midweek Meetinf (Life & Ministry &CLM) is Wednesday
It fall all in a Midweek setting of the OnlyT.

Thanks and Best Regards

**Comment by bergerchemical** [comment]
In this case, you may consider switching from automatic to "from file" and thus customizing the meeting plan. By the way, @AntonyCorbett , what do you think about the possibility of choosing a file with the right plan in such a case?

**Comment by AntonyCorbett** [comment]
> what do you think about the possibility of choosing a file with the right plan in such a case?

@bergerchemical - that's a possibility but it would involve adjusting the item times manually. I think it should be possible to have an option to treat weekends as Fri-Sat. The only question (which I was trying to get to the bottom of) is this: what meeting agenda do we use if OnlyT is opened on a Sunday? It is locally considered to be "midweek" and the start of the week, yet the date corresponds to the end of the previous week in the official schedule. For example, take the jw week Mon 18th - Sun 24th Nov. Suppose we allow users to specify a "Fri/Sat" weekend so that their week runs from Sun 17th - Sat 23rd Nov. If we open OnlyT on Sun 17th which midweek agenda do we use?

**Comment by bergerchemical** [comment]
@AntonyCorbett  it seems that the best solution in this case is to roll back the calendar one day back. That is: normally the week from Mon to Fri 23 - 27 Nov and weekend 28 - 29 for @Kulotski66 will last from 22 - 26 Nov and the weekend 27 - 28. By moving the meter back one day you are still discussing the current program

**Comment by AntonyCorbett** [comment]
@bergerchemical Thanks. Using your dates (which are different from those in the previous example), and assuming we choose the "alternative weekend" option, what does @Kulotski66 see when he opens OnlyT on Sunday 22? It's midweek for him, but does he see the midweek agenda for w/c 16th or w/c 23rd?

**Comment by AntonyCorbett** [comment]
Implemented in latest release. My chosen solution is a simple flag to indicate whether Friday should also be treated as the "weekend"

**Comment by Kulotski66** [comment]
I would like to express my sincere and overwelming joy on your solution to overcome this scenario. Thank you and best regards to you, your team and to the Family.

**Comment by Kulotski66** [comment]
Thank you very much for all your effort in adding this new feature we really appreciate it. 

From our congregation we send our Love to you, your team and to your family.
