### ISSUE TITLE
Display Talk Timer

### ISSUE THREAD

**Issue by kcwizard** [AntonyCorbett/OnlyT#36]
Please display the CURRENT talk time after STOP has been pressed.  The Chairman can then view talk length during counsel.  START with next talk starts next countdown.  i.e. SOUNDBOX displayed the time until the next timed part was started.  Of course they listed the individual parts separately and that made it easier for them to do as I have suggested for ONLY-T.  

Regardless, you have done a great job all-in-all.

**Comment by gbog2000** [comment]
This is my question as well.
Is this something that might be tackled in the near future?

**Comment by gbog2000** [comment]
Hi Antony..  I'm just following up on this ticket.  The more we use the timer for the students and their talks, the more i'm seeing that its not worth using during them.  As soon as the stop is pushed, it just goes back to the time and the chairman sees nothing.  I know you are major busy doing other things but is there a way to at least add a pause button so the chairman can at least see the timing of the talk?  Thanks again for all your hard work.
Greg

**Comment by AntonyCorbett** [comment]
@kcwizard @gbog2000 Please try the latest pre-release. Final timer values for student talks remain on screen until a new timer is started,

https://github.com/AntonyCorbett/OnlyT/releases/tag/1.1.0.3

**Comment by kcwizard** [comment]
Thanks Antony.  I’ll test this week .

 

 

_____________________________________________________

 

John S. Wood

   Phone: (816) 741-8116

   Fax: (816) 841-4899

johnwood@ambercomputer.com <mailto:johnwood@ambercomputer.com>

**Comment by gbog2000** [comment]
works great!  Thank you for being so prompt!

**Comment by ricardoantonio** [comment]
Works fine!!
I have a suggestion. Remain the time on screen until a new timer is started may confuse the next student. Could you add the way reset the time once the chairman has seen it?
