### ISSUE TITLE
Creating file based how?

### ISSUE THREAD

**Issue by JohnnyBoy11** [AntonyCorbett/OnlyT#362]
How to create a file based timing ? Can you teach me how?

**Comment by AntonyCorbett** [comment]
@JohnnyBoy11 Yes. From the wiki: "In File-based mode you can specify an xml file named "talk_schedule.xml" containing the meeting items and store it in your "Documents\OnlyT" folder. A sample xml file is contained in the root of the OnlyT installation folder; you should modify it to suit your needs and copy it to your "Documents\OnlyT" folder. File-based mode is for advanced users."

What have you tried?

**Comment by nitro2010** [comment]
I know that some time elapsed from issue.

1. Go to Documents -> OnlyT
2. In this folder you have talk_schedule.xml, you can edit it, it has comments, so modify is easy
3. save
4. run OnlyT, go to program settings
5. In 'General' on 'Mode' Choose 'File'
6. Tadam, is ready!



PS.
I attach my talk_schedule.xml useful for conference (unzip it)
[talk_schedule.zip](https://github.com/AntonyCorbett/OnlyT/files/4021429/talk_schedule.zip)
![image](https://user-images.githubusercontent.com/950663/71758161-aff3fc80-2e9c-11ea-8933-9fcce94fffb4.png)
