### ISSUE TITLE
Fail to working with JWL

### ISSUE THREAD

**Issue by marek-dziechciarz** [AntonyCorbett/OnlyT#365]
**Describe the bug**
There's a problem with countdown to cooperate with JWL.

**To Reproduce**
Set countdown to media screen e.g. 5 min before.
Run JWL e.g. play music.
Wait for countdown to run.
Countdown ends.
Run video on JWL.
JWL can't display media on media monitor/(crash) restart needed, even when "working with JWL enabled"

**Expected behavior**
Proper work

**Screenshots**
...

**Desktop (please complete the following information):**
 - Windows 10 - actual
 - Notebook Dell + 1 external screen

**Comment by bergerchemical** [comment]
Hi marek, I'll try to do it on our equipment, although we use three displays instead of two. But I'll see if you can "ruin": D if you are from Poland, we can talk about it in Polish - it will be easier

**Comment by AntonyCorbett** [comment]
@marek-dziechciarz are you using JwlMediaWin?

https://github.com/AntonyCorbett/JwlMediaWin

**Comment by marek-dziechciarz** [comment]
Cześć
Tak jestem z Polski.
Nie widziałem o dodatkowej aplikacji z fixem, sprawdzę ją.
Największy problem jaki zauważyliśmy to przy onlyT z wyświetlaniem
odliczania przed zebraniem.
Bo tutaj trzeba od razu po zakończeniu zegara mieć gotowe JWL do pieśni.
I mieliśmy już 3 razy problem:
2 razy zginęło okno z wideo z JWL
1 raz zegar wyświetlił się pod JWL i nie było go widać.

sob., 7 gru 2019, 23:22 użytkownik Grzegorz <notifications@github.com>
napisał:

**Comment by marek-dziechciarz** [comment]
Sprawdzę go, bo nie wiedziałem że jest coś takiego

niedz., 8 gru 2019, 08:51 użytkownik Antony Corbett <
notifications@github.com> napisał:

**Comment by AntonyCorbett** [comment]
@marek-dziechciarz I suggest the following:

1. Install JwlMediaWin
2. Make sure your video driver is up to date

Please let us know what happens.

Kind regards
Antony

**Comment by bergerchemical** [comment]
@marek-dziechciarz Poczytaj wiki do JMW w sekcji "Operation". My nie stosujemy tego rozwiązania - karta zawsze prawidłowo identyfikuje wyświetlacze (używamy trzech - 1. projektor, 2, kontrola czasu, 3. komp stacjonarny. Kiedyś pojawił się problem z identyfikacją monitorów ale przyczyną było rozjechanie się zadanej rozdzielczości w sekcji ustawień ekranu win10. Po ustawieniu rozdzielczości natywnej dla urządzeń wszystko wróciło do normy. Teraz jestem na budowie do soboty ale jak wrócę poeksperymentuję na naszym sprzęcie. Pozdrawiam

**Comment by AntonyCorbett** [comment]
Closing. Please reopen if needed.
