### ISSUE TITLE
Countdown timer for start of the meeting

### ISSUE THREAD

**Issue by PhilTrickH** [AntonyCorbett/OnlyT#370]
We only use the program currently for the countdown timer for the start of the meeting.
Is it possible to set the midweek and weekend meeting start times and then just have a start countdown button which automatically works out how long is left to the start time? 
At the moment we have to manual set the timer based on how long is left before the meeting start. i.e. Meeting at 7:15, set the timer to 10mins then wait until 7:05 to start manual start the timer.

**Comment by AntonyCorbett** [comment]
@PhilTrickH yes. Please see the wiki for full details.
