### ISSUE TITLE
Counsel Timer

### ISSUE THREAD

**Issue by ardenee** [AntonyCorbett/OnlyT#375]
Would it be possible to add an option (check box item in program options) to add an additional timer after each item that has counsel to help avoid the counsel going over time, say 1 minute for counsel but only for items that receive counsel (not videos etc..).

I've looked at the file-based timer settings, but this would require manually editing and verification each week.

Currently we could select the very first item in the timer items (1 min – Opening Comments) right after the item and use this, but this may confuse the timer reports or the operator and gives way to additional mistakes.

If it could be automatically added to the automatic timer function via a checkbox in the options as maybe not all would like it, or it could cause confusion.

**Comment by Benhereg4a** [comment]
This is the issue we are running into. Also we would like the ability to view the videos with the timer still running in the background.

**Comment by josslamberti** [comment]
@AntonyCorbett I've been asked about timing the counselling again last week. Adding it to the automatic schedule seems easy enough from here. Those who don't want to use it can always skip it if they want.

**Comment by Benhereg4a** [comment]
I agree. It would really help because sometimes the chairman doesn’t know exactly where he is in time. It’s not always easy to manage time, counsel, your comments, and keep the meeting flow correct. This would truly be a tremendous help.

**Comment by AntonyCorbett** [comment]
> Also we would like the ability to view the videos with the timer still running in the background.

Please see existing issues.

**Comment by AntonyCorbett** [comment]
> I agree. It would really help because sometimes the chairman doesn’t know exactly where he is in time. It’s not always easy to manage time, counsel, your comments, and keep the meeting flow correct. This would truly be a tremendous help.

How does the current arrangement not work? See Timer window => Persist talk duration

**Comment by Benhereg4a** [comment]
Your right. I went back to review instructions. The chairman are instructed to be very brief between each part. That’s all we have.

**Comment by Benhereg4a** [comment]
The issue was I thought the chairman had a set time to comment or introduce the next part. I was wrong.

**Comment by Benhereg4a** [comment]
It does say One minutes between student assignments. That’s what we were talking about originally.

**Comment by josslamberti** [comment]
> > I agree. It would really help because sometimes the chairman doesn’t know exactly where he is in time. It’s not always easy to manage time, counsel, your comments, and keep the meeting flow correct. This would truly be a tremendous help.
> 
> How does the current arrangement not work? See Timer window => Persist talk duration

Fair enough, I'll check this feature again.

**Comment by AntonyCorbett** [comment]
> It does say “One minute” between student assignments. That’s what we were talking about originally. If you could add that “one minute” so brothers don’t keep talking.

OnlyT deals with this automatically. Whenever counsel is to be offered, after the student timer is stopped, the display shows how long the student talk took. This static display remains on-screen for a little over 1 minute (or however long you specify in the settings) so that the chairman can refer to it if needed. When the minute is up, the timer display reverts to the standard clock - giving the chairman notice that his 1 minute is up. It's simply a matter of training the chairman to understand these cues.

**Comment by Benhereg4a** [comment]
Well thanks for the heads up. I’m chairman next week. I’ll pay close attention to it. Thank you.

**Comment by AntonyCorbett** [comment]
Closing for now - OnlyT allows the counsellor to keep a check on his one minute allowance.

**Comment by moguerri85** [comment]
there is a bug! this feature works only if there is an analog clock.
if you hide the analog clock via the split-screen, this functionality is not visible.

**Comment by moguerri85** [comment]
> > It does say “One minute” between student assignments. That’s what we were talking about originally. If you could add that “one minute” so brothers don’t keep talking.
> 
> OnlyT deals with this automatically. Whenever counsel is to be offered, after the student timer is stopped, the display shows how long the student talk took. This static display remains on-screen for a little over 1 minute (or however long you specify in the settings) so that the chairman can refer to it if needed. When the minute is up, the timer display reverts to the standard clock - giving the chairman notice that his 1 minute is up. It's simply a matter of training the chairman to understand these cues.

there is a bug! this feature works only if there is an analog clock.
if you hide the analog clock via the split-screen, this functionality is not visible.

**Comment by AntonyCorbett** [comment]
Please see the latest release, which now includes a "Show persist countdown bar" option that can be used with the "persist student time" option to display a countdown bar for the chairman during counsel.
