### ISSUE TITLE
Edit text size for timer display and countdown

### ISSUE THREAD

**Issue by Cal0209** [AntonyCorbett/OnlyT#377]
Would it be possibly to add a setting to allow changing the size of the font for the digital timer and countdown? Our timer display is at the back of the hall and despite the screen being quite large, some brothers struggle to see it.

**Comment by AntonyCorbett** [comment]
@Cal0209 The digital timer can be made full screen (i.e. as large as it will go). See wiki for options. Please send more detailed info if I have misundertood.
