### ISSUE TITLE
Monitor identity reversed for OnlyT

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#379]
Yesterday on our KH PC has been installed automatically 1909 Windows update. After completed (took couple of hours) we noticed that OnlyT and OnlyM monitors were not selected which is the normal behavior after an major Windows update.
I'm thinking to specify the monitors from the command line to prevent this kind of issues in the future, but I've decided to test this options on my home PC first. 
On the Wiki it's said that "the value specified must be a number and should correspond to the location of the monitor as it appears in the list of monitors (see Settings page)". I believe this refers to the "Setting > Display" where I can see the identity numbers for each monitor.
On my setup #1 is the main monitor and #2 is the second monitor (used for JWL media, countdown  and testing the timer). But if I use "/monitor=2" I get the timer on the primary monitor. If I use "/monitor=1" timer is displayed correctly on the 2nd screen.
I've had a look through "Intel's Graphic Control Panel" and monitor identity is similar with the one from "Settings > Display".
It's a bit weird that I need to revers the numbers in OnlyT command line to make it work... and to be honest I'm not quite confident to do it.
I'm wondering, will an update affect the identity numbers and mix the displays? Or make it right from OnlyT perspective and affect the settings? This can be worst as you can't change the monitors from OnlyT settings once you specify them through command line.
Please let me know your thoughts on this. Thank you

**Comment by AntonyCorbett** [comment]
@LvDaniel I have made some changes in the latest pre-release and would be grateful if you have chance to check again.

**Comment by LvDaniel** [comment]
Thanks Anthony, I will as soon as I'll be able to. This happened only on the KH PC and now due to the restrictions I cannot do it. Once restrictions will be raised I'll do it. Looking forward for that moment.

**Comment by AntonyCorbett** [comment]
@LvDaniel Closing for now, but please reopen if needed.

**Comment by LvDaniel** [comment]
@AntonyCorbett sorry, but I didn't had the chance to test this at the KH due to pandemic. I'll post here if I'll see the same behavior. Thank you!
