### ISSUE TITLE
Clock on Computer Destop

### ISSUE THREAD

**Issue by DMKSR** [AntonyCorbett/OnlyT#382]
Hello :-) When launching OnlyT, a clock opens on the computer monitor displaying the current time, on the entire desktop. I’ve tried a few things but so far I am unable to minimize it, or adjust the size. To remove it, I have to sign off or restart the computer. Any help would be appreciated. Thanks.

**Comment by AntonyCorbett** [comment]
This means that the timer monitor is set to the main display. Use Alt-tab to activate the OnlyT main window, go to settings and change the timer monitor.
