### ISSUE TITLE
Playing JWL music during countdown

### ISSUE THREAD

**Issue by marek-dziechciarz** [AntonyCorbett/OnlyT#389]
**Describe the bug**
During countdown JWL hangs and do not switch to another song.

**To Reproduce**

1. set meeting time to start in about 1 hour - set countdown display to JWL media screen (same)
2. Run JWL
3. Run Media/Audio Play meeting songs (random)
4. Run onlyT - Countdown starts
5. JWL will stop after currently played song will end, and not play next.

**Expected behavior**
Countdown shouldn't stop

**Desktop (please complete the following information):**
 - Windows 10

**Comment by AntonyCorbett** [comment]
What version of OnlyT please? And do you use JwlMediaWin?

https://github.com/AntonyCorbett/JwlMediaWin

**Comment by AntonyCorbett** [comment]
@marek-dziechciarz closing for now as no reponse. But please reopen if you have a reproducible case
