### ISSUE TITLE
Transparent background for timer

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#390]
Hi Anthony, I know that we have an option for transparent background for the countdown meeting timer. I was wandering if it's possible to have this option for the main timer as well.
Using OBS (during Zoom meetings) we would like to display the timer on the bottom right corner over JWL Media window while we're displaying images (and spotlight in Zoom that view). In this way the presenter will see for sure the time left for his part.
Thank you for all your efforts.

**Comment by AntonyCorbett** [comment]
@LvDaniel Use the latest pre-release which has an option to display the timer in a window.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks, I already use that version.
I just wanted to have a more friendly display over images and eliminate the black portion.
Only if it's possible and if it's easy to implement.

![image](https://user-images.githubusercontent.com/45002147/77757670-54b84d00-703a-11ea-8324-628500910b13.png)

**Comment by AntonyCorbett** [comment]
@LvDaniel There is a technical issue that I haven't been able to overcome yet. I can create a transparent window but OBS doesn't recognise it! I haven't investighated at length yet.

**Comment by LvDaniel** [comment]
@AntonyCorbett Thanks. In this case, doesn't worth the effort to investigate more. 
I know that these days are very busy, almost all of us working from home and supporting the videoconferences... I can imagine that your day with all of this and supporting OnlyX as well.
Thanks again and I can't find words to express my appreciation for all your help. I'm absolutely convinced that Jehovah won't forget your efforts.

**Comment by LvDaniel** [comment]
@AntonyCorbett I found something... 
In OBS you can put a Filter for a source and add a Color Key effect with Opacity.
So if we have a shadow (different than the background color) will look really nice.
Doesn't look bad as it is either...

![image](https://user-images.githubusercontent.com/45002147/77762105-add7af00-7041-11ea-8f6b-c3a16fbfc0d3.png)

**Comment by AntonyCorbett** [comment]
Closing now. Please reopen if needed.
