### ISSUE TITLE
Countdown frame small size

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#394]
I don't know if this is easy to implement, but wold be nice to have the frame size of the countdown meeting timer smaller. 
Since we have the meetings through Zoom I usually play some video songs with 5 min or so before the meeting starts and also I'm displaying the countdown for everybody to be prepared and ready when the meeting starts. The frame takes a lot of space currently and I've tried to use the transparent background but the timer is not so visible, especially when the background is bright.

Current frame
![image](https://user-images.githubusercontent.com/45002147/79031130-6acf1d00-7ba5-11ea-9461-74a9c4547895.png)

Small frame
![image](https://user-images.githubusercontent.com/45002147/79031153-8f2af980-7ba5-11ea-86e7-d184ab52f0d5.png)

**Comment by AntonyCorbett** [comment]
@LvDaniel I've done a little work on this in the latest prerelease but probably not enough.

**Comment by LvDaniel** [comment]
@AntonyCorbett Thank you, looks nice.
I believe that the perfect case will be to have a shadow (black) on the countdown numbers to be able to use it without frame and have a good visibility, but probably this is not so simple to implement and doesn't worth the effort (I know your time is limited).
As the frame is smaller now, it looks much better.
Thank you for all your efforts!

**Comment by LvDaniel** [comment]
@AntonyCorbett is it possible to reduce more the frame size, maybe in a future release? Thank you!

**Comment by LvDaniel** [comment]
I'm using the countdown on every congregation meeting hosted in Zoom, so if some adjustments can me made in a future release will be much appreciated.
Thanks again Antony!
