### ISSUE TITLE
Last release 1.3.0.4 - bug

### ISSUE THREAD

**Issue by AlexSanti** [AntonyCorbett/OnlyT#406]
Thank you very much for the good work.

After updating with the latest version, I started to have some problems.

1) - According to the attached image, this Thursday's meeting, the program did not update the time for each designation of "APPLY YOURSELF TO THE FIELD MINISTRY". By adapting the time count, the program did not make the final report.
![OnlyT](https://user-images.githubusercontent.com/62076449/85178436-63e41b00-b276-11ea-9fc0-98e4835416c3.jpg)

2) - As you can see in the short video I made, the program after completing the assignment "TREASURES FROM GOD’S WORD", immediately changes the count to the first designation of   "Opening Comments". So it always remains in each designation to change to "Opening Comments".

The video can be viewed at https://drive.google.com/file/d/1djO_Y6yzKIqbgXsnRLsK793M2CG760b_/view?usp=sharing

It was a complicated meeting to control the time and in the end we were left without a report.

A brotherly hug

**Comment by AntonyCorbett** [comment]
@AlexSanti I exceeded the spending limit on the server I use which means that the meeting times feed won't be available until July 1. Sorry. I'll see if I can fix sooner.

**Comment by AlexSanti** [comment]
Why does the count at the end of the assignment return to the beginning of the meeting? The program did not have this procedure.
You can see it in the short video I made.

**Comment by AntonyCorbett** [comment]
@AlexSanti the app relies upon the meetings feed when you are using the automatic mode. I assume that without it the meeting resets at the end of each item. I will check tomorrow.

**Comment by AlexSanti** [comment]
@AntonyCorbett did you see the video I made? What happened yesterday at the
end of each assignment, the counter always changes to the first. It is not
normal. This was another problem.

Em sex., 19 de jun. de 2020 às 22:23, Antony Corbett <
notifications@github.com> escreveu:

**Comment by AntonyCorbett** [comment]
@AlexSanti I didn't view the video as I don't have access to it. I believe the behaviour you experience is  because the feed is unavailable. I have just fixed the problem with the feed. Please let me know if this solves the problem.

**Comment by AlexSanti** [comment]
@AntonyCorbett

This is the video

https://drive.google.com/file/d/1djO_Y6yzKIqbgXsnRLsK793M2CG760b_/view?usp=drivesdk

**Comment by AntonyCorbett** [comment]
@AlexSanti Thanks I have watched the video and can confirm that the behaviour is caused by the problem with the feed which is now fixed. Please would you confirm if this solves the problem.

**Comment by AlexSanti** [comment]
@AntonyCorbett it’s ok, problem solved.

Thanks
