### ISSUE TITLE
Is timer report possible to have also for file based timing? It did not create any.

### ISSUE THREAD

**Issue by pepekall** [AntonyCorbett/OnlyT#410]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AntonyCorbett** [comment]
@pepekall Thanks. Let's see how popular this would be.

**Comment by pepekall** [comment]
For special occasions. We had a LDC training yesterday and today. I made a special file for the program and it worked well, but I would have needed the report for presenters so they could adjust the presentations for next weekend.

There will be a lot of trainings in the near future and that would be a nice option.

I suppose there is no way to workaround this?

// Juha



Lähetetty Samsung Galaxy -älypuhelimesta.



-------- Alkuperäinen viesti --------
Lähettäjä: Antony Corbett <notifications@github.com>
Päivämäärä: 11.7.2020 13.34 (GMT+02:00)
Saaja: AntonyCorbett/OnlyT <OnlyT@noreply.github.com>
Kopio: Juha Kalliola <juha@kalliola.com>, Mention <mention@noreply.github.com>
Aihe: Re: [AntonyCorbett/OnlyT] Is timer report possible to have also for file based timing? It did not create any. (#410)


@pepekall<https://github.com/pepekall> Thanks. Let's see how popular this would be.

**Comment by AntonyCorbett** [comment]
@pepekall You would need to make a note of the timings as you go,

**Comment by pepekall** [comment]
I found out that the ”report” is visble on the dropdown list. This Works for now

[cid:image001.png@01D6578C.224910A0]

Lähetetty Windows 10:n Sähköposti<https://go.microsoft.com/fwlink/?LinkId=550986>sta

Lähettäjä: Antony Corbett<mailto:notifications@github.com>
Lähetetty: lauantai 11. heinäkuuta 2020 14.01
Vastaanottaja: AntonyCorbett/OnlyT<mailto:OnlyT@noreply.github.com>
Kopio: Juha Kalliola<mailto:juha@kalliola.com>; Mention<mailto:mention@noreply.github.com>
Aihe: Re: [AntonyCorbett/OnlyT] Is timer report possible to have also for file based timing? It did not create any. (#410)


@pepekall<https://github.com/pepekall> You would need to make a note of the timings as you go,
