### ISSUE TITLE
API add or subtract minutes

### ISSUE THREAD

**Issue by dorofino** [AntonyCorbett/OnlyT#411]
There is any way to start a timer and add or subtract minutes using the API?

I'm trying to automatically add or subtract minutes to the Watchtower timer when the Talk finish early or rans late. 

Best, 
Diego

**Comment by AntonyCorbett** [comment]
@dorofino Is there any reason why the adaptive timing mode doesn't provide what you need?

**Comment by dorofino** [comment]
> @dorofino Is there any reason why the adaptive timing mode doesn't provide what you need?

Yes sure, but can I modified the adaptive timing from the API?

**Comment by AntonyCorbett** [comment]
@dorofino Do you mean turn adaptive timing on / off?

Regarding the adaptive timer feature not working, please would you explain further? Typically, you would decide whether you want to use adaptive timing for midweek or weekend or both and then just leave it at that - there's no reason to keep turning it on or off.

**Comment by AntonyCorbett** [comment]
@dorofino Closing as no response. But please reopen if needed.
