### ISSUE TITLE
Fine tune timer

### ISSUE THREAD

**Issue by Stokesy84** [AntonyCorbett/OnlyT#413]
**Is your feature request related to a problem? Please describe.**
Yes, IE. A brother starts an item, if we forget to launch the timer straight away we are stuck

**Describe the solution you'd like**
Able to use the + and - button to fine tune any item, its greyed out for most parts. 

**Describe alternatives you've considered**
Some items don't have the timer, as there is no option to start the timer late,

**Additional context**
During CLM, especiall open 2 items, cannot adjust time.

**Comment by LvDaniel** [comment]
Indeed, till "Bible Reading" (including) all is grayed out.
Sometimes we forgot to start the timer on time so we would love to have the option to decrease the time with 1 or 2 mins.
If it's possible to have in settings an option to adjust the first talks, that would be appreciated.

**Comment by AntonyCorbett** [comment]
@LvDaniel This was included some time back but I forgot to close the issue :)
