### ISSUE TITLE
Remote Mode for Windows App

### ISSUE THREAD

**Issue by MiltJR111** [AntonyCorbett/OnlyT#414]
I have a computer that I use for the meeting timer, and a different computer I use for Zoom. I'd like to be able to remotely control the OnlyT timer from the Zoom computer, but presently there isn't a way to do this.

If it was possible to enable "Remote Mode" for the Desktop app, to give you the ability to connect to the timer as you would with the mobile app, this would allow more flexibility for people using multiple PCs.

Somewhat related but also probably separate would be the ability to adjust the timer remotely for part timings. I originally thought that using the File-Based method would work if custom part timings were needed, but then there's no reporting which I need to provide to the Life & Ministry Assistant (unfortunately I didn't realize that until after the meeting tonight).

So I suppose either allowing the timers to be adjusted remotely from the mobile apps or allowing a PC to work in remote mode (and still allow the timers to be adjusted) would be great. Thanks for all of your work on this!

**Comment by AntonyCorbett** [comment]
@MiltJR111 Your best option at the moment is to run the OnlyT web client on your other PC and OnlyT on your Zoom PC. Regarding the 2nd question, please would you raise a separate issue?
