### ISSUE TITLE
OnlyT Crashing on Settings Page

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#416]
I installed OnlyT version 1.3.0.4 on a newly-imaged Windows 10 desktop. I went into OnlyT settings, and as soon as I clicked the "Enabled" checkbox for "Remote Apps", OnlyT crashed and closed out. I re-opened OnlyT and tried enabling Remote Apps one more time, and it crashed again. The next time, I tried entering an Access code, then closing and re-opening the OnlyT settings. This time, once the Access code was entered, I was able to enable the Remote Apps without it crashing.

Also, I noticed the app would crash if you attempt to open the Remote Access port (8096) again after it was already opened.

I attached my OnlyT log for your reference. I hope you and the family are doing well. Let me know if you require any additional information. But I wanted to report these 2 issues that I recently found.
[log-20201218.txt](https://github.com/AntonyCorbett/OnlyT/files/5716646/log-20201218.txt)

**Comment by AntonyCorbett** [comment]
Fixed now. Thanks.
