### ISSUE TITLE
Timer only for Bible Reading

### ISSUE THREAD

**Issue by aLiEnMuNkEe** [AntonyCorbett/OnlyT#418]
I only see the auto timer sound for the bible reading. Am i missing a setting for the other student items?

**Comment by AntonyCorbett** [comment]
@aLiEnMuNkEe Please see #417

**Comment by aLiEnMuNkEe** [comment]
> @aLiEnMuNkEe Please see #417

Brilliant thanks Antony - I didn't see that thread.

**Comment by AntonyCorbett** [comment]
> Brilliant thanks Antony - I didn't see that thread.

Yes, I'd closed it so it's not visible unless you search. I'll leave this one open for a few weeks :)
