### ISSUE TITLE
Comments timer

### ISSUE THREAD

**Issue by Spenser715** [AntonyCorbett/OnlyT#420]
Feature request to have a comment timer that only shows up during the parts that have comments to be able to get an idea how long ones are taking on comments so as to follow encouragement to have comments be 30 seconds or less.

**Comment by AntonyCorbett** [comment]
@Spenser715 Thanks for your suggestion. Unfortunately, I think this feature is very niche so probably not worth spending time on. However, I'll leave it open for another month or so to see if others feel differently.

**Comment by DavidIQ** [comment]
Would probably have the opposite effect of encouragement I think. Plus if the timekeeper has to do additional work for this comments timer it means they're not likely to be able to pay attention or participate themselves.
