### ISSUE TITLE
Xml file

### ISSUE THREAD

**Issue by KwstasE** [AntonyCorbett/OnlyT#422]
Hello,

Can anyone send me a midweek xml example with the sections in already? I am struggling to put Sections on the meeting schedule xml file. Thanks in Advance

email: euaggeloykws@yahoo.gr

**Comment by AntonyCorbett** [comment]
@KwstasE Do you know that there's an _Automatic Mode_ for the meetings?

**Comment by KwstasE** [comment]
@AntonyCorbett I know, but I want to make some changes. I am trying to make sections like the automatic one in midweek meeting but I do something wrong. Can I Have a sample xml from a midweek meeting that already have sections and I will modify it and paste it in document/OnlyT folder

**Comment by AntonyCorbett** [comment]
@KwstasE Understood. The "section" attribute might be added to items like this:

```
<meeting>
  <items>
    <item name="Music" section="prelude" duration="00:03:00" />
    <item name="Welcome" section="main" duration="00:03:00" />
    <item name="Keynote" section="main" duration="01:00:00"  />    
    <item name="Concluding Comments" section="main" />
  </items>   
</meeting>
```

**Comment by KwstasE** [comment]
@AntonyCorbett thanks a lot.
