### ISSUE TITLE
Mac Suport

### ISSUE THREAD

**Issue by lastowl** [AntonyCorbett/OnlyT#423]
**Is your feature request related to a problem? Please describe.**
We had a mix of Mac and Windows users hosting meetings and needed a Mac solution for the timer.

**Describe the solution you'd like**
We already have a working solution just wanted to let others know. It uses Wine to run the existing Windows EXE.

**How it was made**
Built using OnlyT 1.3.0.4 release on Wineskin 2.9.0.7-rc4 with WS11WineCX20.0.2 engine
WineTricks is then used to install .NET Framework 4.8

**Found Negatives**
Due to all the required dependencies its 1.31GB
Gatekeeper will require manual app approval before being opened the first time _(via the Security & Privacy panel)_
App needs to be launched from the users desktop the first time _(can be moved after first launch)_

**Release**
[OnlyT 1.3.0.4 Mac Wrapper](http://sanity.fail/OnlyT.app.zip)

**Comment by AntonyCorbett** [comment]
@lastowl Thanks!
