### ISSUE TITLE
Reports NOT Generated? 

### ISSUE THREAD

**Issue by Luca-Macari** [AntonyCorbett/OnlyT#424]
Hi there

Can someone please explain why all of a sudden the OnlyT reports won't generate after a meeting?

Edit: I have tried to time a whole meeting, not just a test & still could not get a report generated.

Kind Regards

**Comment by AntonyCorbett** [comment]
@Luca-Macari The log file should tell us. The log is stored in the Documents\OnlyT\Logs folder.

**Comment by Luca-Macari** [comment]
I have the folder but no logs are in it. I will try again tonight and see what happens.

**Comment by Luca-Macari** [comment]
So tried again, but the same message that the report wasn’t generated and no logs have been generated in the path that you highlighted 🤷🏻‍♂️

**Comment by AntonyCorbett** [comment]
@Luca-Macari If no logs are being generated then it sounds like you might have enabled "Controlled folder access" in Windows 10. Which would also explain why no report is generated. Please search for the "Controlled folder access" applet in Windows and let me know if that's the reason.

**Comment by AntonyCorbett** [comment]
@Luca-Macari Any update on this please?

**Comment by Luca-Macari** [comment]
Hi there

My apologies for the late reply. I think you have solved it ( I can’t access the controlled folder access, working on it now) but I will tell you if it works soon.

Kind regards

**Comment by Luca-Macari** [comment]
@AntonyCorbett  That is it working now. Thank you for pointing me in the right direction.

Kind Regards
