### ISSUE TITLE
Please explain the difference between one-way and two-way adaptive timing

### ISSUE THREAD

**Issue by JamesR8** [AntonyCorbett/OnlyT#425]
First off, thank you very much for the great work put into this helpful tool! 

I've read the wiki and one or two related posts, but somehow it's still not very clear to me. 
Please explain the differences between one-way and two-way adaptive timing. 
Some examples will be very helpful too. 

Regards,
J

**Comment by Spenser715** [comment]
One way timing simply will reduce the time of parts if a part prior to it went overtime.

**Comment by Spenser715** [comment]
another more in depth example of 2 way with OCLM meeting

opening comments goes 2 minutes instead of 1 then treasures is shortened to 9 minutes. if then they go under and only use 8 minutes then the digging will now have an extra minute and be able to go 11 minutes.

This can be much more confusing so I suggest 1 way from my experience. It will keep the meetings on time but won't confuse brothers wondering why the clock says they have more time than the part is supposed to have.

**Comment by JamesR8** [comment]
Great thanks @Spenser715 for that explanation with examples. 

So I must be doing something incorrectly? 
I've set both midweek and weekend meetings to one-way adaptive modes. 
I've been running a 'test' meeting simulating all the parts going overtime (see screenshot from the mobile app a bit earlier in my test). However, I don't see any automatic adjustments for the subsequent parts. 

My 'test' meeting is now in what should be the CBS and it still shows the originally allotted 30 minutes. Any ideas as to what I could be doing incorrectly? 

![Screenshot_20210308_211421_com imattsolutions onlyt](https://user-images.githubusercontent.com/80283026/110371476-b60fdb00-8055-11eb-9f00-d71a084880c1.jpg)

**Comment by Spenser715** [comment]
I have not tested using the adaptive timer with the app. Have you tested with running the timers overtime directly on the windows computer with onlyT installed?

**Comment by JamesR8** [comment]
Yes I have. 
For clarification, I have been controlling the timer (i.e. starting/stopping the timer) directly on the Windows PC. 
I was merely also viewing it also via the mobile app.

**Comment by Spenser715** [comment]
Ok and just to check have you restarted the OnlyT program after changing the adaptive setting?

**Comment by AntonyCorbett** [comment]
@JamesR8 from the Wiki: "Note that some item durations are never adapted - it depends on the meeting format." In the midweek meeting I think it's only items in the "Living as Christians" section that is adapted, but I would need to check to be sure.

**Comment by JamesR8** [comment]
> Ok and just to check have you restarted the OnlyT program after changing the adaptive setting?

I think I did but now I'm questioning myself :) We'll run it at our meeting this week and I'll report back thereafter.

**Comment by JamesR8** [comment]
@AntonyCorbett Got it thank you. Just didn't want to be caught unawares during our live meeting this week.
