### ISSUE TITLE
"section" 

### ISSUE THREAD

**Issue by gionatanbottaini** [AntonyCorbett/OnlyT#426]
Thanks for the great job you have done. Since we are in this difficult situation due to COVID we have started using the timer for the meetings I was able to give access to all the brothers who have the parties to the TIMER via a remote DNS server.

We usually use the file-base setting to set the timers but I can't find a way to use this parameter: 

```
<!--"section" is an optional identifier referring to the section of the meeting in which the talk is 
  scheduled. It's not used directly by OnlyT but remote control apps may use it-->

```
Could you send me an example of the midweek meeting on how to set this parameter?

**Comment by AntonyCorbett** [comment]
Please see #422 for an example.
