### ISSUE TITLE
"section"

### ISSUE THREAD

**Issue by gionatanbottaini** [AntonyCorbett/OnlyT#427]
Good morning yesterday I tried to use the "section" setting in file-based mode.
But on the Android or iOS app, I couldn't see any sections as I see them in Automatic mode.
How? 

``
AUTOMATIC MODE
![Automatic Mode](https://user-images.githubusercontent.com/81307528/112434719-2f8d1600-8d44-11eb-9bfc-1b84a61a7e4c.png)

FILE BASED MODE
![file-based MODE](https://user-images.githubusercontent.com/81307528/112434724-3025ac80-8d44-11eb-8f75-348a4415d9a5.png)

**Comment by AntonyCorbett** [comment]
@gionatanbottaini The section setting is made available to 3rd-party applications using the OnlyT API, but it's up to the apps whether they use it. I'm not that familiar with any of the mobile apps and you may wish contact their authors for support on this.
