### ISSUE TITLE
Main timer cannot be set to windowed mode

### ISSUE THREAD

**Issue by DhitiBank** [AntonyCorbett/OnlyT#428]
I cannot set main timer to windowed mode (please see attached clip video). It used to be fine and I am not sure when this problem started. Could it be that it happened after I'd changed main display to second monitor 4 weeks ago? I tried to uninstall and re-install many times, but nothing changed.

https://user-images.githubusercontent.com/65483100/115976956-2ee2dc00-a59d-11eb-82d2-55d5d11c0197.mp4

OnlyT version: 1.3.0.8
OS: Windows10 20H2 build 19042.928

I'm not good in English, so please forgive me for any mistakes.

Best regards,
Dhiti T.

**Comment by AntonyCorbett** [comment]
@DhitiBank First try dragging the timer window to show the edges of the window so you can then resize it. If that doesn't work, press Win+Down (the Windows Key and the down arrow key). (If the timer window is maximised this will restore it.)

**Comment by DhitiBank** [comment]
@AntonyCorbett Thank you very much for your application and instruction. That's really work!
