### ISSUE TITLE
onlyt 2.0.0.3 portable

### ISSUE THREAD

**Issue by bergerchemical** [AntonyCorbett/OnlyT#429]
Hi, pre-release version 2.0.0.3 portable, surface pro 3 i5:
an error appears when trying to start, even though the .net runtime is installed and up to date
![image](https://user-images.githubusercontent.com/15932535/121734885-a6d97700-caf5-11eb-97c4-3b29d84a6b5c.png)

**Comment by AntonyCorbett** [comment]
You will need to install the x86 .net 5 runtime (not the x64 runtime)

**Comment by bergerchemical** [comment]
it works thx
