### ISSUE TITLE
no time synchronization

### ISSUE THREAD

**Issue by bergerchemical** [AntonyCorbett/OnlyT#432]
is this a bug?
OnlyT ver. 2.0.0.4 portable
![obraz](https://user-images.githubusercontent.com/15932535/124462561-1c9dcf00-dd92-11eb-9106-53f24ddd8058.png)

**Comment by AntonyCorbett** [comment]
@bergerchemical Yes. Thanks for reporting

**Comment by AntonyCorbett** [comment]
@bergerchemical Now fixed in v2.0.0.5. Thanks for your help.
