### ISSUE TITLE
Windowed Timer Resizing

### ISSUE THREAD

**Issue by ice-cure** [AntonyCorbett/OnlyT#434]
Hello, I'm using OnlyT earlier and I always use the "Windowed" option because I can move and resize the timer, but I accidentally double-clicked the top part of the timer and it fills up now the whole screen. I tried double-clicking the same part again but it didn't revert into a small-timer. My colleague shows me that he can resize it back from his computer by hovering into the sides of the timer and waiting for the resize cursor, I tried it to mine but whenever I hover to my screen the resize arrow doesn't show.

NOTE:
His timer is on his second screen while mine is on my main screen. I tried reinstalling too hoping that it will go back into its default state but it didn't work, it still has the same settings I made.

Is there any way I can change OnlyT back into its default stage? Maybe some files that I can delete after it is uninstalled, or maybe a "Default" button in the settings on the next update. Thank you and thanks for your great software!

**Comment by AntonyCorbett** [comment]
@ice-cure Thanks for your report. Are you using the latest version of OnlyT? I don't think it's possible to do this anymore.

**Comment by AntonyCorbett** [comment]
@ice-cure If you want to reset settings, they are stored in options,json in the users roaming profile, e.g. 

C:\Users\[Your Name]\AppData\Roaming\OnlyT\1\options.json

Just close OnlyT, delete the file and restart.

**Comment by ice-cure** [comment]
> @ice-cure Thanks for your report. Are you using the latest version of OnlyT? I don't think it's possible to do this anymore.

yes

**Comment by ice-cure** [comment]
> @ice-cure If you want to reset settings, they are stored in options,json in the users roaming profile, e.g.
> 
> C:\Users[Your Name]\AppData\Roaming\OnlyT\1\options.json
> 
> Just close OnlyT, delete the file and restart.

oh i'll try that

**Comment by ice-cure** [comment]
> @ice-cure If you want to reset settings, they are stored in options,json in the users roaming profile, e.g.
> 
> C:\Users[Your Name]\AppData\Roaming\OnlyT\1\options.json
> 
> Just close OnlyT, delete the file and restart.

It's fixed now thanks :)
