### ISSUE TITLE
Set Output Window Size

### ISSUE THREAD

**Issue by ryrylightfoot** [AntonyCorbett/OnlyT#438]
Would it be possible to please add the Windowed Fixed size options on OnlyT that you added to OnlyM? 

We use OnlyT with OBS Studio to show the timer on Zoom. To do that OnlyT must be set to Windowed mode and the output windows need to be the same size every time so OBS can find the windows and so they look correctly on OBS. 

We have also found that the window size has an impact on the image quality on Zoom. At first I told them to set the output windows in a corner of their screens, which on 1080p screen would be about 480p, that doesn't look great on Zoom.

I am the IT guy for the congregation and it is a struggle to help the brothers who want to help out set up their computers because OBS needs a consistent window size and some brothers have 1080p screens while others have 4k screens. So I find myself having to meet on Zoom to remotely control their devices and set it up myself. It would be huge difference if I could just send them my OBS Scenes file and tell them to set OnlyT to 1080p.

Thank you for these programs you've made that help in our worship. And I hope you enjoy the rest of your day.

**Comment by AntonyCorbett** [comment]
@ryrylightfoot This was implemented some time ago. Additionally, the latest pre-release features NDI support, which means you can integrate the timer directly into OBS with the help of the OBS NDI plugin.
