### ISSUE TITLE
Mac version 

### ISSUE THREAD

**Issue by davideloddeDev** [AntonyCorbett/OnlyT#439]
hi, I am davide. I contact you to Italy. It’s possible one Version for the Mac.

**Comment by notjulian** [comment]
> hi, I am davide. I contact you to Italy. It’s possible one Version for the Mac.

Hi,
with CrossOver (https://www.codeweavers.com/)
it is working, I've tried the latest version (2.0.0.10) on a .Net 4.8 bottle
<img width="1151" alt="Screenshot 2022-01-03 at 23 39 51" src="https://user-images.githubusercontent.com/2241601/147988199-485cc1f4-7a66-4e62-95d1-44a8a8338df4.png">

**Comment by davideloddeDev** [comment]
it honestly doesn't seem right to use the organization's funds for a program of this type, so I cut my head off and created a version with xcode for mac with m1 processor

Inviato da iPad

**Comment by wphenry83** [comment]
Hello my Brothers. My congregation just received the Mac Mini with the M1 Chip. JW Library currently does not display to an external monitor (extended).  Is there a way to do media and timer?? A sound box for mac or  three apps (only M, Only T, and Only V). or a better workaround than setting all media in OBS. If so let me know, please. Thank you in advance.

**Comment by OishiiCha** [comment]
> Hello my Brothers. My congregation just received the Mac Mini with the M1 Chip. JW Library currently does not display to an external monitor (extended).  Is there a way to do media and timer?? A sound box for mac or  three apps (only M, Only T, and Only V). or a better workaround than setting all media in OBS. If so let me know, please. Thank you in advance. 

It depends on your use, there currently isn't any M1 arm wrappers to my knowledge for OnlyX suite.

If you are wanting to do video share on zoom, best option is to do the share on advanced and select video.

For KH setting, best app to use would be VLC and to set the application to play video on external monitor in the settings.

For the timer you May have to use one from the appstore, or possibly use Wine/crossover if that works.

A lot of the software used in KH is windows based so it May be difficult to find a mac alternative. Microsoft currently have no plans for windows on arm to work on the M1 chip.

For KHCONF video, the software used is based upon OBS, so you could configure that to work for that use, or do a direct stream to KHCONF from zoom if zoom is being used.

I hope this helps.

If anyone else has any other information or doesn't agree with the info. Please update.

**Comment by lastowl** [comment]
We use https://github.com/sircharlo/jw-meeting-media-fetcher for automatically downloading all the media, then we just screen share the media. 
I've got wrapper working on Intel Mac's for OnlyT but haven't had chance to test it on an M1 Mac yet

**Comment by wphenry83** [comment]
Thank you brothers for your help. We will be using OBS and have CrossOver as a backup
