### ISSUE TITLE
Circuit Visit option on main screen

### ISSUE THREAD

**Issue by JonMcFly** [AntonyCorbett/OnlyT#44]
Following my last comment, if the Circuit Visit checkbox was moved to the main screen, it would also mean that for the most part, the brothers would have no reason to use the settings button once it has been set up, and thus could be disabled.

**Comment by Passarito** [comment]
This suggestion makes sense when several congregations share the same equipment, one having the Circuit Visit would let the option saved for the other not having the circuit visit.

**Comment by its-markk** [comment]
Just raising my hand for the CO Visit option to be moved to the main page.  We have CO starting this week, and our congregation (1 of 4 at the hall) has started to use JWL and OnlyT.  Going to encourage the other congregations to start on this path as well.
Thanks for your work and the thought that you put in to the designs.

**Comment by AntonyCorbett** [comment]
@Blann it will help to resize the settings window.

**Comment by AntonyCorbett** [comment]
Now available in latest pre-release. Turn the feature on in Settings

**Comment by Blann** [comment]
@AntonyCorbett Excellent, thanks.

**Comment by JonMcFly** [comment]
Just in time for the circuit visit next week 🥇
