### ISSUE TITLE
ARM / Raspberry Pi support

### ISSUE THREAD

**Issue by Mister-King** [AntonyCorbett/OnlyT#440]
It would be fantastic to have this working on a Raspberry Pi connected to a screen at the back of a hall.

Trying to use Wine on an ARM infrastructure is not ideal when trying to run x86 programs.

**Comment by bergerchemical** [comment]
Ah that would be great! We use a raspi as a file server in the Kingdom Hall to display the electronic bulletin board. It would be great to use the raspberry even better :) it is perfect for such tasks

**Comment by realtebo** [comment]
we simply opened a browser pointing to web timer.

**Comment by eXXence** [comment]
We got it putting data on mysql accessed by lan (acustic/president pc), on raspberry the timer is shown by a browser, some php, some js.
OnlyT integration should be fine!
