### ISSUE TITLE
API available

### ISSUE THREAD

**Issue by rafik73github** [AntonyCorbett/OnlyT#45]
Welcome
Is API available?

**Comment by AntonyCorbett** [comment]
See #40

**Comment by MrPaulus** [comment]
The link to #40 doesn't answer the query.

**Comment by AntonyCorbett** [comment]
@MrPaulus - it was just a note explaining the closure of the duplicate issue. #40 points to an earlier identical issue.

**Comment by MrPaulus** [comment]
#40 asks if we can have a remote control, and it points to this issue. Presumably, the answer is that is an API is available then someone else could create a remote timer for iOS for example. However, unless I’m missing something there is no detail about an API.

**Comment by AntonyCorbett** [comment]
@MrPaulus There is no API available yet. The issue is designated an "Enhancement"
