### ISSUE TITLE
Only T stuck in Manual mode

### ISSUE THREAD

**Issue by PaulAspinall** [AntonyCorbett/OnlyT#450]
Only T has been stuck in Manual Mode since Sunday. Have tried closing down, ending task but nothing works.

**Comment by AntonyCorbett** [comment]
@PaulAspinall You don't indicate, but I assume you have tried to turn it back to Automatic mode. When you do so, does the UI change to show that the mode is now automatic (e.g. is a list of talks available)? If not, what is shown? Or is it the case that the automatic mode can be set while the software is running, but is then forgotten when OnlyT is closed down? Please try to provide as much info as you can. Thanks, Antony

**Comment by PaulAspinall** [comment]
Hi, I cannot switch it to automatic mode at all and it just stays in manual mode. 
I have gone into the settings and toggled automatic off and then back on but as soon as I come out of the settings, the main screen is still in manual mode.

**Comment by AntonyCorbett** [comment]
When you launch the application, is it in Manual mode even though the setting indicates Automatic? Or are you saying that the dropdown box in the Settings page does not retain the "Automatic" option? 

Please would you send your log file?

**Comment by PaulAspinall** [comment]
The dropdown box in settings is listed as Automatic but the main screen is on manual. 

How do I create a log file?

**Comment by PaulAspinall** [comment]
I’ll have a look at it again on Sunday and carefully go through each setting to see if anything has changed.

**Comment by AntonyCorbett** [comment]
@PaulAspinall is there any update on this issue, please?

**Comment by PaulAspinall** [comment]
Hi, yes sorry, it is fixed. I managed to go into the settings and select automatic and when a came out the settings, it was working perfectly.
