### ISSUE TITLE
Countdown timer stops JWL audio music

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#452]
Hi Antony,

When we're using the countdown timer (on the media screen) seems like JWL Media Windows is minimized and this prevents JWL audio music to run in background (before the meeting starts).
I'm not sure if this is the normal behavior, so just want to confirm this with you.
If so, does this mean we need to play the background musing using a different audio player not JWL?
Or we need to use JwlMediaWin tool if we want to play the background music using JWL while using the countdown timer?
Thanks for clarification.

**Comment by AntonyCorbett** [comment]
@LvDaniel This isn't behaviour that I've seen. Whether you are playing video or just audio, minimising the JWL media window does not mute the audio in my experience. Some questions:

1. Does the audio continue to play (but silently)?
2. Does the audio return when you manually restore the JWL media window (using JWL the taskbar icon)?

JwlMediaWin will keep the JWL window open albeit behind the timer window, so it may be worth trying.

Regards
Antony

**Comment by LvDaniel** [comment]
@AntonyCorbett the song that is running when the countdown appears (5 mins before the meeting) continues to play normally,  but when this finishes and next song should start, it doesn't starts (remains paused at 0:00). The same applies if I try to manually start a new song. If I try to hit play button, in the end starts but silently.
When I manually restore JWL media window, the audio returns, but the countdown disappears (as I'm not using JwlMediaWin tool).

**Comment by AntonyCorbett** [comment]
@LvDaniel I see. Presumably, the audio doesn't start because the JWL media window is minimised. This is another reason to use JwlMediaWin. Or perhaps not to use the countdown.
