### ISSUE TITLE
Crash when trying to open settings

### ISSUE THREAD

**Issue by Coryc1123** [AntonyCorbett/OnlyT#46]
For some reason i can replicate this issue on two different computers but on a third it works fine. Everytime I open the settings gear icon the program crashes. The 2 computers that it happens on have usb to hdmi plugs. Not sure if that helps.

**Comment by AntonyCorbett** [comment]
@Coryc1123 Please ensure you're running the latest version. Then check the log file. Please get back to me - I'd like to know what the log says.

OnlyT maintains a log (a simple text file) of activity which can be useful if you run into problems. The log is stored in the Documents\OnlyT\Logs folder.

**Comment by Coryc1123** [comment]
2017-12-12 07:57:07.369 -05:00 [Information] ==== Launched ====
2017-12-12 07:57:09.704 -05:00 [Error] Could not open timer window
System.InvalidOperationException: Sequence contains more than one matching
element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source,
Func`2 predicate)
   at
OnlyT.Services.Monitors.MonitorsService.GetDeviceMatchingScreen(DisplayDeviceData[]
devices, Screen screen)
   at OnlyT.Services.Monitors.MonitorsService.GetSystemMonitors()
   at OnlyT.Services.Monitors.MonitorsService.GetMonitorItem(String
monitorId)
   at OnlyT.ViewModel.MainViewModel.OpenTimerWindow()


Thanks!

On Dec 12, 2017 4:03 AM, "Antony Corbett" <notifications@github.com> wrote:

@Coryc1123 <https://github.com/coryc1123> Please ensure you're running the
latest version. Then check the log file. Please get back to me - I'd like
to know what the log says.

OnlyT maintains a log (a simple text file) of activity which can be useful
if you run into problems. The log is stored in the Documents\OnlyT\Logs
folder.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AntonyCorbett/OnlyT/issues/46#issuecomment-350988262>,
or mute the thread

**Comment by Coryc1123** [comment]
the second pc might have an issue. The log file only shows the first line "launched" although hitting the settings button no other lines are shown in the log file. I've tried reinstalling the file but to no avail

**Comment by AntonyCorbett** [comment]
@Coryc1123 - please would you try the latest release and let me know if this fixes the issue?

**Comment by Coryc1123** [comment]
Wow! Worked thanks!

**Comment by AntonyCorbett** [comment]
@Coryc1123 good news!
