### ISSUE TITLE
clock to taskbar

### ISSUE THREAD

**Issue by rivasjadiel** [AntonyCorbett/OnlyT#461]
**Is your feature request related to a problem? Please describe.**
Hi is there any possibility or way to minimize the OnlyT window and have the timer displayed on the taskbar? I'm using a Surface and when giving an assignment I want to try to have OnlyT in a space where I can use the screen

**Describe the solution you'd like**
minimize the OnlyT window and have the timer displayed on the taskbar

**Comment by AntonyCorbett** [comment]
@rivasjadiel The latest version provides a minimise function that may help to free up more screen space.

**Comment by AntonyCorbett** [comment]
Closing as I believe the new optional minimize behaviour provides what is needed.
