### ISSUE TITLE
The iOS and Android apps failed to sync

### ISSUE THREAD

**Issue by CleefZX** [AntonyCorbett/OnlyT#466]
When we connect the OnlyT app on the laptop* with the IP, code and key in the iOS or Android phones/tablets it fails to sync from time to time. We have to be in the same connection, however the laptop we use is connected via cable ethernet port and wifi; the wifi has also two types 2.4 Ghz. and 5.2 Ghz. So it is a bit confusing and unreliable when using during a meeting. The IP web timer visualizer also stops randomly from time to time. 

Maybe making this app web based would help a lot to resolve the sync issues. The app Stagetimer.io manages it perfectly: https://stagetimer.io
____________
*We are using Windows 11 on a Lenovo laptop as the main computer to run the meeting. We've tried the app on different phones and tablets.

**Comment by scottys94** [comment]
@CleefZX The computer is connected to both hardwire and Wifi? Can you disconnect one and then see if the app works reliably? With 2 active connections your PC likely has 2 default gateways which will definitely create issues.

**Comment by AntonyCorbett** [comment]
@CleefZX Closing for now as there is no response. Please re-open if needed.
