### ISSUE TITLE
Specify Off-Times for Meeting Parts

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#467]
Hi Antony,
Would it be possible for OnlyT to time each meeting part based on its scheduled end time? For example, on certain days the Congregation Bible Study may start later than usual, but it still needs to end at 8:37 for us. I'm aware of the Adaptive mode, but I feel having the app programmable with specific off-times would allow the timing to be more precise. This came up today because I often see brothers glancing between both the timer and the wall clock. They know they need to be off the stage at a certain time, but sometimes the timer suggests otherwise. Thanks for all your hard work on developing and maintaining this app. Our congregation is greatly benefiting from it, especially the pre-meeting countdown :)

**Comment by AntonyCorbett** [comment]
Hi Scotty. Thanks for your observation. What do the instructions say regarding the timing of parts? I'm not so sure that a "finish time" is relevant. Each item is assigned a _duration_ and the speaker should not take any longer, and they should not prolong the item to take up any slack. Now take an example: Suppose the meeting is running behind by 5 minutes at the start of the "Living" section. And suppose the first item in that section is 5 minutes long. If the speaker adheres to a "finish time" then he should just get up and introduce the next item! The timing instructions allow the speaker to take his 5 minutes, but if subsequent speakers kept to this regime and made no effort to reclaim some of the time then the meeting would run overtime, which is not permitted by the timing instructions. Logic demands that the 5-minute overrun is reclaimed somehow, but should this be at the expense of a single item or spread among remaining items on the agenda in proportion to their duration? The latter approach is taken by the adaptive timing mode in OnlyT. 

With the adaptive mode enabled, the speaker can be confident that the OnlyT timer provides a fair indication of time available for each item.

Thanks, again. I'd welcome your further comments on this.

**Comment by scottys94** [comment]
I appreciate the explanation Antony. It makes sense especially if the parts early in the meeting finish sooner than expected. That would not entitle the later parts to take more than the allotted time. I'll let you know if I have further questions.
