### ISSUE TITLE
Real-time save or loss time

### ISSUE THREAD

**Issue by alanfermtz** [AntonyCorbett/OnlyT#474]
**Is your feature request related to a problem? Please describe.**
Its not a problem

**Describe the solution you'd like**
Hello there,

It will be excellent if we can have on monitor and web clock, the feature to see the real time total loss or save time. This based on when the meeting its supposed to start

**Describe alternatives you've considered**
The only alternative its to manually sum the differences of time 

**Additional context**
n/a

**Comment by alanfermtz** [comment]
Something like these 
![image](https://user-images.githubusercontent.com/43801184/223577791-98bf7503-7528-471c-a452-d5593725c8ce.png)

**Comment by AntonyCorbett** [comment]
@alanfermtz thanks for your feedback. Please would describe your idea in more detail. Thanks, Antony.

**Comment by AntonyCorbett** [comment]
@alanfermtz If I understand correctly, the proposal is that OnlyT window would display a value showing how many minutes and seconds the meeting was ahead or behind. Some questions please:

1. Would this be displayed on the operator's screen (main window) or on the timer window or both? I'd be reluctant to provide any more information on the timer window because it may be confusing, but can't see the benefit of showing it on the main window.
2. Would the value be updated only at the end of each assignment when the operator stops the timer? Or on the start of a timer too?
3. How would the proposed function interact with OnlyT's adaptive modes? For example, if the meeting is running behind schedule by 5 minutes, the adaptive timer may reduce the next talk duration by 2 minutes. Should the value shown be -5 minutes or -3 minutes? If the speaker sees that the meeting is behind by 5 minutes he may decide that he should make up that time and reduce the duration of his item even further.

**Comment by alanfermtz** [comment]
1. Operator, monitor and web clock (please web clock haha its what we used). Why? The chairman ask us of how much time ahead or behind. So if we have it on monitor and web clock, he can see exactly how we are going.
2. I think is fine when we start the next part, it updates you the time. Also will be really nice, if the speaker is already over time, the time start to increase the timer. Like this video

https://user-images.githubusercontent.com/43801184/223792983-c3afc86d-7a47-4ed1-89b3-00ccc2edd054.mp4

3. That feature im not really aware of how works because im just started to analyze this program. And I have seen only the basic functions.

OFFTOPIC: Let me ask you something, how the program know how much time the chairman elpased to give the counsel to the student between the last part of apply yourself to the field ministry and the song?

**Comment by AntonyCorbett** [comment]
OnlyT's _Adaptive_ timing mode automatically takes into account how are far behind or ahead of schedule the meeting is running and dynamically adjusts the time available for the talk. My feeling is that an indicator showing "save or loss time" would just be confusing to most speakers. I'll leave this issue open to see if others have strong feelings on it.

**Comment by alanfermtz** [comment]
Could this be implemented at some point?
As I mentioned in my previous comment, it could be an optional feature, and only be observed within the app, just for the multimedia managers to observe, so they can inform the president, how much time we are behind or ahead, and adjust to finish on time.

**Comment by AntonyCorbett** [comment]
Hello @alanfermtz Sorry that I didn't reply to your previous post on this thread. I agree that the feature should be optional if implemented. I view it as an alternative to the _Adaptive_ mode that we already have in OnlyT, and I also believe that the Adaptive mode works very well. I'm reluctant to commit to this extra development unless there is popular support for the idea. Kind regards, Antony

**Comment by alanfermtz** [comment]
We have not tried to use this tool, because I am afraid that they will be confused when they see the clock and notice that the time is up, when they have more time. So, I don't fully understand how the adaptive function really works on practice. 
For example, if in Spirtual Gems the brother takes 12 minutes. From which part will it take that lost time?

Sorry for my bad theocratic language, my first language is spanish

**Comment by AntonyCorbett** [comment]
@alanfermtz The Wiki states "Note that some item durations are never adapted - it depends on the meeting format."

None of the "student" talks have adapted timing - they remain at their stated duration. If "Gems" goes over time by 2 mins, and the "Living as Christians" section begins late, any time that must be made up is shared between all remaining items in proportion to their original stated duration.

Here's an example. Suppose that the "Living as Christians" section begins 10 mins late, and the section features a 5 min talk, a 10 min talk, the 30 min study and the 3 min conclusion.

OnlyT will reduce the items _roughly_ as follows to reclaim the 10 minutes (the actual times will be more precisely calculated):

5 min talk => ~4 mins
10 min talk => ~8 mins
30 min study to ~24 mins
3 min conclusion => ~2mins

Hope this helps.

**Comment by AntonyCorbett** [comment]
Closing now. Please reopen if needed.
