### ISSUE TITLE
settings password

### ISSUE THREAD

**Issue by bergerchemical** [AntonyCorbett/OnlyT#476]
Hi, what do you think about the idea of setting a password to access the settings? It happened several times that someone out of curiosity lit up there, consciously or unknowingly changed the settings and left it like that, perhaps he could not restore the preset settings. I guess it would be nice to be able to block access to settings..

King regards

**Comment by AntonyCorbett** [comment]
@bergerchemical You can set up a shortcut with the "--nosettings" command-line switch to disable the "Settings" button.

**Comment by bergerchemical** [comment]
I didn't know that, thanks, I'll try it
