### ISSUE TITLE
Add one minute for chairman commendation and counsel

### ISSUE THREAD

**Issue by miedzikd** [AntonyCorbett/OnlyT#48]
Hi! 
Thanks for your amazing work! 

> "Counsel: Following each of the four student assignments, the Life and Ministry Meeting chairman has approximately one minute to provide commendation and counsel based on the Ministry School book."

In our congregation Counsel always consumes more than one minute :P 

Can you add one minute periods after each of student assignments?

Sorry for my English...
Greetings from Poland
Daniel

**Comment by TechMan88** [comment]
Brothers giving counsel never give attention to time, so adding more mins will just complicate the timer.

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 21, 2017 at 1:06 AM, Daniel Miedzik<notifications@github.com> wrote:   
Hi!
Thanks for your amazing work!


"Counsel: Following each of the four student assignments, the Life and Ministry Meeting chairman has approximately one minute to provide commendation and counsel based on the Ministry School book."


In our congregation Counsel always consumes more than one minute :P

Can you add one minute periods after each of student assignments?

Sorry for my English...
Greetings from Poland
Daniel

**Comment by AntonyCorbett** [comment]
@miedzikd @TechMan88 Thanks for comments. I think the suggestion is for an automatic 1 minute timer that cuts in as soon as the student talk ends (or perhaps 20 secs afterward as it does in SoundBox). This doesn't complicate the operation of the timer and has proved to be a useful tool (for some) in SoundBox.

**Comment by miedzikd** [comment]
Thanks a lot brothers... I this this can be very important... if chairman insted of 1 minute take 2 minutes for each presentation... he comsumps 4 minutes more... 
In our cong elders ask about that posibility, because they want give attention on that..

but maybe this can be configured option? If some congregations don't care, no problem for them also :)

One more time thanks for fast replay :)
Greetings

**Comment by AntonyCorbett** [comment]
This can now be accommodated by using the "persist talk duration" setting. Set it so that the student's time is displayed for 1 minute (or perhaps 90 secs) after the conclusion of the talk. The chairman knowns that his time is up when the student's time disappears.

**Comment by AntonyCorbett** [comment]
Please see the latest release, which now includes a "Show persist countdown bar" option that can be used with the "persist student time" option to display a countdown bar for the chairman during counsel.
