### ISSUE TITLE
timer screen stop showing time after reach 0.00

### ISSUE THREAD

**Issue by ticrack** [AntonyCorbett/OnlyT#486]
**Describe the bug**
The timer screen show the time perfectly, but when reach 0.30sec it stay green, but the onlyT App show it in yellow. When time is 0.00, the timer screen stop showing any number, but onlyT continu showing down in red.

here a the video: https://1drv.ms/v/s!AgNCELR_-RNgndgr36TMsB06xaNpJQ?e=dlSEXR

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Home
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@ticrack Is the wall display showing OnlyT's Timer Window, or is it the OnlyT web page, or something else? Also, what version of OnlyT are you using, please (shown in Options => Main)? I expect that the wall monitor may be displaying the OnlyT web page and that it is an old version of OnlyT.

**Comment by AntonyCorbett** [comment]
@ticrack Closing now as there is no response. Please reopen if needed.
