### ISSUE TITLE
When timer is displayed how to get to menu

### ISSUE THREAD

**Issue by jurena015** [AntonyCorbett/OnlyT#49]
I switched over from soundbox because timer freezes too often in the middle of the metting. One issue i found in only T is that once timer is displayed how do i get back to the menu so i can start or stop the timer if a part finishes early. Can can hidden ivon be added on timer display for explain clickinh the analog clock or bottom of display.... or do i have to extend my screen to have timer menu on my laptop and timer on the display?

**Comment by AntonyCorbett** [comment]
Normally, you would display the timer output on a different monitor (using extended desktops). However, if you only have a single display, just Alt-TAB back to the app window.
