### ISSUE TITLE
The interface disappears after configuring the timer

### ISSUE THREAD

**Issue by Syntax-Prime** [AntonyCorbett/OnlyT#490]
**Describe the bug**
The interface disappears after configuring the timer or when I click on the normal view icon.

**To Reproduce**
1. Click on the Normal View Icon and the interface disappears. The same thing happens when I try to go back to the timer interface after I click on the settings button.

**Expected behavior**
I am supposed to be able to go back to the control interface when I do any of the above. There are supposed to be two icons on my taskbar to shift from one interface to another but there is only one. Once the interface disappears, I have to manually end the task from the Task Manager.
[log-20210905.txt](https://github.com/AntonyCorbett/OnlyT/files/11412059/log-20210905.txt)

**Screenshots**

**Desktop (please complete the following information):**
Windows 11
![OnlyT](https://user-images.githubusercontent.com/131695924/236617852-684eafaa-8b32-44e2-b179-16b250efb916.png)

Please see the attached log file.

Thank you so much for your assistance.

**Comment by AntonyCorbett** [comment]
@Syntax-Prime thanks for your feedback. The log indicates that you are using ver 2.0.0.8 but the screenshot is from a later version. I wonder if there is some corruption in the installation. Please uninstall all OnlyT installations and install the latest pre-release. Please let me know how you get on.

**Comment by AntonyCorbett** [comment]
@Syntax-Prime please ignore my previous message - I just noticed that the log file you sent is from 2021

**Comment by AntonyCorbett** [comment]
@Syntax-Prime we would benefit from step by step description of what you do and what you see. Also a log file that covers the operation you describe. Thanks in advance

**Comment by Syntax-Prime** [comment]
Hello Brother Antony,

Thank you for getting back to me.

Please see the attached log file.

I went over my programs and there are indeed two OnlyTs installed. I uninstalled both. I also deleted the OnlyT folders on my Documents folder. Just to be sure, I also deleted the OnlyT folder under Program Files.

I downloaded a fresh copy of the installer and installed it.

When I launch it, this is how it looks like.

***@***.***

Then, I click on the settings button.

***@***.***

***@***.***
***@***.***
***@***.***
***@***.***

***@***.***

I then click on the big button above and everything disappears.

***@***.***

It’s not on my taskbar too.

***@***.***

Thank you for your assistance again, brother.

**Comment by AntonyCorbett** [comment]
@Syntax-Prime Thanks for the additional information. The screenshots have not appeared. When replying, it may be better to log into GitHub and insert the images there.

In the meantime, can I suggest you remove all of the OnlyT settings (they are not automatically removed when uninstalling). Do this by closing OnlyT and then deleting the `options.json` file from the `%AppData%\OnlyT\1` folder. Next time you load OnlyT it will be with the default settings.

**Comment by Syntax-Prime** [comment]
Hello Brother Antony,

Thank you so much! That worked!
