### ISSUE TITLE
OnlyT Glitch During Meeting

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#492]
Hello Antony,

On Saturday we experienced some issues with OnlyT during our meeting at the KH. We never experienced this before.

We are publishing the OnlyT Web Clock to our confidence monitor using OBS. The first issue that occurred - the web clock suddenly stopped displaying. When this was reported to me, I went to the sound desk PC and found OnlyT in the "shrinked / minimized" mode. This was interesting because we have "Shrink on minimise" disabled. I attempted to restore OnlyT to the maximized window by clicking the button with 2 diagonal arrows. However, when I clicked that button, OnlyT immediately closed. I tried to launch it again but it wasn't opening. Then I went into Task Manager and found OnlyT as an active task. So I ended the task and then was able to launch OnlyT. Again it was in the "shrinked / minimized" mode. This time, instead of clicking the button with 2 diagonal arrows, I decided to drag out the window from the corner, and this worked. At that point the Web Clock also started working normally. No further issues occurred for the remainder of the meeting.

I attached the OnlyT log file from that day. Our installed version is 2.1.0.1 and the PC is running Windows 11 Pro. The issue started around 10:00 AM. I wasn't near the sound desk when it started happening, so I'm not aware of exactly what triggered this sequence of events. When I asked the brother who was there, he said he didn't notice anything out of the ordinary occur.

We appreciate all your hard work, Antony. Let me know if you have any questions on this issue, or if you need additional details.

[log-20230513.txt](https://github.com/AntonyCorbett/OnlyT/files/11493924/log-20230513.txt)

**Comment by AntonyCorbett** [comment]
@scottys94 Hi Scotty. Thanks for the report. I can't see anything wrong from the log. The Web Server errors are handled properly and can be expected.

I think the only way OnlyT should appear in the shrunk state (with "shrink on minimise" off) is if the user manually reduced the window size. But I can't see how the web server failed. Is there anything in the Windows event log, please?

**Comment by scottys94** [comment]
@AntonyCorbett I apologize for the delay in responding. I checked the Application log and found two entries related to OnlyT. I'm not certain if they are related to this issue in any way. Both entries are pasted below for your reference.
_____________________________________________________________________________
Logged: 5/13/2023 8:53:55 AM
.NET Runtime

Application: OnlyT.exe
CoreCLR Version: 6.0.1523.11507
.NET Version: 6.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.HttpListenerException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at OnlyT.WebServer.HttpServer.ListenerCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.ListenerAsyncResult.IOCompleted(ListenerAsyncResult asyncResult, UInt32 errorCode, UInt32 numBytes)
   at System.Net.ListenerAsyncResult.WaitCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

_____________________________________________________________________________
Logged: 5/13/2023 8:53:56 AM
Application Error

Faulting application name: OnlyT.exe, version: 2.1.0.1, time stamp: 0x63ed8147
Faulting module name: KERNELBASE.dll, version: 10.0.22000.1817, time stamp: 0xf4024b88
Exception code: 0xe0434352
Fault offset: 0x00140d42
Faulting process id: 0x3450
Faulting application start time: 0x01d98599a5f080b7
Faulting application path: C:\Program Files (x86)\OnlyT\OnlyT.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 41e5e50f-baf5-4a69-a4b2-e9f800c8f220
Faulting package full name: 
Faulting package-relative application ID:

**Comment by AntonyCorbett** [comment]
@scottys94 Thanks Scotty - that's very helpful. I can see where to modify my error handling to prevent this.

**Comment by AntonyCorbett** [comment]
@scottys94 Just reviewing some issues. This one was fixed some time ago and I forgot to mark it as fixed and notify you :)
