### ISSUE TITLE
OnlyT Resizes

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyT#506]
Hi Antony

We are finding that OnlyT resizes to miniture for some reason. I am not even sure of how to recreate the issue. 

![Screenshot 2023-07-23 at 9 01 57 AM](https://github.com/AntonyCorbett/OnlyT/assets/35364657/f8c755c2-4ba0-4713-870d-4a8f46df5cf8)

It is easy enough to fix, just click and drag the corner, but not sure why it is resizing in the first instance. 
This is occurring both at home on my PC and the KH. 

I am sorry that is a bit vague. If I notice a pattern I will be sure to update. In the meantime I just thought I would let you know in case there was something easy-to-fix. 

All the best
Simon

**Comment by AntonyCorbett** [comment]
Hi Simon. It should remember the size and state last used. Is that not the case? Also note that when you minimise, it will either minimise to the taskbar (as is usual) or minimise to the shrunken view depending on an option in the settings page.

**Comment by AntonyCorbett** [comment]
Closing as no response. Feel free to reopen if needed.
