### ISSUE TITLE
Duplicate languages

### ISSUE THREAD

**Issue by KovalevArtem** [AntonyCorbett/OnlyT#508]
**Describe the bug**
There are 2 Russian languages in the language settings, which is incorrect.

**Screenshots**
![изображение](https://github.com/AntonyCorbett/OnlyT/assets/36500228/3886a6a9-a630-4834-80ee-2111c3a40c51)

**Desktop (please complete the following information):**
 - Windows version 2.2.0.4

**Comment by AntonyCorbett** [comment]
@KovalevArtem Fixed in repo. Should be available in next release
