### ISSUE TITLE
OnlyT run under normal account access

### ISSUE THREAD

**Issue by tlamari** [AntonyCorbett/OnlyT#51]
Dear AntonyCorbett,

We have recently rebuilt our KH media notebook so the profiles for media playing no longer use Administrator access.  Undortunately we have discovered that the OnlyT timer can only advertise webservice timer control when run under an admin account. A wifi tablet only sees the timer via the browser when OnlyT is run under admin access in the media notebook.

Do you know if we can use profiles under normal account access to advertise Timer control via the webservice? Possibly a registry path can be modified with appropriate security permissions? I have tried to open the 8096 default port using the GUI button but this has not worked.

Thank you kindly for your assistance with this request,

Kind regards,
Tony Lamari

**Comment by AntonyCorbett** [comment]
@tlamari - The web timer works fine under a non-elevated account. The port must be open and the URL reservation made (both are performed when using the "Open Port" button in the Settings page (which _does_ require elevation at the prompt).
