### ISSUE TITLE
Certain text does not apper when using the app.

### ISSUE THREAD

**Issue by ionutthebest** [AntonyCorbett/OnlyT#513]
**Describe the bug**
I own an Android 10 device that is quite old, but still runs relatively well. Recently I downloaded the app for the first time and some text does not show on screen, like the start/stop button text, or any of the menu text. The text that includes the assignment name and the time left still appears.

**To Reproduce**
There are no particular steps required to reproduce this issue.

**Expected behavior**
I expected all the text to appear, as I have seen happen on one of my friend's phones.

**Screenshots**
![Screenshot_20230923-212559_OnlyT](https://github.com/AntonyCorbett/OnlyT/assets/121128696/d3d93b82-631a-4c84-8e53-16a60c6525bb)
![Screenshot_20230923-212523_OnlyT](https://github.com/AntonyCorbett/OnlyT/assets/121128696/95a991f9-b769-4024-b9b5-b525c53d5b6a)

**Desktop (please complete the following information):**
The desktop version should not matter because the app works perfectly fine on my friend's phones, using the same windows connection.

**Comment by AntonyCorbett** [comment]
@ionutthebest thanks for the report. Please contact the app developer for help.
