### ISSUE TITLE
Meeting Countdown Delay

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#522]
Hello Antony,
My congregation uses the meeting countdown feature in OnlyT (version 2.2.0.5). We have the duration set to 5 minutes. However, I am noticing that OnlyT begins the countdown approximately 5 seconds late at the 4:55 mark. I am experiencing the same behavior on multiple PCs.

**Comment by AntonyCorbett** [comment]
@scottys94 Thanks - I have fixed this in the latest pre-release
