### ISSUE TITLE
Client/Server Setup for OnlyT

### ISSUE THREAD

**Issue by scottys94** [AntonyCorbett/OnlyT#523]
Hello Antony,
Would it be possible for the OnlyT installed on our Sound PC to be remotely controllable by another OnlyT instance on a separate PC? We are already using the Remote mobile app and we rely heavily on it. However, the app does not allow us to modify the timing for any of the meeting parts.

Our congregation designates the timekeeping responsibility to the Zoom Video Conference Attendant who is stationed in an auxiliary conference room. If the timing for any parts needs to be adjusted, we would like for him to have access to the main OnlyT instance to make the necessary updates.

If such a feature is possible, perhaps it should require password authentication to connect to the main PC. Thanks for all your support, Antony. And if this can't be done, I'm fine with it. Just thought I'd still ask.

**Comment by AntonyCorbett** [comment]
Hi Scotty. I think the most straightforward option would be to extend the existing API to allow for modification of times.

**Comment by scottys94** [comment]
Hi Antony,
I am closing this issue since we now have a workaround in place. For the designated timekeeper stationed in the rear conference room, we installed a separate laptop with the OnlyT software where the brother can control the timer. On the sound console PC, we have OBS linked to the laptop's OnlyT web clock. OBS has a projection window going out to the confidence monitor. This setup has been working very well for us.

**Comment by AntonyCorbett** [comment]
@scottys94 Thanks for the feedback.
