### ISSUE TITLE
Proposed Adjustment to Midweek Adaptive Mode

### ISSUE THREAD

**Issue by MiltJR111** [AntonyCorbett/OnlyT#524]
**Is your feature request related to a problem? Please describe.**
Last night we had our Midweek meeting, and instead of the first Living As Christians part, we watched the Governing Body Update #4. As such, that "part" shows as going overtime by more than 7 minutes. The Adaptive mode adjusted the next part to a little more than 3 minutes (even though we were still alotting the full 5 minutes for it), and that brother also happened to go overtime by quite a few minutes. When it came time for the Congregation Bible Study, OnlyT (for some reason) allocated the entire 30 minutes for the part, rather than reducing the time accordingly.

**Describe the solution you'd like**
I would prefer that for the Midweek Meeting, there be an option to always take the "extra" time from the Bible Study, as I believe most congregations do that when other parts go overtime. If not automatically, then perhaps an option related to Adaptive mode to leave the other parts alone, and only adjust the Bible Study based on how much time is remaining.

**Describe alternatives you've considered**
The only other option would be to use a File-based schedule for meetings that have "substitute" parts, but since I believe the Branch directs all of the congregations to show the Governing Body updates, a centralized solution makes more sense. Also, using a File-based schedule would mean that no Timing Report is generated, so the Auxiliary Counselor wouldn't be able to use it to review the meeting timings.

**Additional context**
I'm attaching the Timing Report from the Meeting so you can see exactly how OnlyT allocated the time. It appears to be very confused.
![2024-07-09.pdf](https://github.com/user-attachments/files/16164415/2024-07-09.pdf)

**Comment by AntonyCorbett** [comment]
Thanks for the report. It looks like there is an issue here, which I’ll investigate. On a more general note, if you know in advance that an item will take longer than the allocated time, simply adjust it manually before the meeting, e.g. in this case you might add 8 mins to the first item and deduct 8 mins from the study.

**Comment by MiltJR111** [comment]
> Thanks for the report. It looks like there is an issue here, which I’ll investigate. On a more general note, if you know in advance that an item will take longer than the allocated time, simply adjust it manually before the meeting, e.g. in this case you might add 8 mins to the first item and deduct 8 mins from the study.

Thanks for the suggestion! I didn't realize we could manually adjust the items in the drop down and have that persist for the meeting timing. I guess that's a relatively new feature, and a great addition. I'll keep that in mind for next time.

The brothers have really come to rely on having OnlyT so thank you so much for all your hard work on it!

**Comment by AntonyCorbett** [comment]
You’ve always been able to manually modify the duration of these items. It’s particularly useful when you know that the announcements will take longer than 3mins.

**Comment by MiltJR111** [comment]
> You’ve always been able to manually modify the duration of these items. It’s particularly useful when you know that the announcements will take longer than 3mins.

Oh, you know what it is? If you manually modify them, the drop down still displays the original time, so I thought it wasn't working. I didn't even bother checking whether it's correct in the app or when you get to that part (which it is). Maybe you could allow the drop down to have the adjusted time as well, in case anyone else makes the same mistake that I did?

**Comment by AntonyCorbett** [comment]
@MiltJR111 I have investigated the issue first reported (where the study duration was _not_ adapted. This is because OnlyT's "adaptive time" algorithm gives up if it calculates that an item has a deviation of more than 15 mins (as was the case in your example). i.e. in these circumstances, it assumes that you have abandoned the original schedule.

**Comment by AntonyCorbett** [comment]
@MiltJR111 The dropdown box now displays manually modified times. See the latest release,
