### ISSUE TITLE
How much will SoundBox be 'broken up'?

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyT#54]
Hi Antony,
As I understand it, OnlyT and OnlyR are independant apps that were part of what SoundBox was doing as a complete unit.  In theory, JWL will be the go-to app for playback of meeting media and images, however I doubt that it will cater for third party images such as a brother might use for a PT.  I know that VLC is the 'recommended' media player for content other than what JWL will cater for, but SoundBox as a media player is far superior in so many ways I cannot see it not being used after 2018 for that feature alone.  Will you continue to produce other apps that SoundBox does already? Specifically I am referring to a media player as user friendly as SoundBox is?  Absolutely no pressure, just curious as to what your plans might be... <smile>

**Comment by AntonyCorbett** [comment]
@Chipperchap - there's a possibility I might create an application for video and images, but I want to see what changes are made to JWL in 2018 first.
