### ISSUE TITLE
Changing the background color at the program level 

### ISSUE THREAD

**Issue by Matthew-Gaydachuk** [AntonyCorbett/OnlyT#56]
Hello, dear brother!!! Thank you for your excellent work - it's very valuable. Have a one question... 
How to change the background color from pinkish-and-burgundy shades to the bright green color in the Analogue Clock? And how to remove the frame from the same Analogue Clock?
I'm using JetBrains dotPeek to decompile your .dll libraries.
Could you help please? That would be wonderful!!!

Sincerely, brother Matthew.

**Comment by AntonyCorbett** [comment]
@Matthew-Gaydachuk - no need to decompile; you have the source code.

ClockPanel.BorderThickness = 0
ClockPanel.Border.Background = ...

I hope you're joking about making it bright green :)
