### ISSUE TITLE
Cannot access timer settings.

### ISSUE THREAD

**Issue by tkit090** [AntonyCorbett/OnlyT#57]
Accidently selected the main monitor for the clock/timer and cannot access settings to change it back. Tried pressing Alt Tab and when I click on the settings button it just goes back to the clock. Have uninstalled and reinstalled but it keeps opening the clock on the main monitor. Admin user account works fine. KHUser local account will not work. Both short cuts are from the Public user account.

**Comment by tkit090** [comment]
Finally figured it out. Had to disconnect the second monitor and then Alt Tab worked to access the settings with the clock and main control on the same screen.

**Comment by AntonyCorbett** [comment]
@tkit090 - thanks for your help. Now fixed.
