### ISSUE TITLE
Countdown timer on undesired monitor?

### ISSUE THREAD

**Issue by mbrakutt1** [AntonyCorbett/OnlyT#58]
Hello Antony great program I've had OnlyT for a quite a while and I must say everything about it is great, the idea itself along with it's concept, fantastic piece of code. I am trying to make use of the countdown timer however when the window initiates to begin the 5 minutes counter it becomes active on my main monitor not on the second where it is suppose to override the current time window, I am also running the latest version. Here is my [log](https://pastebin.com/EH1ic9x9)

**Comment by AntonyCorbett** [comment]
@mbrakutt1 - close down and restart the app. Let me know if it's still a problem

**Comment by mbrakutt1** [comment]
I've tried that once again, the countdown starts on main display while the time window closes on the second. However when I close the countdown with the assigned button the countdown closes and the time window reappears I believe I had this problem even in the pre-release.

**Comment by AntonyCorbett** [comment]
@mbrakutt1 - thanks. I can't reproduce this and looking at the code I can't see how it might happen. Please would you check that your video driver is up to date?

**Comment by mbrakutt1** [comment]
I see, is it because I have two gpu's? an integrated Intel and dedicated NVIDIA, I updated my dedicated card and my integrated is up to date, after updating I rebooted my machine I've also tried switching the gpu's to run the program but to no avail. I forgot to mention upon start-up when navigating to the settings page the program remembers the second monitor (actually selected) but yet displays the time on the main monitor, so I have to select the first one where the window shuts off and re-appears for a split second and then select the second monitor where it finally displays and then the countdown problem begins.

**Comment by AntonyCorbett** [comment]
@mbrakutt1 - Please would you try the latest release? https://github.com/AntonyCorbett/OnlyT/releases/latest

**Comment by mbrakutt1** [comment]
Latest version installed I'm afraid nothing has changed here is the [log ](https://pastebin.com/raw/sfAFWGYN) (first launch followed by restart)

**Comment by AntonyCorbett** [comment]
@mbrakutt1 - please go to the settings page and check that the dropdown "Monitor" list contains your 2 monitors

**Comment by mbrakutt1** [comment]
@AntonyCorbett - yes I am seeing my 2 monitors on the drop down list

**Comment by AntonyCorbett** [comment]
@mbrakutt1 - I can only suggest that you install specifi drivers for your cards since they are using the Windows generic ones at the moment.

**Comment by mbrakutt1** [comment]
@AntonyCorbett  - I get it now, I downloaded the driver for my external monitor now in the drop down selection it shows my monitor name instead of generic PnP but I am using a laptop how can I download a driver for my built-in display? 

Countdown works perfectly when I set my second monitor to main display (expected outcome)

**Comment by AntonyCorbett** [comment]
@mbrakutt1 you need to find out the make and model of the display and then refer to the manufacturer's website
