### ISSUE TITLE
The automatic mode don’t update the meeting items.

### ISSUE THREAD

**Issue by ricardoantonio** [AntonyCorbett/OnlyT#59]
The time for the meeting items is always the same in automatic mode.

**Comment by AntonyCorbett** [comment]
@ricardoantonio - please would you provide more information.

**Comment by ricardoantonio** [comment]
![captura](https://user-images.githubusercontent.com/11904265/36828671-d2f9957a-1ce0-11e8-9c93-d345bd773dc3.png)

The items of the living part, never change. I took this screenshot this week.

**Comment by AntonyCorbett** [comment]
@ricardoantonio that's odd. The "Ministry" item timings are correct for this week, but not the "Living" sections. Please would you send me this file:

C:\Users\[your name]\AppData\Roaming\OnlyT\feed.json

And also your latest log file from (Documents\OnlyT\Logs)

Thanks
Antony

**Comment by AntonyCorbett** [comment]
@ricardoantonio I think you may be using an old version

**Comment by ricardoantonio** [comment]
I use the 1.0.0.47 version. Sorry, I will send you the files next sunday before the weakend meeting.

**Comment by ricardoantonio** [comment]
I updated to 1.0.0.48 versión and works ok. Thank you.

**Comment by AntonyCorbett** [comment]
@ricardoantonio that's good. Must have been owing to the bug I just fixed. Thanks for letting me know.
