### ISSUE TITLE
Enhancement - Display Song Number

### ISSUE THREAD

**Issue by greggjf** [AntonyCorbett/OnlyT#60]
Would be great to have the ability to display the song number on the board, doesn't have to auto fill but be available to add manually for each part of the meeting.

**Comment by donavan1** [comment]
Hi
This should be an option were the timer is set to digital only as the timer screen does not get cluttered. If this option is selected then there are fields to enter song numbers to display  at the specific time interval.

**Comment by Brrwolf** [comment]
Hi, we  have just started using these new programs for the meetings and we would like the Song # to be listed on the back screen.. Any chance to get this added ??
Richard

**Comment by timjobutler** [comment]
Our hall is migrating from a custom built timer app to OnlyT. The current app we use has the ability to autofill the song numbers and display them on the timer monitor. The song number fields were editable so they could be override as needed, i.e. circuit overseers, or manually filled in for public talks.

Having this feature would be a handy reference for the chairman.

**Comment by AntonyCorbett** [comment]
Thanks for your suggestion. I am closing the issue for now as I am trying to limit the feature-set to essentials.
