### ISSUE TITLE
Three monitors support

### ISSUE THREAD

**Issue by Lameleck** [AntonyCorbett/OnlyT#64]
Chapeau bas! Great job, very helpful.
Main topic: Soundbox has nice feature to manage more then two displays, very useful to display timer on a Speakers timer monitor and a startup timer on a main monitor for media. Would be nice to have such possibility in OnlyT. Startup timer could be always on top before meeting begun, after will disappear.

**Comment by AntonyCorbett** [comment]
@Lameleck We have discussed this before and concluded that we won't place anything on the main media display before the meeting because the instructions state that it should show the Year Text (i.e. from JW Library). Thanks for your feedback - it's very welcome.

**Comment by Lameleck** [comment]
Sorry I haven't found this information, but transparent digital clock in selectable corner could be compromise.

**Comment by AntonyCorbett** [comment]
Yes, we thought of that too, but didn't think it was appropriate. Additionally, JWL uses a special UWP maximise mode that means it's technically awkward to overlay content on it without it disappearing.

**Comment by dazzathestag** [comment]
Apologies that this question is slightly off topic but I was interested in reading Anthony’s comment about the overlap being difficult. In our screens when the years text appears, a few months ago two small icons have started appearing. They are small but very noticeable and from memory they look like control icons like the “pause” symbol. They are in different places on the screen and not in line with anything else.

We simply can’t work out what could be placing them there - any ideas ? They don’t appear on any other screen only the year text.
