### ISSUE TITLE
Background/font color options 

### ISSUE THREAD

**Issue by EfreAvilaJr** [AntonyCorbett/OnlyT#65]
Hello Anthony, I was wondering if there's a possibility of adding the ability to change the background and font color (currently brown and white) to the clock displayed on the 2nd/3rd monitor.

**Comment by AntonyCorbett** [comment]
@EfreAvilaJr - it wouldn't be sensible to allow independent setting of background and text colour since they may easily clash with the analogue clock colours. But I may consider several themes. What are your preferred colours?

**Comment by EfreAvilaJr** [comment]
How about the color theme from the “Sing Out Joyfully” (gray background & black fonts, or white background and black or blue fonts???

**Comment by AntonyCorbett** [comment]
@EfreAvilaJr I'll leave the question here for another week or so to see if anyone else feels strongly about it.

**Comment by AntonyCorbett** [comment]
Closing as no further feedback from others.
