### ISSUE TITLE
Diffrent meeting countdown style

### ISSUE THREAD

**Issue by IliasBosman** [AntonyCorbett/OnlyT#68]
Is it possible to have a diffrent meeting countdown style?
rather than the large circle becoming smaller?
maybe just the standard analogue  clock with the green area becoming smaller.
like the normal operation only than for meeting countdown?

Greetings, Ilias Bosman from Holland

**Comment by AntonyCorbett** [comment]
It follows the regional convention style. Please let me know if there's a problem with the current countdown that is solved by a conventional clock? If a conventional clock will do then perhaps just disable the countdown and use the one that's provided. Thanks for feedback.

**Comment by AntonyCorbett** [comment]
Closing as no response
