### ISSUE TITLE
Student talk time stuck on permanently

### ISSUE THREAD

**Issue by Jeremy909** [AntonyCorbett/OnlyT#70]
The timer for the last student part stays stuck on the monitor and does not return to the Clock. It would be useful to the Chairman to be able to see what time it is when he introduces the song for the Living as Christians part of the meeting.

**Comment by AntonyCorbett** [comment]
see #36

**Comment by AntonyCorbett** [comment]
Please see 1.1.0.12

Added "Persist talk time" option to allow you to turn off the continued display of talk times after the conclusion of a student talk.

Added "Persist talk duration" option to specify how long the talk time should remain on screen after the conclusion of a student talk.
