### ISSUE TITLE
Countdown Close Button

### ISSUE THREAD

**Issue by Blann** [AntonyCorbett/OnlyT#71]
![capture](https://user-images.githubusercontent.com/39594788/42419732-73a6f6ca-82b2-11e8-9e19-35677742986f.PNG)

Small thing - with the new theme, the text on the 'Close Countdown' button is white and is thus not easily read.

**Comment by AntonyCorbett** [comment]
@Blann - great. Thanks for the report. Now fixed.

**Comment by AntonyCorbett** [comment]
@manuelvita96 from the wiki:

Meeting countdown => Enable meeting countdown - Check this box to display a 5-minute countdown to the start of your meeting.

Meeting countdown => Meeting start times - Specify the start times of your meetings (1 per line). The countdown timer begins automatically.
