### ISSUE TITLE
Filebase config upload to OnlyT

### ISSUE THREAD

**Issue by donavan1** [AntonyCorbett/OnlyT#72]
HI
As anyone tried to upload a filebase timer file for the regional assembly 2018.
Reason: My config file does not display on the app.
filebase.zip

note: this is just to test before it can be applied.
[filebase (1).zip](https://github.com/AntonyCorbett/OnlyT/files/2180078/filebase.1.zip)

**Comment by manuelvita96** [comment]
The XML file work, maybe it's wrong the folder

**Comment by donavan1** [comment]
Hi

Can you confirm the folder path.

C:\Program Files (x86)\OnlyT

Note: The original xml ( which works fine) if I make a copy and edit the
original and place it back in the same folder it does not work, the only
edit I made was the name and the time. Now if I replace the original it
works.

**Comment by donavan1** [comment]
Here is the original.

If I change "welcome" to "Chairman's Address" else and the duration="00:10:00" and save it still does not work. But if I revert it back to the original it works. I even tried re-installing the app.

**Comment by AntonyCorbett** [comment]
@donavan1 From the wiki: In File-based mode you can specify an xml file named "talk_schedule.xml" containing the meeting items and store it in your "Documents\OnlyT" folder

**Comment by donavan1** [comment]
Thanks, its now fixed.
I specified the  xml file named "talk_schedule.xml" in the  "Documents\OnlyT"
folder not in the  C:\Program Files (x86)\OnlyT.
