### ISSUE TITLE
API - missing variables

### ISSUE THREAD

**Issue by rafik73github** [AntonyCorbett/OnlyT#74]
Welcome

Can you add the variable "timeElapsed" in seconds format (It may be in milliseconds)? There may be an additional variable, e.g. "timeElapsedInSeconds". In the Soundbox there was one very useful variable "isStudentTalk". My project in Arduino supports 4 displays. The variable "isStudentTalk" would allow you to choose which displays to be active.

Thank you and best regards.

**Comment by AntonyCorbett** [comment]
@rafik73github thanks for your comments on the API. The "timeElapsed" value is in the form 00:00:00.000 (hours:minutes:seconds.ms) - please parse it as required. 

Unfortunately "isStudentTalk" doesn't have any analogue in "file mode" and I have tried to keep the timer generic in operation. You could perhaps examine the "usesBell" property which will - by default - be enabled for student talks.

Please see the wiki for a full description of the API.

**Comment by rafik73github** [comment]
Thanks for help.
