### ISSUE TITLE
ApiCode not working

### ISSUE THREAD

**Issue by rafik73github** [AntonyCorbett/OnlyT#76]
Hello
I'm trying to use ApiCode but it does not work. It is entered in the OnlyT settings, e.g. 123456, then it is entered into OnlyT on Android and does not work. What am I doing wrong?
Greetings

**Comment by AntonyCorbett** [comment]
The code is optional. So does it work without one?

**Comment by rafik73github** [comment]
yes

**Comment by K0rTy** [comment]
What is the Android application you are using? rafik73github

**Comment by rafik73github** [comment]
OnlyT Remote

**Comment by K0rTy** [comment]
By iMatt Solutions this https://play.google.com/store/apps/details?id=com.imattsolutions.onlyt ?

**Comment by rafik73github** [comment]
Yes. This one. :)

**Comment by K0rTy** [comment]
Well, that did not work for me.

**Comment by AntonyCorbett** [comment]
@rafik73github I can reproduce the problem and will report it to the app developer.

**Comment by AntonyCorbett** [comment]
@rafik73github I discovered this was a bug in OnlyT. Now fixed in 1.1.0.15. Sorry for inconvenience!
