### ISSUE TITLE
Add Output Volume to Setings>App olume and device preferences

### ISSUE THREAD

**Issue by ucphinni** [AntonyCorbett/OnlyT#78]
In windows 10, there is an output sound device in Settings>Sound>App volume and device Preferences.

OnlyT is not listed in this configuration item.  If it was there, it would be possible to send the sound though the third monitor.  If this is not feasible, should be able to change the default audio device from OnlyT from the settings.

Reasons:

1. It does not jar the entire congregation when the bell goes off.  Sound volume is also localized.
2. It is localized to onlyT which is facing the stage and hopefully close to it.
- A bit of a stretch but if you are using OnlyT in 2 schools, then it does not affect the other school as much or at the very minimum you know where the sound is coming from.
- Brothers are more likely to respond on stage if it is localized to them.  There is some type of psychological effect that is going on.  Notice how distracted when a cell phone goes off versus something going through the sound system.  Friends will respond by mentally searching out a local distraction to see if they can shut it down. 
- Its less embarrassing.

**Comment by AntonyCorbett** [comment]
@ucphinni Thanks for the suggestion. I think your environment is an unsual one (but I could be wrong). Most timer monitors are located at the rear of the hall and facing towards the platform. Most timer monitors have no audio capability (and are typically run from USB adapters). As you note, OnlyT uses the default audio playback device for the bell (with volume adjustment available in the settings page). This means (I think) that it should be possible to set the volume to a level that is audible to the student(s) and chairman while not startling the audience. There would have to be a strng consensus to add the feature you request. Let's see what others think. Thanks again for the feedback.

**Comment by blazer2004** [comment]
@ucphinni :That is a really awesome idea. Provided you have either SDI or HDMI driving your third monitor, this is available right now. Open OnlyT, Open advanced sound settings. Play the test bell in OnlyT. I believe you will find OnlyT shows up in the list of apps in sound settings. From there, you can select your third monitor as your OnlyT specific output device. Hope this helps.

**Comment by ucphinni** [comment]
Thanks blazer2004. That suggestion works! When I opened that advanced sound settings,  I never thought to try to play the bell first before looking at the list. I just tested it and it would have worked if we were connected directly to the desktop.  Our desktop has a 2 display limitation, but I just setup a workaround which does not allow for the audio to be sent to the third monitor ☹

BTW: My setup is somewhat convoluted.   (I was given the responsibility of adding a third monitor and am testing a feasible setup)

The third display on computer is really a spacedesk(software) display with the  laptop as a spacedesk viewer with a duplicated display through the laptop’s hdmi port to a sdi connection and finaly to the third monitor.  OBS is used to copy the second display to the third display in realtime and a browser source with the webclock  is overlayed on top of the screen. (In the below snapshot, ignore the borders as this is teamviewer)  I will be working on python scripts to ensure everything comes up successfully.

Afterthought, might forgo the spacedesk for NDI output from desktop to the laptop using OBS NDI Source.  This might be more futureproofed and more stable.

**Comment by blazer2004** [comment]
@ucphinni  Glad to here it. I noticed when i tried it that any app I wanted to output (thinking of media players like JW library), I have to play a sound first for the list to populate, much like the volume mixer in the task bar. 
Perhaps as a local sound source, a bluetooth speaker could be tried. Have not attempted it myself, may work, may not. 
As a observation, simplicity is our friend. Suppose we should take the six foot subway to the new world, we would not want to leave reasons for our brother working behind us to speak badly of us trying to figure out how we made things work. ( I'm one to talk, my wiring diagrams detailing our ATEM setup aren't 100% complete yet either.) Hope it works out for ya

**Comment by ucphinni** [comment]
Agreed. I like your illustration of 6 Foot subway.

Simplicity is difficult when direction is not to replace , just extend with a limited budget.  Like new wine in old wineskin we see the effects. We got just renovated 2 years ago finally have the drive to  add another display to add timer/confidence monitor.  If we had done it a computer that could support 3 displays, would have been very easy and simple.

Lessons learned.

**Comment by ucphinni** [comment]
This enhancement can be closed.  Even with the remote computer, it works reliably through OBS using NDI in windows 10.  Thanks.
