### ISSUE TITLE
Ministry Metting Keep time

### ISSUE THREAD

**Issue by talkingdragon** [AntonyCorbett/OnlyT#79]
When we do the timing at the ministry meeting the one taking the school likes to see how long the bother took. Especially when its a student assignment. Is there maybe a way can keep the last time visible maybe when doing the counsel? If Also can have the counsel timed? We thinking of setting up a monitor with a RaspberyPi to auto open only the web address of the timer. So the all features would be grate to be on the web version if possible. Thks :)

**Comment by Blann** [comment]
Hi, not sure about on the web clock but there is an option for this in the app already. From the wiki:

“Automatic mode => Persist student time - Check this box if you want to display a student's talk duration after the conclusion of the talk. This can be useful for the chairman.”

Timer window => Persist talk duration - Specify how long the final talk duration should be displayed after the conclusion of a talk (this can be useful for the chairman). This only applies to talks with the "persist" attribute such as student talks in Automatic mode.“

**Comment by AntonyCorbett** [comment]
@talkingdragon closing as the features are already provided. Please feel free to raise a new issue regarding the web clock if you want
