### ISSUE TITLE
Web clock: Showing times with 60 seconds rather than 0

### ISSUE THREAD

**Issue by josslamberti** [AntonyCorbett/OnlyT#81]
Issue:
Given I'm using the web clock on a mobile device 
When the timer reaches n minutes and 0 seconds
Then the web clock shows n-1 minutes and 60 seconds

Steps to reproduce:
1. Enable remote access and apps
2. Open 192.168.n.n:8096/index on (possibly) any mobile device
3. Start timer on PC 
4. Wait til the timer reaches nn:00 and observe on the mobile device

Expected behaviour:
I'd expect the web clock to match the timer and correctly show 07:00

Screenshot:
![image](https://user-images.githubusercontent.com/30600877/46140740-d19e1700-c249-11e8-81a0-b43fa22ef933.png)

Environment:
 - Windows 10,  64 bits (Edit: running v1.1.0.17)
 - Timer shown on a Nexus 7 (2013) via a Webview using Lynket Browser (https://play.google.com/store/apps/details?id=arun.com.chromer) started via a Tasker task shortcut, but don't be distracted by that, it's also reproducible when using a standard Chrome tab on another Android device, an iPhone or the PC itself

**Comment by donavan1** [comment]
Hi
Have you installed the new update ?

**Comment by josslamberti** [comment]
Yes, I'm running 1.1.0.17

**Comment by josslamberti** [comment]
Great response time! Thanks a lot for all these fantastic tools.

**Comment by AntonyCorbett** [comment]
@josslamberti thanks for reporting this - it crept in during a recent revision!

**Comment by AntonyCorbett** [comment]
@josslamberti now fixed in latest release.

**Comment by josslamberti** [comment]
#81 checked against build 18, fix confirmed. Thanks again!
