### ISSUE TITLE
Countdown on Auditorium Screens

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyT#82]
Countdown timer shown on timer screen (back-of-hall) but not on main auditorium screens.  (The friends have become accustomed to it when we used SoundBox and would make their way to their seats and the meeting always got underway in a timely manner.)

When the countown timer option is chosen, have the selectability to choose to also show on the Auditorium screens in addition to the timer screen.  

Alternatively, if OnlyT can only handle one screen option at a time, Countdown on the auditorium screens but regular meeting timer on the back-of-the-hall screen...?

**Comment by AntonyCorbett** [comment]
@Chipperchap please see #9

**Comment by Chipperchap** [comment]
Okay, thank you Antony, I didn't see it that way.

**Comment by AntonyCorbett** [comment]
@Chipperchap yes, understood. I may need to change my view :)

**Comment by Chipperchap** [comment]
Forgive me, I am not wanting to press the issue unnecessarily, I just wondered if having a countdown timer on the screens for 2-3 minutes would _really_ impact on the JWL image of the **_Year Text_** since it is there for most of the meeting anyway.... and prior to /post the countdown timer - hence why the request...  :)  

Sorry, I truly appreciate things the way they are... I can only ask, and be ready to be told **_"NO!"_** :)  👍

**Comment by Chipperchap** [comment]
Thank you so much Antony.
Please, in version 1.1.0.39 where do I find this feature / option? I cannot find it under the 'Meeting Countdown' section.

**Comment by AntonyCorbett** [comment]
@Chipperchap it's in the latest pre-release. See Releases page

**Comment by Chipperchap** [comment]
Ah, there it is.  Thank you! Seems to be working fine too.
Any reason why 5 minutes in particular was selected as the duration of the pre-meeting countdown timer? (Just curious).

**Comment by AntonyCorbett** [comment]
@Chipperchap 5 mins seemed a reasonable value

**Comment by Chipperchap** [comment]
@AntonyCorbett Fair enough.  With SoundBox I had selected 3 minutes as that 'seemed a reasonable value'... 
...no particular reason why...    😁 

At convention level we are used to five minutes I suppose. 👌 

I am looking forward to implementing the auditorium screens countdown again as we became quite accustomed to having it on the screens and the congregation responded to it really well with our meetings beginning on time!    😏

**Comment by AntonyCorbett** [comment]
@Chipperchap "Transparent background" is now available in the latest pre-release

**Comment by Chipperchap** [comment]
Hi Antony,
I have installed and had a play.  Set it to 'bottom left' and adjusted the zoom level to fit under the year-text nicely. It appears to be working okay.  Will give it a meeting or two and let you know how it is going / received by the friends.
