### ISSUE TITLE
'Persist student time' not taken into account on web clock

### ISSUE THREAD

**Issue by josslamberti** [AntonyCorbett/OnlyT#84]
Issue:
Given the countdown is running against an item with persist=true 
When the countdown is stopped
Then the web clock does not persist the student's time

Steps to reproduce the behaviour:
1. Enable Persist student time
2. Set Persist Talk duration to a testable time (e.g. the default 90s)
3. Access the web clock 
3. Start and stop the timer on one of the students items
4. Compare the main monitor and web clock 
Note: reproducible with both file based and automatic modes

Expected behaviour:
I'd expect the web clock to match the main monitor clock and keep on showing the student's time for the specified amount of time.

Observations:
I understand that technically, this is likely not a bug but a missing feature.
I also understand that this is likely not as straight forward as it might look.
We need to use a tablet to show our countdown because the PC's GPU only supports 2 monitors, one for the sound assistant and one for the projector.
I am looking at this feature to cater for the issue of keeping an eye on the counselling times (see your suggestion in #48).

Screenshot:
![image](https://user-images.githubusercontent.com/30600877/46572559-06b01500-c980-11e8-91b9-74b6bc57b53a.png)

Desktop:
 - Windows 10 64-bits
 - Running v1.1.0.18

**Comment by AntonyCorbett** [comment]
@josslamberti you're right, it's not implemented on the web clock. You can add another monitor using a USB-HDMI adapter card.

**Comment by josslamberti** [comment]
Fair enough. I don't think I'll be able to justify buying a new monitor for that. Something to investigate. Thanks!

**Comment by AntonyCorbett** [comment]
Thanks for your suggestion. I am closing the issue for now as I am trying to limit the feature-set to essentials.

**Comment by AntonyCorbett** [comment]
@josslamberti Persist is now included.  Please see the latest release, which now includes a "Show persist countdown bar" option that can be used with the "persist student time" option to display a countdown bar for the chairman during counsel.
