### ISSUE TITLE
Meeting countdown on webclock?

### ISSUE THREAD

**Issue by mbrakutt1** [AntonyCorbett/OnlyT#85]
I think it would be nice to have this feature, since all our brothers use devices nowadays, all they need to do is download the [Lynket ](https://play.google.com/store/apps/details?id=arun.com.chromer&hl=en) app where they can set the webclock address and be able to preview the time with the handy web head feature, for those of you who don't know it acts as a Facebook Messenger's chat bubble so you can open any website in it and minimize it back to the bubble located at the side of screen, this makes multitasking a breeze and completely eliminates the need for the brothers to always look back or look up at the timing monitor.

**Comment by josslamberti** [comment]
We already have the countdown on the web clock, don't we? Or did you mean count up? (See #32)

**Comment by mbrakutt1** [comment]
My bad I meant to say meeting countdown on the webclock

**Comment by AntonyCorbett** [comment]
Thanks for your suggestion. I am closing the issue for now as I am trying to limit the feature-set to essentials.
