### ISSUE TITLE
Meeting countdown

### ISSUE THREAD

**Issue by AntonyCorbett** [AntonyCorbett/OnlyT#9]
Overlay a meeting countdown timer on the specified monitor.

Unlikely to do this, since this could be used to overlay the timer on the JWL year text.

**Comment by AntonyCorbett** [comment]
(Adding to the JWL display would not be appropriate)

**Comment by TiagoPaisAlmeida** [comment]
Thank you for the answer. I agree with you. We shouldnt' conflict with jw library functions. Sorry for the question. Best regards.

**Comment by PXLink** [comment]
Hi. Thanks for your work an the nice tools.

The meeting countdown is very usefull.
But it doesn't work, if you not choose an main monitor.

We don't want the big clock the whole time, we just need the meeting countdown on our beamer. Is it possible to run the meeting countdown without choosing an main monitor? Or an option to deactivate the main clock?

**Comment by AntonyCorbett** [comment]
@PXLink thanks for spotting the bug. It should be possible to select a monitor for the countdown but not for the main timer.

**Comment by AntonyCorbett** [comment]
@PXLink See #163

**Comment by AntonyCorbett** [comment]
@PXLink fixed
